export type TranslationKeys = {
    ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: string;
    INPUT_PLACEHOLDER: string;
    SEARCH: string;
    PAGE: string;
    OF: string;
    SOURCE: string;
    NO_ANNOUNCEMENTS_FOUND: string;
    SEE_DETAILS: string;
    DISCOVER_MORE: string;
    INDIAN_ANNOUNCEMENTS: string;
    SEE_MORE: string;
    VIEW_ALL: string;
    VIEW_DETAILS: string;
    DESCRIPTION: string;
    SEE_ANNOUNCEMENTS: string;
    LOAD_MORE: string;
    SOMETHING_WENT_WRONG: string;
    SUBSCRIBE_TO_ALERTS: string;
    NEVER_MISS_AN_UPDATE: string;
    SUBSCRIBE: string;
    ENTER_YOUR_EMAIL: string;
    PLEASE_ENTER_YOUR_EMAIL: string;
    PLEASE_ENTER_A_VALID_EMAIL: string;
    SUCCESSFULLY_SUBSCRIBED: string;
    FAILED_TO_SUBSCRIBE: string;
    SHARE_ANNOUNCEMENT: string;
    HELP_OTHERS_DISCOVER: string;
    CHECK_OUT_THIS_AMAZING: string;
    SHARE_ON: string;
    CLICK_OPTION_TO_SHARE: string;
};

export const TranslateText: Record<string, TranslationKeys> = {
    English: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "All Government Announcements in One Place",
        INPUT_PLACEHOLDER: "Search type or title....",
        SEARCH: "Search",
        PAGE: "Page",
        OF: "of",
        SOURCE: "View Official Source",
        NO_ANNOUNCEMENTS_FOUND: "No announcements found",
        SEE_DETAILS: "See Details",
        DISCOVER_MORE: "Discover More",
        INDIAN_ANNOUNCEMENTS: "Indian Announcements",
        SEE_MORE: "See More",
        VIEW_ALL: "View All",
        VIEW_DETAILS: "View Details",
        DESCRIPTION: "Automatically collects government announcements from across India and translates them into simple text.",
        SEE_ANNOUNCEMENTS: "See Announcements",
        LOAD_MORE: "LOAD MORE",
        SOMETHING_WENT_WRONG: "Something Went Wrong",
        SUBSCRIBE_TO_ALERTS: "Subscribe to Alerts",
        NEVER_MISS_AN_UPDATE: "Never miss an update, get weekly alerts",
        SUBSCRIBE: "Subscribe",
        ENTER_YOUR_EMAIL: "Enter your Email",
        PLEASE_ENTER_YOUR_EMAIL: "Please enter your email",
        PLEASE_ENTER_A_VALID_EMAIL: "Please enter a valid email address",
        SUCCESSFULLY_SUBSCRIBED: "Successfully subscribed",
        FAILED_TO_SUBSCRIBE: "Failed to subscribe",
        SHARE_ANNOUNCEMENT: "Share Announcement",
        HELP_OTHERS_DISCOVER: "Help others discover this",
        CHECK_OUT_THIS_AMAZING: "Check out this announcement",
        SHARE_ON: "Share on",
        CLICK_OPTION_TO_SHARE: "Click above to share with your network"
    },
    हिन्दी: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "सभी सरकारी घोषणाएँ, एक ही स्थान पर",
        INPUT_PLACEHOLDER: "खोज प्रकार या शीर्षक....",
        SEARCH: "खोज",
        PAGE: "पृष्ठ",
        OF: "का",
        SOURCE: "आधिकारिक स्रोत देखें",
        NO_ANNOUNCEMENTS_FOUND: "कोई घोषणा नहीं मिली",
        SEE_DETAILS: "विवरण देखें",
        DISCOVER_MORE: "अधिक खोजें",
        INDIAN_ANNOUNCEMENTS: "भारतीय घोषणाएँ",
        SEE_MORE: "और देखें",
        VIEW_ALL: "सभी देखें",
        VIEW_DETAILS: "विवरण देखें",
        DESCRIPTION: "पूरे भारत से सरकारी घोषणाओं को एकत्रित और अनुवादित करता है।",
        SEE_ANNOUNCEMENTS: "घोषणाएँ देखें",
        LOAD_MORE: "और लोड करें",
        SOMETHING_WENT_WRONG: "कुछ गलत हो गया",
        SUBSCRIBE_TO_ALERTS: "अलर्ट के लिए सब्सक्राइब करें",
        NEVER_MISS_AN_UPDATE: "अपडेट न चूकें, साप्ताहिक अलर्ट प्राप्त करें",
        SUBSCRIBE: "सब्सक्राइब",
        ENTER_YOUR_EMAIL: "ईमेल दर्ज करें",
        PLEASE_ENTER_YOUR_EMAIL: "अपना ईमेल दर्ज करें",
        PLEASE_ENTER_A_VALID_EMAIL: "वैध ईमेल दर्ज करें",
        SUCCESSFULLY_SUBSCRIBED: "सफलतापूर्वक सब्सक्राइब किया गया",
        FAILED_TO_SUBSCRIBE: "सब्सक्राइब विफल रहा",
        SHARE_ANNOUNCEMENT: "साझा करें",
        HELP_OTHERS_DISCOVER: "औरों की मदद करें",
        CHECK_OUT_THIS_AMAZING: "यह घोषणा देखें",
        SHARE_ON: "यहाँ साझा करें",
        CLICK_OPTION_TO_SHARE: "साझा करने के लिए क्लिक करें"
    },
    বাংলা: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "সকল সরকারি ঘোষণা, এক জায়গায়",
        INPUT_PLACEHOLDER: "অনুসন্ধান করুন....",
        SEARCH: "অনুসন্ধান",
        PAGE: "পৃষ্ঠা",
        OF: "এর",
        SOURCE: "উৎস দেখুন",
        NO_ANNOUNCEMENTS_FOUND: "কোনো ঘোষণা পাওয়া যায়নি",
        SEE_DETAILS: "বিস্তারিত দেখুন",
        DISCOVER_MORE: "আরও জানুন",
        INDIAN_ANNOUNCEMENTS: "ভারতীয় ঘোষণা",
        SEE_MORE: "আরও দেখুন",
        VIEW_ALL: "সব দেখুন",
        VIEW_DETAILS: "বিস্তারিত দেখুন",
        DESCRIPTION: "সরকারি ঘোষণা সংগ্রহ এবং সহজ ভাষায় অনুবাদ করে।",
        SEE_ANNOUNCEMENTS: "ঘোষণা দেখুন",
        LOAD_MORE: "আরও লোড করুন",
        SOMETHING_WENT_WRONG: "কিছু ভুল হয়েছে",
        SUBSCRIBE_TO_ALERTS: "সাবস্ক্রাইব করুন",
        NEVER_MISS_AN_UPDATE: "সাপ্তাহিক আপডেট পান",
        SUBSCRIBE: "সাবস্ক্রাইব",
        ENTER_YOUR_EMAIL: "ইমেল লিখুন",
        PLEASE_ENTER_YOUR_EMAIL: "ইমেল প্রদান করুন",
        PLEASE_ENTER_A_VALID_EMAIL: "সঠিক ইমেল লিখুন",
        SUCCESSFULLY_SUBSCRIBED: "সফলভাবে সাবস্ক্রাইব হয়েছে",
        FAILED_TO_SUBSCRIBE: "সাবস্ক্রাইব করতে ব্যর্থ",
        SHARE_ANNOUNCEMENT: "শেয়ার করুন",
        HELP_OTHERS_DISCOVER: "অন্যদের জানতে সাহায্য করুন",
        CHECK_OUT_THIS_AMAZING: "এই ঘোষণাটি দেখুন",
        SHARE_ON: "শেয়ার করুন",
        CLICK_OPTION_TO_SHARE: "শেয়ার করতে ক্লিক করুন"
    },
    தமிழ்: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "அனைத்து அரசு அறிவிப்புகளும் ஒரே இடத்தில்",
        INPUT_PLACEHOLDER: "தேடல்....",
        SEARCH: "தேடு",
        PAGE: "பக்கம்",
        OF: "இல்",
        SOURCE: "ஆதாரத்தைப் பார்க்க",
        NO_ANNOUNCEMENTS_FOUND: "அறிவிப்புகள் இல்லை",
        SEE_DETAILS: "விவரம்",
        DISCOVER_MORE: "மேலும் அறிய",
        INDIAN_ANNOUNCEMENTS: "இந்திய அறிவிப்புகள்",
        SEE_MORE: "மேலும்",
        VIEW_ALL: "அனைத்தும்",
        VIEW_DETAILS: "விவரங்கள்",
        DESCRIPTION: "அரசு அறிவிப்புகளை எளிய தமிழில் வழங்குகிறது.",
        SEE_ANNOUNCEMENTS: "அறிவிப்புகளைக் காண்க",
        LOAD_MORE: "மேலும் ஏற்றுக",
        SOMETHING_WENT_WRONG: "ஏதோ தவறு நடந்துள்ளது",
        SUBSCRIBE_TO_ALERTS: "பதிவு செய்க",
        NEVER_MISS_AN_UPDATE: "வாராந்திர செய்திகளைப் பெறுக",
        SUBSCRIBE: "பதிவு",
        ENTER_YOUR_EMAIL: "மின்னஞ்சல்",
        PLEASE_ENTER_YOUR_EMAIL: "மின்னஞ்சலை உள்ளிடவும்",
        PLEASE_ENTER_A_VALID_EMAIL: "சரியான மின்னஞ்சல்",
        SUCCESSFULLY_SUBSCRIBED: "பதிவு முடிந்தது",
        FAILED_TO_SUBSCRIBE: "பதிவு தோல்வி",
        SHARE_ANNOUNCEMENT: "பகிர்",
        HELP_OTHERS_DISCOVER: "மற்றவர்களுக்கு உதவ",
        CHECK_OUT_THIS_AMAZING: "இந்த அறிவிப்பைப் பார்",
        SHARE_ON: "பகிர்",
        CLICK_OPTION_TO_SHARE: "பகிர கிளிக் செய்க"
    },
    తెలుగు: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "అన్ని ప్రభుత్వ ప్రకటనలు ఒకే చోట",
        INPUT_PLACEHOLDER: "శోధించండి....",
        SEARCH: "వెతకండి",
        PAGE: "పేజీ",
        OF: "లో",
        SOURCE: "మూలాన్ని చూడండి",
        NO_ANNOUNCEMENTS_FOUND: "ప్రకటనలు లేవు",
        SEE_DETAILS: "వివరాలు",
        DISCOVER_MORE: "మరిన్ని",
        INDIAN_ANNOUNCEMENTS: "భారతీయ ప్రకటనలు",
        SEE_MORE: "మరింత",
        VIEW_ALL: "అన్నీ",
        VIEW_DETAILS: "వివరాలు",
        DESCRIPTION: "ప్రభుత్వ సమాచారాన్ని సులభంగా అందిస్తుంది.",
        SEE_ANNOUNCEMENTS: "ప్రకటనలు చూడండి",
        LOAD_MORE: "మరిన్ని చూపించు",
        SOMETHING_WENT_WRONG: "పొరపాటు జరిగింది",
        SUBSCRIBE_TO_ALERTS: "చందా పొందండి",
        NEVER_MISS_AN_UPDATE: "వారపు అప్‌డేట్స్ పొందండి",
        SUBSCRIBE: "సబ్‌స్క్రయిబ్",
        ENTER_YOUR_EMAIL: "ఈమెయిల్",
        PLEASE_ENTER_YOUR_EMAIL: "ఈమెయిల్ నమోదు చేయండి",
        PLEASE_ENTER_A_VALID_EMAIL: "సరైన ఈమెయిల్",
        SUCCESSFULLY_SUBSCRIBED: "చందా విజయవంతమైంది",
        FAILED_TO_SUBSCRIBE: "చందా విఫలమైంది",
        SHARE_ANNOUNCEMENT: "షేర్ చేయండి",
        HELP_OTHERS_DISCOVER: "ఇతరులకు తెలియజేయండి",
        CHECK_OUT_THIS_AMAZING: "ఈ ప్రకటన చూడండి",
        SHARE_ON: "షేర్",
        CLICK_OPTION_TO_SHARE: "షేర్ చేయడానికి క్లిక్ చేయండి"
    },
    मराठी: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "सर्व सरकारी घोषणा एकाच ठिकाणी",
        INPUT_PLACEHOLDER: "शोधा....",
        SEARCH: "शोधा",
        PAGE: "पृष्ठ",
        OF: "पैकी",
        SOURCE: "स्त्रोत पहा",
        NO_ANNOUNCEMENTS_FOUND: "घोषणा आढळली नाही",
        SEE_DETAILS: "तपशील",
        DISCOVER_MORE: "अधिक माहिती",
        INDIAN_ANNOUNCEMENTS: "भारतीय घोषणा",
        SEE_MORE: "अधिक",
        VIEW_ALL: "सर्व",
        VIEW_DETAILS: "तपशील",
        DESCRIPTION: "सरकारी घोषणांचे सोपे मराठी भाषांतर.",
        SEE_ANNOUNCEMENTS: "घोषणा पहा",
        LOAD_MORE: "आणखी पहा",
        SOMETHING_WENT_WRONG: "काहीतरी चुकले",
        SUBSCRIBE_TO_ALERTS: "सबस्क्राइब करा",
        NEVER_MISS_AN_UPDATE: "अपडेट्स मिळवण्यासाठी सबस्क्राइब करा",
        SUBSCRIBE: "सबस्क्राइब",
        ENTER_YOUR_EMAIL: "ईमेल लिहा",
        PLEASE_ENTER_YOUR_EMAIL: "ईमेल टाका",
        PLEASE_ENTER_A_VALID_EMAIL: "योग्य ईमेल टाका",
        SUCCESSFULLY_SUBSCRIBED: "यशस्वी नोंदणी",
        FAILED_TO_SUBSCRIBE: "नोंदणी अपयशी",
        SHARE_ANNOUNCEMENT: "शेअर करा",
        HELP_OTHERS_DISCOVER: "इतरांना मदत करा",
        CHECK_OUT_THIS_AMAZING: "ही घोषणा पहा",
        SHARE_ON: "शेअर करा",
        CLICK_OPTION_TO_SHARE: "नेटवर्कवर शेअर करा"
    },
    ગુજરાતી: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "બધી સરકારી જાહેરાતો એક જ જગ્યાએ",
        INPUT_PLACEHOLDER: "શોધો....",
        SEARCH: "શોધો",
        PAGE: "પૃષ્ઠ",
        OF: "નું",
        SOURCE: "સ્ત્રોત જુઓ",
        NO_ANNOUNCEMENTS_FOUND: "કોઈ જાહેરાત મળી નથી",
        SEE_DETAILS: "વિગતો",
        DISCOVER_MORE: "વધુ જાણો",
        INDIAN_ANNOUNCEMENTS: "ભારતીય જાહેરાતો",
        SEE_MORE: "વધુ",
        VIEW_ALL: "બધું જુઓ",
        VIEW_DETAILS: "વિગતો",
        DESCRIPTION: "સરકારી માહિતીનું સરળ ગુજરાતીમાં અનુવાદ.",
        SEE_ANNOUNCEMENTS: "જાહેરાતો જુઓ",
        LOAD_MORE: "વધુ લોડ કરો",
        SOMETHING_WENT_WRONG: "ભૂલ થઈ છે",
        SUBSCRIBE_TO_ALERTS: "સબસ્ક્રાઇબ કરો",
        NEVER_MISS_AN_UPDATE: "નવી અપડેટ્સ મેળવો",
        SUBSCRIBE: "સબસ્ક્રાઇબ",
        ENTER_YOUR_EMAIL: "ઈમેલ લખો",
        PLEASE_ENTER_YOUR_EMAIL: "ઈમેલ દાખલ કરો",
        PLEASE_ENTER_A_VALID_EMAIL: "સાચો ઈમેલ લખો",
        SUCCESSFULLY_SUBSCRIBED: "સફળતાપૂર્વક જોડાયા",
        FAILED_TO_SUBSCRIBE: "જોડાવામાં નિષ્ફળતા",
        SHARE_ANNOUNCEMENT: "શેર કરો",
        HELP_OTHERS_DISCOVER: "અન્યોને જણાવો",
        CHECK_OUT_THIS_AMAZING: "આ જાહેરાત જુઓ",
        SHARE_ON: "શેર",
        CLICK_OPTION_TO_SHARE: "શેર કરવા માટે ક્લિક કરો"
    },
    ಕನ್ನಡ: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "ಎಲ್ಲಾ ಸರ್ಕಾರಿ ಘೋಷಣೆಗಳು ಒಂದೆಡೆ",
        INPUT_PLACEHOLDER: "ಹುಡುಕಿ....",
        SEARCH: "ಹುಡುಕು",
        PAGE: "ಪುಟ",
        OF: "ರ",
        SOURCE: "ಮೂಲ ನೋಡಿ",
        NO_ANNOUNCEMENTS_FOUND: "ಮಾಹಿತಿ ಇಲ್ಲ",
        SEE_DETAILS: "ವಿವರಗಳು",
        DISCOVER_MORE: "ಇನ್ನಷ್ಟು",
        INDIAN_ANNOUNCEMENTS: "ಭಾರತೀಯ ಪ್ರಕಟಣೆಗಳು",
        SEE_MORE: "ಹೆಚ್ಚು",
        VIEW_ALL: "ಎಲ್ಲವೂ",
        VIEW_DETAILS: "ವಿವರಗಳು",
        DESCRIPTION: "ಸರ್ಕಾರಿ ಪ್ರಕಟಣೆಗಳ ಸರಳ ಕನ್ನಡ ಅನುವಾದ.",
        SEE_ANNOUNCEMENTS: "ಘೋಷಣೆ ನೋಡಿ",
        LOAD_MORE: "ಮತ್ತಷ್ಟು ನೋಡಿ",
        SOMETHING_WENT_WRONG: "ತಪ್ಪಾಗಿದೆ",
        SUBSCRIBE_TO_ALERTS: "ಚಂದಾದಾರರಾಗಿ",
        NEVER_MISS_AN_UPDATE: "ಅಪ್‌ಡೇಟ್ ಪಡೆಯಿರಿ",
        SUBSCRIBE: "ಚಂದಾದಾರ",
        ENTER_YOUR_EMAIL: "ಇಮೇಲ್",
        PLEASE_ENTER_YOUR_EMAIL: "ಇಮೇಲ್ ನಮೂದಿಸಿ",
        PLEASE_ENTER_A_VALID_EMAIL: "ಸರಿಯಾದ ಇಮೇಲ್",
        SUCCESSFULLY_SUBSCRIBED: "ಯಶಸ್ವಿಯಾಗಿದೆ",
        FAILED_TO_SUBSCRIBE: "ವಿಫಲವಾಗಿದೆ",
        SHARE_ANNOUNCEMENT: "ಹಂಚಿಕೊಳ್ಳಿ",
        HELP_OTHERS_DISCOVER: "ಇತರರಿಗೆ ತಿಳಿಸಿ",
        CHECK_OUT_THIS_AMAZING: "ಇದನ್ನು ನೋಡಿ",
        SHARE_ON: "ಹಂಚು",
        CLICK_OPTION_TO_SHARE: "ಹಂಚಲು ಕ್ಲಿಕ್ ಮಾಡಿ"
    },
    മലയാളം: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "എല്ലാ സർക്കാർ അറിയിപ്പുകളും ഒരിടത്ത്",
        INPUT_PLACEHOLDER: "തിരയുക....",
        SEARCH: "തിരയുക",
        PAGE: "പേജ്",
        OF: "ൽ",
        SOURCE: "ഉറവിടം",
        NO_ANNOUNCEMENTS_FOUND: "വിവരങ്ങൾ ലഭ്യമല്ല",
        SEE_DETAILS: "വിശദാംശങ്ങൾ",
        DISCOVER_MORE: "കൂടുതൽ",
        INDIAN_ANNOUNCEMENTS: "ഇന്ത്യൻ അറിയിപ്പുകൾ",
        SEE_MORE: "കൂടുതൽ",
        VIEW_ALL: "എല്ലാം",
        VIEW_DETAILS: "വിശദാംശങ്ങൾ",
        DESCRIPTION: "അറിയിപ്പുകൾ ലളിതമായ മലയാളത്തിൽ.",
        SEE_ANNOUNCEMENTS: "അറിയിപ്പുകൾ കാണുക",
        LOAD_MORE: "കൂടുതൽ കാണുക",
        SOMETHING_WENT_WRONG: "പിശക് സംഭവിച്ചു",
        SUBSCRIBE_TO_ALERTS: "സബ്‌സ്‌ക്രൈബ് ചെയ്യുക",
        NEVER_MISS_AN_UPDATE: "വാർത്തകൾ അറിയാൻ",
        SUBSCRIBE: "സബ്‌സ്‌ക്രൈബ്",
        ENTER_YOUR_EMAIL: "ഇമെയിൽ",
        PLEASE_ENTER_YOUR_EMAIL: "ഇമെയിൽ നൽകുക",
        PLEASE_ENTER_A_VALID_EMAIL: "ശരിയായ ഇമെയിൽ",
        SUCCESSFULLY_SUBSCRIBED: "വിജയകരമായി ചേർന്നു",
        FAILED_TO_SUBSCRIBE: "പരാജയപ്പെട്ടു",
        SHARE_ANNOUNCEMENT: "പങ്കിടുക",
        HELP_OTHERS_DISCOVER: "മറ്റുള്ളവരെ അറിയിക്കുക",
        CHECK_OUT_THIS_AMAZING: "ഇത് കാണുക",
        SHARE_ON: "പങ്കിടുക",
        CLICK_OPTION_TO_SHARE: "പങ്കിടാൻ ക്ലിക്ക് ചെയ്യുക"
    },
    اردو: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "تمام سرکاری اعلانات ایک جگہ",
        INPUT_PLACEHOLDER: "تلاش کریں....",
        SEARCH: "تلاش",
        PAGE: "صفحہ",
        OF: "کا",
        SOURCE: "ذریعہ دیکھیں",
        NO_ANNOUNCEMENTS_FOUND: "کوئی اعلان نہیں ملا",
        SEE_DETAILS: "تفصیلات",
        DISCOVER_MORE: "مزید",
        INDIAN_ANNOUNCEMENTS: "ہندوستانی اعلانات",
        SEE_MORE: "مزید دیکھیں",
        VIEW_ALL: "سب دیکھیں",
        VIEW_DETAILS: "تفصیلات",
        DESCRIPTION: "سرکاری اعلانات کا آسان اردو ترجمہ۔",
        SEE_ANNOUNCEMENTS: "اعلانات دیکھیں",
        LOAD_MORE: "مزید لوڈ کریں",
        SOMETHING_WENT_WRONG: "خرابی ہوئی",
        SUBSCRIBE_TO_ALERTS: "سبسکرائب کریں",
        NEVER_MISS_AN_UPDATE: "اپ ڈیٹ حاصل کریں",
        SUBSCRIBE: "سبسکرائب",
        ENTER_YOUR_EMAIL: "ای میل درج کریں",
        PLEASE_ENTER_YOUR_EMAIL: "ای میل لکھیں",
        PLEASE_ENTER_A_VALID_EMAIL: "درست ای میل",
        SUCCESSFULLY_SUBSCRIBED: "کامیابی سے شامل ہوئے",
        FAILED_TO_SUBSCRIBE: "ناکامی ہوئی",
        SHARE_ANNOUNCEMENT: "شیئر کریں",
        HELP_OTHERS_DISCOVER: "دوسروں کو بتائیں",
        CHECK_OUT_THIS_AMAZING: "یہ اعلان دیکھیں",
        SHARE_ON: "شیئر",
        CLICK_OPTION_TO_SHARE: "شیئر کرنے کے لیے کلک کریں"
    },
    অসমীয়া: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "সকলো চৰকাৰী ঘোষণা একেলগে",
        INPUT_PLACEHOLDER: "সন্ধান কৰক....",
        SEARCH: "সন্ধান",
        PAGE: "পৃষ্ঠা",
        OF: "ৰ",
        SOURCE: "উৎস চাওক",
        NO_ANNOUNCEMENTS_FOUND: "কোনো ঘোষণা নাই",
        SEE_DETAILS: "বিৱৰণ",
        DISCOVER_MORE: "অধিক জানক",
        INDIAN_ANNOUNCEMENTS: "ভাৰতীয় ঘোষণা",
        SEE_MORE: "অধিক",
        VIEW_ALL: "সকলো",
        VIEW_DETAILS: "বিৱৰণ",
        DESCRIPTION: "চৰকাৰী তথ্য সহজ অসমীয়াত।",
        SEE_ANNOUNCEMENTS: "ঘোষণা চাওক",
        LOAD_MORE: "অধিক চাওক",
        SOMETHING_WENT_WRONG: "ভুল হৈছে",
        SUBSCRIBE_TO_ALERTS: "চাবস্ক্ৰাইব কৰক",
        NEVER_MISS_AN_UPDATE: "আপডেট লাভ কৰক",
        SUBSCRIBE: "চাবস্ক্ৰাইব",
        ENTER_YOUR_EMAIL: "ইমেইল",
        PLEASE_ENTER_YOUR_EMAIL: "ইমেইল দিয়ক",
        PLEASE_ENTER_A_VALID_EMAIL: "সঠিক ইমেইল",
        SUCCESSFULLY_SUBSCRIBED: "সফল চাবস্ক্ৰিপচন",
        FAILED_TO_SUBSCRIBE: "বিফল হৈছে",
        SHARE_ANNOUNCEMENT: "শ্বেয়াৰ কৰক",
        HELP_OTHERS_DISCOVER: "আনক জানিবলৈ দিয়ক",
        CHECK_OUT_THIS_AMAZING: "এইটো চাওক",
        SHARE_ON: "শ্বেয়াৰ",
        CLICK_OPTION_TO_SHARE: "শ্বেয়াৰৰ বাবে ক্লিক কৰক"
    },
    "बरʼ": {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "गासै सरकारी थोंनाय खौ जायगाआव",
        INPUT_PLACEHOLDER: "नाय....",
        SEARCH: "नाय",
        PAGE: "बिलाइ",
        OF: "नि",
        SOURCE: "मुलसो नाय",
        NO_ANNOUNCEMENTS_FOUND: "मोनाखै",
        SEE_DETAILS: "नाय",
        DISCOVER_MORE: "गोबां",
        INDIAN_ANNOUNCEMENTS: "भारतीय थोंनाय",
        SEE_MORE: "नाय",
        VIEW_ALL: "गासै",
        VIEW_DETAILS: "गेलेबाव",
        DESCRIPTION: "सरकारी थोंनायफोरखौ बुझिनो हागौ सोलोंनाय।",
        SEE_ANNOUNCEMENTS: "थोंनाय नाय",
        LOAD_MORE: "गोबां नाय",
        SOMETHING_WENT_WRONG: "जायाखै",
        SUBSCRIBE_TO_ALERTS: "सबस्क्राइब",
        NEVER_MISS_AN_UPDATE: "अपडेट मोन",
        SUBSCRIBE: "सबस्क्राइब",
        ENTER_YOUR_EMAIL: "ईमेल",
        PLEASE_ENTER_YOUR_EMAIL: "ईमेल लिर",
        PLEASE_ENTER_A_VALID_EMAIL: "मोजां ईमेल",
        SUCCESSFULLY_SUBSCRIBED: "जाबाय",
        FAILED_TO_SUBSCRIBE: "जायाखै",
        SHARE_ANNOUNCEMENT: "शेयर खालाम",
        HELP_OTHERS_DISCOVER: "मदद खालाम",
        CHECK_OUT_THIS_AMAZING: "नाय",
        SHARE_ON: "शेयर",
        CLICK_OPTION_TO_SHARE: "क्लिक खालाम"
    },
    डोगरी: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "सारे सरकारी ऐलान इक्की जगह",
        INPUT_PLACEHOLDER: "तलाश करो....",
        SEARCH: "तलाश",
        PAGE: "पन्ना",
        OF: "दा",
        SOURCE: "स्रोत दिक्खो",
        NO_ANNOUNCEMENTS_FOUND: "नेईं मिल्ले",
        SEE_DETAILS: "ब्यौरा",
        DISCOVER_MORE: "होर",
        INDIAN_ANNOUNCEMENTS: "भारतीय ऐलान",
        SEE_MORE: "होर",
        VIEW_ALL: "सारे",
        VIEW_DETAILS: "ब्यौरा",
        DESCRIPTION: "सरकारी ऐलानें दा डोगरी अनुवाद।",
        SEE_ANNOUNCEMENTS: "ऐलान दिक्खो",
        LOAD_MORE: "होर दिक्खो",
        SOMETHING_WENT_WRONG: "गलत होया",
        SUBSCRIBE_TO_ALERTS: "सबस्क्राइब करो",
        NEVER_MISS_AN_UPDATE: "अपडेट मिलदे रहन",
        SUBSCRIBE: "सबस्क्राइब",
        ENTER_YOUR_EMAIL: "ईमेल",
        PLEASE_ENTER_YOUR_EMAIL: "ईमेल लिखो",
        PLEASE_ENTER_A_VALID_EMAIL: "सही ईमेल",
        SUCCESSFULLY_SUBSCRIBED: "कामयाब",
        FAILED_TO_SUBSCRIBE: "नाकाम",
        SHARE_ANNOUNCEMENT: "साझा करो",
        HELP_OTHERS_DISCOVER: "मदद करो",
        CHECK_OUT_THIS_AMAZING: "ऐलान दिक्खो",
        SHARE_ON: "साझा",
        CLICK_OPTION_TO_SHARE: "क्लिक करो"
    },
    कॉशुर: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "تمام سرکاری اعلان اکہ جاے",
        INPUT_PLACEHOLDER: "تلاش....",
        SEARCH: "تلاش",
        PAGE: "صفحہ",
        OF: "چھ",
        SOURCE: "وچھو",
        NO_ANNOUNCEMENTS_FOUND: "نہ ملیو",
        SEE_DETAILS: "تفصیل",
        DISCOVER_MORE: "مزید",
        INDIAN_ANNOUNCEMENTS: "ہندوستانی اعلان",
        SEE_MORE: "مزید",
        VIEW_ALL: "سارے",
        VIEW_DETAILS: "تفصیل",
        DESCRIPTION: "سرکاری اعلانن ہند کاشُر ترجمہ۔",
        SEE_ANNOUNCEMENTS: "اعلان وچھو",
        LOAD_MORE: "مزید وچھو",
        SOMETHING_WENT_WRONG: "غلط گژھ",
        SUBSCRIBE_TO_ALERTS: "سبسکرائب",
        NEVER_MISS_AN_UPDATE: "اپ ڈیٹ وچھو",
        SUBSCRIBE: "سبسکرائب",
        ENTER_YOUR_EMAIL: "ای میل",
        PLEASE_ENTER_YOUR_EMAIL: "ای میل لکھو",
        PLEASE_ENTER_A_VALID_EMAIL: "صحیح ای میل",
        SUCCESSFULLY_SUBSCRIBED: "کامیاب",
        FAILED_TO_SUBSCRIBE: "ناکام",
        SHARE_ANNOUNCEMENT: "شیئر",
        HELP_OTHERS_DISCOVER: "مدد کرو",
        CHECK_OUT_THIS_AMAZING: "اعلان وچھو",
        SHARE_ON: "شیئر",
        CLICK_OPTION_TO_SHARE: "کلک کرو"
    },
    मैथिली: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "सब सरकारी घोषणा एके ठाम",
        INPUT_PLACEHOLDER: "खोजू....",
        SEARCH: "खोजू",
        PAGE: "पृष्ठ",
        OF: "क",
        SOURCE: "देखू",
        NO_ANNOUNCEMENTS_FOUND: "नहि भेटल",
        SEE_DETAILS: "विवरण",
        DISCOVER_MORE: "आओर",
        INDIAN_ANNOUNCEMENTS: "भारतीय घोषणा",
        SEE_MORE: "देखू",
        VIEW_ALL: "सब",
        VIEW_DETAILS: "विवरण",
        DESCRIPTION: "सरकारी घोषणाक मैथिली अनुवाद।",
        SEE_ANNOUNCEMENTS: "घोषणा देखू",
        LOAD_MORE: "आओर देखू",
        SOMETHING_WENT_WRONG: "गलत भेल",
        SUBSCRIBE_TO_ALERTS: "सबस्क्राइब",
        NEVER_MISS_AN_UPDATE: "अपडेट पाबू",
        SUBSCRIBE: "सबस्क्राइब",
        ENTER_YOUR_EMAIL: "ईमेल",
        PLEASE_ENTER_YOUR_EMAIL: "ईमेल लिखू",
        PLEASE_ENTER_A_VALID_EMAIL: "सही ईमेल",
        SUCCESSFULLY_SUBSCRIBED: "सफल",
        FAILED_TO_SUBSCRIBE: "विफल",
        SHARE_ANNOUNCEMENT: "साझा",
        HELP_OTHERS_DISCOVER: "मदद करू",
        CHECK_OUT_THIS_AMAZING: "घोषणा देखू",
        SHARE_ON: "साझा",
        CLICK_OPTION_TO_SHARE: "क्लिक करू"
    },
    मৈতৈলোন: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "সরকারগী ৱাফম পুম্নমক্ অমত্তা মফম",
        INPUT_PLACEHOLDER: "থিবা....",
        SEARCH: "থিবা",
        PAGE: "লমাই",
        OF: "গী",
        SOURCE: "উবা",
        NO_ANNOUNCEMENTS_FOUND: "ফংদ্রে",
        SEE_DETAILS: "উবা",
        DISCOVER_MORE: "থিবা",
        INDIAN_ANNOUNCEMENTS: "ভারতকী ৱাফম",
        SEE_MORE: "উবা",
        VIEW_ALL: "পুম্নমক্",
        VIEW_DETAILS: "উবা",
        DESCRIPTION: "সরকারগী ৱাফম মৈতৈলোনদা।",
        SEE_ANNOUNCEMENTS: "ৱাফম উবা",
        LOAD_MORE: "মখা উবা",
        SOMETHING_WENT_WRONG: "অসোয়বা",
        SUBSCRIBE_TO_ALERTS: "সবস্ক্রাইব",
        NEVER_MISS_AN_UPDATE: "পাউ ফংবা",
        SUBSCRIBE: "সবস্ক্রাইব",
        ENTER_YOUR_EMAIL: "ইমেইল",
        PLEASE_ENTER_YOUR_EMAIL: "ইমেইল পীবীরকউ",
        PLEASE_ENTER_A_VALID_EMAIL: "অচুম্বা ইমেইল",
        SUCCESSFULLY_SUBSCRIBED: "মায় পাক্লে",
        FAILED_TO_SUBSCRIBE: "মায় পাকদ্রে",
        SHARE_ANNOUNCEMENT: "শেয়ার",
        HELP_OTHERS_DISCOVER: "মতেং",
        CHECK_OUT_THIS_AMAZING: "ৱাফম উবা",
        SHARE_ON: "শেয়ার",
        CLICK_OPTION_TO_SHARE: "ক্লিক তৌবীয়ু"
    },
    नेपाली: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "सबै सरकारी घोषणाहरू एउटै ठाउँमा",
        INPUT_PLACEHOLDER: "खोज्नुहोस्....",
        SEARCH: "खोज",
        PAGE: "पृष्ठ",
        OF: "को",
        SOURCE: "स्रोत हेर्नुहोस्",
        NO_ANNOUNCEMENTS_FOUND: "फेला परेन",
        SEE_DETAILS: "विवरण",
        DISCOVER_MORE: "थप",
        INDIAN_ANNOUNCEMENTS: "भारतीय घोषणाहरू",
        SEE_MORE: "थप",
        VIEW_ALL: "सबै",
        VIEW_DETAILS: "विवरण",
        DESCRIPTION: "सरकारी सूचनाको नेपाली अनुवाद।",
        SEE_ANNOUNCEMENTS: "घोषणाहरू हेर्नुहोस्",
        LOAD_MORE: "थप हेर्नुहोस्",
        SOMETHING_WENT_WRONG: "गलत भयो",
        SUBSCRIBE_TO_ALERTS: "सबस्क्राइब",
        NEVER_MISS_AN_UPDATE: "जानकारी पाउनुहोस्",
        SUBSCRIBE: "सबस्क्राइब",
        ENTER_YOUR_EMAIL: "ईमेल",
        PLEASE_ENTER_YOUR_EMAIL: "ईमेल लेख्नुहोस्",
        PLEASE_ENTER_A_VALID_EMAIL: "सही ईमेल",
        SUCCESSFULLY_SUBSCRIBED: "सफल",
        FAILED_TO_SUBSCRIBE: "असफल",
        SHARE_ANNOUNCEMENT: "साझा",
        HELP_OTHERS_DISCOVER: "मदत",
        CHECK_OUT_THIS_AMAZING: "सूचना हेर्नुहोस्",
        SHARE_ON: "साझा",
        CLICK_OPTION_TO_SHARE: "क्लिक गर्नुहोस्"
    },
    ଓଡ଼ିଆ: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "ସମସ୍ତ ସରକାରୀ ଘୋଷଣା ଏକ ସ୍ଥାନରେ",
        INPUT_PLACEHOLDER: "ଖୋଜନ୍ତୁ....",
        SEARCH: "ଖୋଜ",
        PAGE: "ପୃଷ୍ଠା",
        OF: "ର",
        SOURCE: "ଉତ୍ସ ଦେଖନ୍ତୁ",
        NO_ANNOUNCEMENTS_FOUND: "ମିଳିଲା ନାହିଁ",
        SEE_DETAILS: "ବିବରଣୀ",
        DISCOVER_MORE: "ଅଧିକ",
        INDIAN_ANNOUNCEMENTS: "ଭାରତୀୟ ଘୋଷଣା",
        SEE_MORE: "ଅଧିକ",
        VIEW_ALL: "ସବୁ",
        VIEW_DETAILS: "ବିବରଣୀ",
        DESCRIPTION: "ସରକାରୀ ଘୋଷଣାର ଓଡ଼ିଆ ଅନୁବାଦ।",
        SEE_ANNOUNCEMENTS: "ଘୋଷଣା ଦେଖନ୍ତୁ",
        LOAD_MORE: "ଅଧିକ ଦେଖନ୍ତୁ",
        SOMETHING_WENT_WRONG: "ଭୁଲ ହୋଇଛି",
        SUBSCRIBE_TO_ALERTS: "ସବସ୍କ୍ରାଇବ",
        NEVER_MISS_AN_UPDATE: "ଅପଡେଟ ପାଆନ୍ତୁ",
        SUBSCRIBE: "ସବସ୍କ୍ରାଇବ",
        ENTER_YOUR_EMAIL: "ଇମେଲ",
        PLEASE_ENTER_YOUR_EMAIL: "ଇମେଲ ଦିଅନ୍ତୁ",
        PLEASE_ENTER_A_VALID_EMAIL: "ସଠିକ ଇମେଲ",
        SUCCESSFULLY_SUBSCRIBED: "ସଫଳ",
        FAILED_TO_SUBSCRIBE: "ବିଫଳ",
        SHARE_ANNOUNCEMENT: "ଶେୟାର",
        HELP_OTHERS_DISCOVER: "ସାହାଯ୍ୟ",
        CHECK_OUT_THIS_AMAZING: "ଘୋଷଣା ଦେଖନ୍ତୁ",
        SHARE_ON: "ଶେୟାର",
        CLICK_OPTION_TO_SHARE: "କ୍ଲିକ କରନ୍ତୁ"
    },
    ਪੰਜਾਬੀ: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "ਸਾਰੀਆਂ ਸਰਕਾਰੀ ਘੋਸ਼ਣਾਵਾਂ ਇੱਕ ਥਾਂ 'ਤੇ",
        INPUT_PLACEHOLDER: "ਖੋਜੋ....",
        SEARCH: "ਖੋਜ",
        PAGE: "ਪੰਨਾ",
        OF: "ਦਾ",
        SOURCE: "ਸਰੋਤ ਦੇਖੋ",
        NO_ANNOUNCEMENTS_FOUND: "ਨਹੀਂ ਮਿਲੀ",
        SEE_DETAILS: "ਵੇਰਵੇ",
        DISCOVER_MORE: "ਹੋਰ",
        INDIAN_ANNOUNCEMENTS: "ਭਾਰਤੀ ਘੋਸ਼ਣਾਵਾਂ",
        SEE_MORE: "ਹੋਰ",
        VIEW_ALL: "ਸਾਰੇ",
        VIEW_DETAILS: "ਵੇਰਵੇ",
        DESCRIPTION: "ਸਰਕਾਰੀ ਘੋਸ਼ਣਾਵਾਂ ਦਾ ਪੰਜਾਬੀ ਅਨੁਵਾਦ।",
        SEE_ANNOUNCEMENTS: "ਘੋਸ਼ਣਾਵਾਂ ਦੇਖੋ",
        LOAD_MORE: "ਹੋਰ ਦੇਖੋ",
        SOMETHING_WENT_WRONG: "ਗਲਤੀ ਹੋਈ",
        SUBSCRIBE_TO_ALERTS: "ਸਬਸਕ੍ਰਾਈਬ",
        NEVER_MISS_AN_UPDATE: "ਅਪਡੇਟ ਪ੍ਰਾਪਤ ਕਰੋ",
        SUBSCRIBE: "ਸਬਸਕ੍ਰਾਈਬ",
        ENTER_YOUR_EMAIL: "ਈਮੇਲ",
        PLEASE_ENTER_YOUR_EMAIL: "ਈਮੇਲ ਲਿਖੋ",
        PLEASE_ENTER_A_VALID_EMAIL: "ਸਹੀ ਈਮੇਲ",
        SUCCESSFULLY_SUBSCRIBED: "ਸਫਲ",
        FAILED_TO_SUBSCRIBE: "ਅਸਫਲ",
        SHARE_ANNOUNCEMENT: "ਸਾਂਝਾ ਕਰੋ",
        HELP_OTHERS_DISCOVER: "ਮਦਦ",
        CHECK_OUT_THIS_AMAZING: "ਘੋਸ਼ਣਾ ਦੇਖੋ",
        SHARE_ON: "ਸਾਂਝਾ",
        CLICK_OPTION_TO_SHARE: "ਕਲਿੱਕ ਕਰੋ"
    },
    "संस्कृतम्": {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "सर्वे सरकारीयाः घोषणाः एकस्मिन् स्थाने",
        INPUT_PLACEHOLDER: "अन्वेषणं करोतु....",
        SEARCH: "अन्वेषणम्",
        PAGE: "पृष्ठम्",
        OF: "तः",
        SOURCE: "स्रोतं पश्यतु",
        NO_ANNOUNCEMENTS_FOUND: "न प्राप्ता",
        SEE_DETAILS: "विवरणम्",
        DISCOVER_MORE: "अधिकम्",
        INDIAN_ANNOUNCEMENTS: "भारतीयाः घोषणाः",
        SEE_MORE: "अधिकम्",
        VIEW_ALL: "सर्वम्",
        VIEW_DETAILS: "विवरणम्",
        DESCRIPTION: "सरकारीयघोषणानां संस्कृतम् अनुवादम्।",
        SEE_ANNOUNCEMENTS: "घोषणाः पश्यतु",
        LOAD_MORE: "अधिकं पश्यतु",
        SOMETHING_WENT_WRONG: "दोषः जातः",
        SUBSCRIBE_TO_ALERTS: "सदस्यता",
        NEVER_MISS_AN_UPDATE: "सूचनां प्राप्नोतु",
        SUBSCRIBE: "सदस्यता",
        ENTER_YOUR_EMAIL: "ईमेल",
        PLEASE_ENTER_YOUR_EMAIL: "ईमेल लिखतु",
        PLEASE_ENTER_A_VALID_EMAIL: "समीचीनं ईमेल",
        SUCCESSFULLY_SUBSCRIBED: "सफल",
        FAILED_TO_SUBSCRIBE: "विफल",
        SHARE_ANNOUNCEMENT: "साझा",
        HELP_OTHERS_DISCOVER: "साहाय्यम्",
        CHECK_OUT_THIS_AMAZING: "घोषणां पश्यतु",
        SHARE_ON: "साझा",
        CLICK_OPTION_TO_SHARE: "नुदतु"
    },
    "ᱥᱟᱱᱛᱟᱲᱤ": {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "ᱡᱷᱚᱛᱚ ᱥᱚᱨᱠᱟᱨᱤ ᱮᱱᱟᱶᱱᱥᱢᱮᱱᱴ ᱢᱤᱫ ᱡᱟᱭᱜᱟ ᱨᱮ",
        INPUT_PLACEHOLDER: "ᱥᱮᱸᱫᱽᱨᱟᱭ ᱢᱮ....",
        SEARCH: "ᱥᱮᱸᱫᱽᱨᱟ",
        PAGE: "ᱥᱟᱦᱴᱟ",
        OF: "ᱨᱮᱭᱟᱜ",
        SOURCE: "ᱧᱮᱞ ᱢᱮ",
        NO_ANNOUNCEMENTS_FOUND: "ᱵᱟᱝ ᱧᱟᱢ ᱞᱮᱱᱟ",
        SEE_DETAILS: "ᱵᱤᱵᱨᱚᱬ",
        DISCOVER_MORE: "ᱰᱷᱮᱨ",
        INDIAN_ANNOUNCEMENTS: "ᱵᱷᱟᱨᱚᱛᱤᱭᱟᱹ ᱮᱱᱟᱶᱱᱥᱢᱮᱱᱴ",
        SEE_MORE: "ᱰᱷᱮᱨ",
        VIEW_ALL: "ᱡᱷᱚᱛᱚ",
        VIEW_DETAILS: "ᱵᱤᱵᱨᱚᱬ",
        DESCRIPTION: "ᱥᱚᱨᱠᱟᱨᱤ ᱮᱱᱟᱶᱱᱥᱢᱮᱱᱴ ᱥᱟᱱᱛᱟᱲᱤ ᱛᱮ ᱾",
        SEE_ANNOUNCEMENTS: "ᱧᱮᱞ ᱢᱮ",
        LOAD_MORE: "ᱰᱷᱮᱨ ᱧᱮᱞ ᱢᱮ",
        SOMETHING_WENT_WRONG: "ᱵᱟᱹᱲᱤᱡ ᱮᱱᱟ",
        SUBSCRIBE_TO_ALERTS: "ᱥᱟᱵᱽᱥᱠᱨᱟᱭᱤᱵᱽ",
        NEVER_MISS_AN_UPDATE: "ᱟᱯᱰᱮᱴ ᱧᱟᱢ ᱢᱮ",
        SUBSCRIBE: "ᱥᱟᱵᱽᱥᱠᱨᱟᱭᱤᱵᱽ",
        ENTER_YOUR_EMAIL: "ᱤᱢᱮᱞ",
        PLEASE_ENTER_YOUR_EMAIL: "ᱤᱢᱮᱞ ᱚᱞ ᱢᱮ",
        PLEASE_ENTER_A_VALID_EMAIL: "ᱥᱟᱹᱨᱤ ᱤᱢᱮᱞ",
        SUCCESSFULLY_SUBSCRIBED: "ᱦᱩᱭ ᱮᱱᱟ",
        FAILED_TO_SUBSCRIBE: "ᱵᱟᱝ ᱦᱩᱭ ᱞᱮᱱᱟ",
        SHARE_ANNOUNCEMENT: "ᱦᱟᱹᱴᱤᱧ",
        HELP_OTHERS_DISCOVER: "ᱜᱚᱲᱚ",
        CHECK_OUT_THIS_AMAZING: "ᱧᱮᱞ ᱢᱮ",
        SHARE_ON: "ᱦᱟᱹᱴᱤᱧ",
        CLICK_OPTION_TO_SHARE: "ᱠᱞᱤᱠ ᱢᱮ"
    },
    سنڌي: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "سڀ سرڪاري اعلان هڪ جاءِ تي",
        INPUT_PLACEHOLDER: "ڳوليو....",
        SEARCH: "ڳولا",
        PAGE: "صفحو",
        OF: "جو",
        SOURCE: "ذريعو ڏسو",
        NO_ANNOUNCEMENTS_FOUND: "اعلان نه مليو",
        SEE_DETAILS: "تفصيل",
        DISCOVER_MORE: "وڌيڪ",
        INDIAN_ANNOUNCEMENTS: "هندستاني اعلان",
        SEE_MORE: "وڌيڪ",
        VIEW_ALL: "سڀ",
        VIEW_DETAILS: "تفصيل",
        DESCRIPTION: "سرڪاري اعلانن جو سنڌي ترجمو.",
        SEE_ANNOUNCEMENTS: "اعلان ڏسو",
        LOAD_MORE: "وڌيڪ ڏسو",
        SOMETHING_WENT_WRONG: "غلطي ٿي",
        SUBSCRIBE_TO_ALERTS: "سبسڪرائب",
        NEVER_MISS_AN_UPDATE: "اپڊيٽ حاصل ڪريو",
        SUBSCRIBE: "سبسڪرائب",
        ENTER_YOUR_EMAIL: "اي ميل",
        PLEASE_ENTER_YOUR_EMAIL: "اي ميل لکو",
        PLEASE_ENTER_A_VALID_EMAIL: "صحيح اي ميل",
        SUCCESSFULLY_SUBSCRIBED: "ڪامياب",
        FAILED_TO_SUBSCRIBE: "ناڪام",
        SHARE_ANNOUNCEMENT: "شئر",
        HELP_OTHERS_DISCOVER: "مدد",
        CHECK_OUT_THIS_AMAZING: "اعلان ڏسو",
        SHARE_ON: "شئر",
        CLICK_OPTION_TO_SHARE: "ڪلڪ ڪريو"
    }
};