export type TranslationKeys = {
    ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: string;
    INPUT_PLACEHOLDER: string;
    SEARCH: string;
    PAGE: string;
    OF: string;
    SOURCE: string;
    NO_ANNOUNCEMENTS_FOUND: string;
    SEE_DETAILS: string;
    DISCOVER_MORE: string;
    INDIAN_ANNOUNCEMENTS: string;
    SEE_MORE: string;
    VIEW_ALL: string;
    VIEW_DETAILS: string;
    DESCRIPTION: string;
    SEE_ANNOUNCEMENTS: string;
    LOAD_MORE: string;
    SOMETHING_WENT_WRONG: string;
    SUBSCRIBE_TO_ALERTS: string;
    NEVER_MISS_AN_UPDATE: string;
    SUBSCRIBE: string;
    ENTER_YOUR_EMAIL: string;
    PLEASE_ENTER_YOUR_EMAIL: string;
    PLEASE_ENTER_A_VALID_EMAIL: string;
    SUCCESSFULLY_SUBSCRIBED: string;
    FAILED_TO_SUBSCRIBE: string;
    SHARE_ANNOUNCEMENT: string;
    HELP_OTHERS_DISCOVER: string;
    CHECK_OUT_THIS_AMAZING: string;
    SHARE_ON: string;
    CLICK_OPTION_TO_SHARE: string;
    TITLE?: string;
};

export const TranslateText: Record<string, TranslationKeys> = {
    English: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "Access All Official Government Announcements in One Unified Portal",
        INPUT_PLACEHOLDER: "Search by keyword, department, or announcement title...",
        SEARCH: "Search Now",
        PAGE: "Current Page",
        OF: "of",
        SOURCE: "View Original Official Source Document",
        NO_ANNOUNCEMENTS_FOUND: "We couldn't find any announcements matching your current search criteria.",
        SEE_DETAILS: "View Full Details",
        DISCOVER_MORE: "Discover More Insights",
        INDIAN_ANNOUNCEMENTS: "Official Indian Government Announcements",
        SEE_MORE: "See More Updates",
        VIEW_ALL: "View All Notifications",
        VIEW_DETAILS: "Detailed Information",
        DESCRIPTION: "reaks down complex government circulars into simple language. Access announcements from all ministries in your preferred language—text or audio. No bureaucratic jargon, just clarity.",
        SEE_ANNOUNCEMENTS: "Browse All Announcements",
        LOAD_MORE: "LOAD MORE UPDATES",
        SOMETHING_WENT_WRONG: "An unexpected error occurred while fetching the data. Please try again later.",
        SUBSCRIBE_TO_ALERTS: "Subscribe to Real-time Notifications",
        NEVER_MISS_AN_UPDATE: "Stay informed with the latest policy changes and news. Get curated weekly alerts directly in your inbox.",
        SUBSCRIBE: "Subscribe Now",
        ENTER_YOUR_EMAIL: "Enter your primary email address",
        PLEASE_ENTER_YOUR_EMAIL: "Please provide a valid email address to proceed.",
        PLEASE_ENTER_A_VALID_EMAIL: "The email format is incorrect. Please check and try again.",
        SUCCESSFULLY_SUBSCRIBED: "You have successfully subscribed to our weekly newsletter.",
        FAILED_TO_SUBSCRIBE: "We encountered a problem during your subscription. Please check your connection.",
        SHARE_ANNOUNCEMENT: "Share this Important Announcement",
        HELP_OTHERS_DISCOVER: "Spread the word and help your community stay updated with official government news.",
        CHECK_OUT_THIS_AMAZING: "I thought you might find this official government announcement useful:",
        SHARE_ON: "Share via",
        CLICK_OPTION_TO_SHARE: "Choose an option above to share this information with your professional network.",
        TITLE: "Complex Government Circulars Made Simple for All Indians"
    },
    हिन्दी: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "सभी आधिकारिक सरकारी घोषणाएँ अब एक ही पोर्टल पर उपलब्ध",
        INPUT_PLACEHOLDER: "कीवर्ड, विभाग या घोषणा के शीर्षक से खोजें...",
        SEARCH: "अभी खोजें",
        PAGE: "वर्तमान पृष्ठ",
        OF: "कुल",
        SOURCE: "आधिकारिक स्रोत दस्तावेज़ देखें",
        NO_ANNOUNCEMENTS_FOUND: "आपके खोज मापदंडों के अनुसार कोई घोषणा नहीं मिली।",
        SEE_DETAILS: "पूर्ण विवरण देखें",
        DISCOVER_MORE: "अधिक जानकारी प्राप्त करें",
        INDIAN_ANNOUNCEMENTS: "आधिकारिक भारतीय सरकारी घोषणाएँ",
        SEE_MORE: "और अपडेट देखें",
        VIEW_ALL: "सभी सूचनाएं देखें",
        VIEW_DETAILS: "विस्तृत जानकारी",
        DESCRIPTION: "हमारा प्लेटफ़ॉर्म सभी भारतीय राज्यों और केंद्रीय विभागों से सरकारी सूचनाओं को समझदारी से एकत्रित करता है और बेहतर पहुँच के लिए उन्हें आपकी स्थानीय भाषा में अनुवादित करता है।",
        SEE_ANNOUNCEMENTS: "सभी घोषणाएं ब्राउज़ करें",
        LOAD_MORE: "और अपडेट लोड करें",
        SOMETHING_WENT_WRONG: "डेटा प्राप्त करते समय एक अप्रत्याशित त्रुटि हुई। कृपया बाद में पुनः प्रयास करें।",
        SUBSCRIBE_TO_ALERTS: "रीयल-टाइम सूचनाओं के लिए सब्सक्राइब करें",
        NEVER_MISS_AN_UPDATE: "नवीनतम नीतिगत परिवर्तनों से अवगत रहें। सीधे अपने इनबॉक्स में साप्ताहिक अलर्ट प्राप्त करें।",
        SUBSCRIBE: "अभी सब्सक्राइब करें",
        ENTER_YOUR_EMAIL: "अपना ईमेल पता दर्ज करें",
        PLEASE_ENTER_YOUR_EMAIL: "जारी रखने के लिए कृपया एक वैध ईमेल पता प्रदान करें।",
        PLEASE_ENTER_A_VALID_EMAIL: "ईमेल प्रारूप गलत है। कृपया जाँचें और पुनः प्रयास करें।",
        SUCCESSFULLY_SUBSCRIBED: "आप हमारी साप्ताहिक न्यूज़लेटर के लिए सफलतापूर्वक सब्सक्राइब हो गए हैं।",
        FAILED_TO_SUBSCRIBE: "आपकी सदस्यता के दौरान हमें एक समस्या का सामना करना पड़ा।",
        SHARE_ANNOUNCEMENT: "यह महत्वपूर्ण घोषणा साझा करें",
        HELP_OTHERS_DISCOVER: "खबर फैलाएं और अपने समुदाय को आधिकारिक सरकारी समाचारों के साथ अपडेट रहने में मदद करें।",
        CHECK_OUT_THIS_AMAZING: "मुझे लगा कि आपको यह सरकारी घोषणा उपयोगी लग सकती है:",
        SHARE_ON: "के माध्यम से साझा करें",
        CLICK_OPTION_TO_SHARE: "अपने नेटवर्क के साथ साझा करने के लिए ऊपर एक विकल्प चुनें।"
    },
    বাংলা: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "সমস্ত সরকারি ঘোষণা এখন একটি সমন্বিত পোর্টালে",
        INPUT_PLACEHOLDER: "কীওয়ার্ড, বিভাগ বা শিরোনাম দিয়ে অনুসন্ধান করুন...",
        SEARCH: "অনুসন্ধান করুন",
        PAGE: "বর্তমান পৃষ্ঠা",
        OF: "এর মধ্যে",
        SOURCE: "অফিসিয়াল উৎস নথি দেখুন",
        NO_ANNOUNCEMENTS_FOUND: "আপনার অনুসন্ধানের সাথে মেলে এমন কোনো ঘোষণা পাওয়া যায়নি।",
        SEE_DETAILS: "বিস্তারিত তথ্য দেখুন",
        DISCOVER_MORE: "আরও অন্তর্দৃষ্টি আবিষ্কার করুন",
        INDIAN_ANNOUNCEMENTS: "অফিসিয়াল ভারতীয় সরকারি ঘোষণা",
        SEE_MORE: "আরও আপডেট দেখুন",
        VIEW_ALL: "সমস্ত বিজ্ঞপ্তি দেখুন",
        VIEW_DETAILS: "বিস্তারিত তথ্য",
        DESCRIPTION: "আমাদের প্ল্যাটফর্ম ভারতের সমস্ত রাজ্য এবং কেন্দ্রীয় বিভাগ থেকে সরকারি বিজ্ঞপ্তিগুলি সংগ্রহ করে এবং আপনার পছন্দের ভাষায় অনুবাদ করে সহজলভ্য করে তোলে।",
        SEE_ANNOUNCEMENTS: "সমস্ত ঘোষণা ব্রাউজ করুন",
        LOAD_MORE: "আরও আপডেট লোড করুন",
        SOMETHING_WENT_WRONG: "ডেটা লোড করার সময় একটি ত্রুটি ঘটেছে। অনুগ্রহ করে পরে চেষ্টা করুন।",
        SUBSCRIBE_TO_ALERTS: "রিয়েল-টাইম অ্যালার্টের জন্য সাবস্ক্রাইব করুন",
        NEVER_MISS_AN_UPDATE: "সর্বশেষ নীতি পরিবর্তন সম্পর্কে অবগত থাকুন। সরাসরি আপনার ইনবক্সে সাপ্তাহিক আপডেট পান।",
        SUBSCRIBE: "এখনই সাবস্ক্রাইব করুন",
        ENTER_YOUR_EMAIL: "আপনার ইমেল ঠিকানা লিখুন",
        PLEASE_ENTER_YOUR_EMAIL: "এগিয়ে যাওয়ার জন্য একটি সঠিক ইমেল দিন।",
        PLEASE_ENTER_A_VALID_EMAIL: "ইমেল ফর্ম্যাটটি ভুল। অনুগ্রহ করে পরীক্ষা করে আবার চেষ্টা করুন।",
        SUCCESSFULLY_SUBSCRIBED: "আপনি সফলভাবে আমাদের নিউজলেটারে সাবস্ক্রাইব করেছেন।",
        FAILED_TO_SUBSCRIBE: "সাবস্ক্রাইব করার সময় সমস্যা হয়েছে। আপনার সংযোগ পরীক্ষা করুন।",
        SHARE_ANNOUNCEMENT: "এই গুরুত্বপূর্ণ ঘোষণাটি শেয়ার করুন",
        HELP_OTHERS_DISCOVER: "অন্যদের সরকারি খবর জানতে সাহায্য করুন এবং আপনার সম্প্রদায়কে সচেতন রাখুন।",
        CHECK_OUT_THIS_AMAZING: "আমি মনে করি এই সরকারি ঘোষণাটি আপনার কাজে লাগতে পারে:",
        SHARE_ON: "এর মাধ্যমে শেয়ার করুন",
        CLICK_OPTION_TO_SHARE: "আপনার নেটওয়ার্কের সাথে শেয়ার করতে উপরের বিকল্পটি বেছে নিন।"
    },
    தமிழ்: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "அனைத்து அரசு அறிவிப்புகளையும் ஒரே ஒருங்கிணைந்த போர்ட்டலில் அணுகுங்கள்",
        INPUT_PLACEHOLDER: "முக்கிய வார்த்தை, துறை அல்லது தலைப்பு மூலம் தேடுங்கள்...",
        SEARCH: "இப்போது தேடு",
        PAGE: "தற்போதைய பக்கம்",
        OF: "இல்",
        SOURCE: "அசல் அதிகாரப்பூர்வ ஆவணத்தைப் பார்க்கவும்",
        NO_ANNOUNCEMENTS_FOUND: "உங்கள் தேடல் அளவுகோல்களுடன் பொருந்தக்கூடிய அறிவிப்புகள் எதுவும் இல்லை.",
        SEE_DETAILS: "முழு விவரங்களையும் காண்க",
        DISCOVER_MORE: "கூடுதல் தகவல்களை அறிய",
        INDIAN_ANNOUNCEMENTS: "இந்திய அரசின் அதிகாரப்பூர்வ அறிவிப்புகள்",
        SEE_MORE: "கூடுதல் புதுப்பிப்புகளைக் காண்க",
        VIEW_ALL: "அனைத்து அறிவிப்புகளையும் காண்க",
        VIEW_DETAILS: "விரிவான தகவல்",
        DESCRIPTION: "எங்கள் தளம் இந்தியா முழுவதிலும் உள்ள மாநில மற்றும் மத்திய அரசு அறிவிப்புகளைத் திரட்டி, உங்களுக்குப் புரிந்த மொழியில் எளிய முறையில் வழங்குகிறது.",
        SEE_ANNOUNCEMENTS: "அனைத்து அறிவிப்புகளையும் உலாவவும்",
        LOAD_MORE: "கூடுதல் செய்திகளை ஏற்றவும்",
        SOMETHING_WENT_WRONG: "தரவைப் பெறுவதில் பிழை ஏற்பட்டுள்ளது. சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.",
        SUBSCRIBE_TO_ALERTS: "உடனடி அறிவிப்புகளுக்குப் பதிவு செய்யவும்",
        NEVER_MISS_AN_UPDATE: "சமீபத்திய கொள்கை மாற்றங்கள் மற்றும் செய்திகளைத் தெரிந்துகொள்ளுங்கள். வாராந்திர செய்திகளைப் மின்னஞ்சலில் பெறுங்கள்.",
        SUBSCRIBE: "இப்போதே பதிவு செய்",
        ENTER_YOUR_EMAIL: "உங்கள் மின்னஞ்சல் முகவரியை உள்ளிடவும்",
        PLEASE_ENTER_YOUR_EMAIL: "தொடர சரியான மின்னஞ்சல் முகவரியை வழங்கவும்.",
        PLEASE_ENTER_A_VALID_EMAIL: "மின்னஞ்சல் வடிவம் தவறானது. சரிபார்த்து மீண்டும் முயற்சிக்கவும்.",
        SUCCESSFULLY_SUBSCRIBED: "எங்கள் வாராந்திர செய்திமடலில் வெற்றிகரமாகப் பதிவு செய்துள்ளீர்கள்.",
        FAILED_TO_SUBSCRIBE: "பதிவு செய்வதில் சிக்கல் ஏற்பட்டது. இணையத் தொடர்பைச் சரிபார்க்கவும்.",
        SHARE_ANNOUNCEMENT: "இந்த முக்கியமான அறிவிப்பைப் பகிரவும்",
        HELP_OTHERS_DISCOVER: "அரசுச் செய்திகளை மற்றவர்களும் தெரிந்துகொள்ள உதவுங்கள்.",
        CHECK_OUT_THIS_AMAZING: "இந்த அரசு அறிவிப்பு உங்களுக்குப் பயனுள்ளதாக இருக்கும் என நினைக்கிறேன்:",
        SHARE_ON: "மூலம் பகிரவும்",
        CLICK_OPTION_TO_SHARE: "உங்கள் நண்பர்களுடன் பகிர மேலே உள்ள விருப்பத்தைத் தேர்ந்தெடுக்கவும்."
    },
    తెలుగు: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "అన్ని ప్రభుత్వ ప్రకటనలను ఒకే చోట సులభంగా పొందండి",
        INPUT_PLACEHOLDER: "కీవర్డ్, శాఖ లేదా శీర్షిక ద్వారా వెతకండి...",
        SEARCH: "వెతకండి",
        PAGE: "ప్రస్తుత పేజీ",
        OF: "లో",
        SOURCE: "అధికారిక మూల పత్రాన్ని చూడండి",
        NO_ANNOUNCEMENTS_FOUND: "మీరు వెతుకుతున్న అంశానికి సంబంధించిన ప్రకటనలు ఏవీ లభించలేదు.",
        SEE_DETAILS: "పూర్తి వివరాలు చూడండి",
        DISCOVER_MORE: "మరింత సమాచారం",
        INDIAN_ANNOUNCEMENTS: "అధికారిక భారత ప్రభుత్వ ప్రకటనలు",
        SEE_MORE: "మరిన్ని అప్‌డేట్స్ చూడండి",
        VIEW_ALL: "అన్ని నోటిఫికేషన్లు చూడండి",
        VIEW_DETAILS: "వివరమైన సమాచారం",
        DESCRIPTION: "భారతదేశంలోని అన్ని రాష్ట్రాలు మరియు కేంద్ర విభాగాల నుండి వచ్చే ప్రభుత్వ ప్రకటనలను మా ప్లాట్‌ఫారమ్ సేకరించి, మీకు నచ్చిన భాషలో అందిస్తుంది.",
        SEE_ANNOUNCEMENTS: "అన్ని ప్రకటనలను బ్రౌజ్ చేయండి",
        LOAD_MORE: "మరిన్ని అప్‌డేట్స్ చూడండి",
        SOMETHING_WENT_WRONG: "డేటాను లోడ్ చేయడంలో లోపం జరిగింది. దయచేసి తర్వాత ప్రయత్నించండి.",
        SUBSCRIBE_TO_ALERTS: "నోటిఫికేషన్ల కోసం సబ్‌స్క్రయిబ్ చేయండి",
        NEVER_MISS_AN_UPDATE: "తాజా మార్పుల గురించి తెలుసుకోండి. వారపు అప్‌డేట్స్ నేరుగా మీ ఇమెయిల్‌లో పొందండి.",
        SUBSCRIBE: "ఇప్పుడే సబ్‌స్క్రయిబ్ చేయండి",
        ENTER_YOUR_EMAIL: "మీ ఇమెయిల్ చిరునామా నమోదు చేయండి",
        PLEASE_ENTER_YOUR_EMAIL: "కొనసాగడానికి సరైన ఇమెయిల్ ఇవ్వండి.",
        PLEASE_ENTER_A_VALID_EMAIL: "ఇమెయిల్ ఫార్మాట్ సరిగా లేదు. సరిచూసి మళ్ళీ ప్రయత్నించండి.",
        SUCCESSFULLY_SUBSCRIBED: "మీరు మా వారపు వార్తాలేఖకు విజయవంతంగా సబ్‌స్క్రయిబ్ అయ్యారు.",
        FAILED_TO_SUBSCRIBE: "సబ్‌స్క్రయిబ్ చేయడంలో సమస్య ఎదురైంది. మీ ఇంటర్నెట్ కనెక్షన్ చూడండి.",
        SHARE_ANNOUNCEMENT: "ఈ ముఖ్యమైన ప్రకటనను షేర్ చేయండి",
        HELP_OTHERS_DISCOVER: "అధికారిక ప్రభుత్వ వార్తలను ఇతరులకు కూడా తెలియజేయండి.",
        CHECK_OUT_THIS_AMAZING: "ఈ ప్రభుత్వ ప్రకటన మీకు ఉపయోగకరంగా ఉంటుందని భావిస్తున్నాను:",
        SHARE_ON: "ద్వారా షేర్ చేయండి",
        CLICK_OPTION_TO_SHARE: "మీ నెట్‌వర్క్‌తో షేర్ చేయడానికి పై ఆప్션을 ఎంచుకోండి."
    },
    മലയാളം: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "എല്ലാ സർക്കാർ അറിയിപ്പുകളും ഇനി ഒരു ഏകീകൃത പോർട്ടലിൽ",
        INPUT_PLACEHOLDER: "കീവേഡ്, വകുപ്പ് അല്ലെങ്കിൽ അറിയിപ്പിന്റെ പേര് ഉപയോഗിച്ച് തിരയുക...",
        SEARCH: "തിരയുക",
        PAGE: "നിലവിലെ പേജ്",
        OF: "ൽ",
        SOURCE: "ഔദ്യോഗിക ഉറവിട രേഖ കാണുക",
        NO_ANNOUNCEMENTS_FOUND: "നിങ്ങളുടെ തിരച്ചിലിന് അനുയോജ്യമായ അറിയിപ്പുകളൊന്നും കണ്ടെത്താനായില്ല.",
        SEE_DETAILS: "പൂർണ്ണ വിവരങ്ങൾ കാണുക",
        DISCOVER_MORE: "കൂടുതൽ വിവരങ്ങൾക്കായി",
        INDIAN_ANNOUNCEMENTS: "ഔദ്യോഗിക ഭാരത സർക്കാർ അറിയിപ്പുകൾ",
        SEE_MORE: "കൂടുതൽ വാർത്തകൾ കാണുക",
        VIEW_ALL: "എല്ലാ അറിയിപ്പുകളും കാണുക",
        VIEW_DETAILS: "വിശദമായ വിവരങ്ങൾ",
        DESCRIPTION: "ഇന്ത്യയിലുടനീളമുള്ള എല്ലാ സംസ്ഥാനങ്ങളിൽ നിന്നും കേന്ദ്ര വകുപ്പുകളിൽ നിന്നുമുള്ള സർക്കാർ അറിയിപ്പുകൾ ഞങ്ങളുടെ പ്ലാറ്റ്‌ഫോം ശേഖരിക്കുകയും നിങ്ങൾക്ക് മനസ്സിലാകുന്ന ഭാഷയിൽ നൽകുകയും ചെയ്യുന്നു.",
        SEE_ANNOUNCEMENTS: "എല്ലാ അറിയിപ്പുകളും പരിശോധിക്കുക",
        LOAD_MORE: "കൂടുതൽ വാർത്തകൾക്കായി",
        SOMETHING_WENT_WRONG: "വിവരങ്ങൾ ശേഖരിക്കുന്നതിൽ തടസ്സം നേരിട്ടു. ദയവായി പിന്നീട് ശ്രമിക്കുക.",
        SUBSCRIBE_TO_ALERTS: "തത്സമയ അറിയിപ്പുകൾക്കായി സബ്‌സ്‌ക്രൈബ് ചെയ്യുക",
        NEVER_MISS_AN_UPDATE: "പുതിയ നയ മാറ്റങ്ങളെയും വാർത്തകളെയും കുറിച്ച് അറിഞ്ഞിരിക്കുക. പ്രതിവാര അപ്‌ഡേറ്റുകൾ ഇമെയിലിൽ നേടുക.",
        SUBSCRIBE: "ഇപ്പോൾ സബ്‌സ്‌ക്രൈബ് ചെയ്യുക",
        ENTER_YOUR_EMAIL: "നിങ്ങളുടെ ഇമെയിൽ വിലാസം നൽകുക",
        PLEASE_ENTER_YOUR_EMAIL: "തുടരുന്നതിനായി ശരിയായ ഇമെയിൽ വിലാസം നൽകുക.",
        PLEASE_ENTER_A_VALID_EMAIL: "ഇമെയിൽ വിലാസത്തിൽ തെറ്റുണ്ട്. ദയവായി പരിശോധിക്കുക.",
        SUCCESSFULLY_SUBSCRIBED: "നിങ്ങൾ വിജയകരമായി സബ്‌സ്‌ക്രൈബ് ചെയ്തിരിക്കുന്നു.",
        FAILED_TO_SUBSCRIBE: "സബ്‌സ്‌ക്രൈബ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു. ഇന്റർനെറ്റ് പരിശോധിക്കുക.",
        SHARE_ANNOUNCEMENT: "ഈ പ്രധാന വാർത്ത പങ്കിടുക",
        HELP_OTHERS_DISCOVER: "ഔദ്യോഗിക സർക്കാർ വാർത്തകൾ മറ്റുള്ളവരിലേക്കും എത്തിക്കാൻ സഹായിക്കുക.",
        CHECK_OUT_THIS_AMAZING: "ഈ സർക്കാർ അറിയിപ്പ് നിങ്ങൾക്ക് ഉപകാരപ്പെടുമെന്ന് കരുതുന്നു:",
        SHARE_ON: "ലൂടെ പങ്കിടുക",
        CLICK_OPTION_TO_SHARE: "മറ്റുള്ളവർക്ക് പങ്കിടാൻ മുകളിലുള്ള ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക."
    },
    मराठी: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "सर्व अधिकृत सरकारी घोषणा आता एकाच व्यासपीठावर उपलब्ध",
        INPUT_PLACEHOLDER: "कीवर्ड, विभाग किंवा शीर्षकानुसार शोधा...",
        SEARCH: "आता शोधा",
        PAGE: "सध्याचे पृष्ठ",
        OF: "पैकी",
        SOURCE: "मूळ अधिकृत दस्तऐवज पहा",
        NO_ANNOUNCEMENTS_FOUND: "तुमच्या शोध निकषांशी जुळणारी कोणतीही घोषणा आम्हाला आढळली नाही.",
        SEE_DETAILS: "पूर्ण तपशील पहा",
        DISCOVER_MORE: "अधिक माहिती मिळवा",
        INDIAN_ANNOUNCEMENTS: "अधिकृत भारतीय सरकारी घोषणा",
        SEE_MORE: "अधिक अपडेट्स पहा",
        VIEW_ALL: "सर्व अधिसूचना पहा",
        VIEW_DETAILS: "सविस्तर माहिती",
        DESCRIPTION: "आमचे व्यासपीठ भारतातील सर्व राज्ये आणि केंद्रीय विभागांमधील सरकारी अधिसूचना एकत्रित करते आणि तुमच्या पसंतीच्या भाषेत त्यांचे अचूक भाषांतर प्रदान करते.",
        SEE_ANNOUNCEMENTS: "सर्व घोषणा पहा",
        LOAD_MORE: "अधिक माहिती लोड करा",
        SOMETHING_WENT_WRONG: "डेटा प्राप्त करताना त्रुटी आली. कृपया नंतर पुन्हा प्रयत्न करा.",
        SUBSCRIBE_TO_ALERTS: "रिअल-टाइम अलर्टसाठी सबस्क्राइब करा",
        NEVER_MISS_AN_UPDATE: "नवीनतम धोरण बदलांची माहिती मिळवा. तुमच्या इनबॉक्समध्ये साप्ताहिक अलर्ट मिळवा.",
        SUBSCRIBE: "आताच सबस्क्राइब करा",
        ENTER_YOUR_EMAIL: "तुमचा ईमेल पत्ता प्रविष्ट करा",
        PLEASE_ENTER_YOUR_EMAIL: "कृपया पुढे जाण्यासाठी वैध ईमेल पत्ता द्या.",
        PLEASE_ENTER_A_VALID_EMAIL: "ईमेल फॉरमॅट चुकीचा आहे. कृपया तपासा.",
        SUCCESSFULLY_SUBSCRIBED: "तुम्ही आमच्या साप्ताहिक वृत्तपत्रासाठी यशस्वीरित्या सबस्क्राइब झाले आहात.",
        FAILED_TO_SUBSCRIBE: "सबस्क्रिप्शन दरम्यान समस्या आली. कृपया कनेक्शन तपासा.",
        SHARE_ANNOUNCEMENT: "ही महत्त्वाची घोषणा शेअर करा",
        HELP_OTHERS_DISCOVER: "इतरांना अधिकृत सरकारी बातम्यांसह अपडेट राहण्यास मदत करा.",
        CHECK_OUT_THIS_AMAZING: "मला वाटले कि तुम्हाला ही सरकारी घोषणा उपयुक्त वाटेल:",
        SHARE_ON: "द्वारे शेअर करा",
        CLICK_OPTION_TO_SHARE: "तुमच्या नेटवर्कसह शेअर करण्यासाठी वरील पर्याय निवडा."
    },
    ગુજરાતી: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "તમામ સત્તાવાર સરકારી જાહેરાતો હવે એક જ પોર્ટલ પર",
        INPUT_PLACEHOLDER: "કીવર્ડ, વિભાગ અથવા શીર્ષક દ્વારા શોધો...",
        SEARCH: "શોધો",
        PAGE: "વર્તમાન પૃષ્ઠ",
        OF: "માંથી",
        SOURCE: "સત્તાવાર સ્ત્રોત દસ્તાવેજ જુઓ",
        NO_ANNOUNCEMENTS_FOUND: "તમારા શોધ માપદંડ મુજબ કોઈ જાહેરાત મળી નથી.",
        SEE_DETAILS: "સંપૂર્ણ વિગતો જુઓ",
        DISCOVER_MORE: "વધુ જાણકારી મેળવો",
        INDIAN_ANNOUNCEMENTS: "સત્તાવાર ભારતીય સરકારી જાહેરાતો",
        SEE_MORE: "વધુ અપડેટ્સ જુઓ",
        VIEW_ALL: "તમામ સૂચનાઓ જુઓ",
        VIEW_DETAILS: "વિગતવાર માહિતી",
        DESCRIPTION: "અમારું પ્લેટફોર્મ ભારતભરના તમામ રાજ્યો અને કેન્દ્રીય વિભાગોમાંથી સરકારી સૂચનાઓ એકત્રિત કરે છે અને તમારી ભાષામાં તેનું ભાષાંતર કરે છે.",
        SEE_ANNOUNCEMENTS: "તમામ જાહેરાતો જુઓ",
        LOAD_MORE: "વધુ અપડેટ લોડ કરો",
        SOMETHING_WENT_WRONG: "ડેટા મેળવવામાં ભૂલ થઈ છે. કૃપા કરીને ફરી પ્રયાસ કરો.",
        SUBSCRIBE_TO_ALERTS: "સૂચનાઓ મેળવવા માટે સબસ્ક્રાઇબ કરો",
        NEVER_MISS_AN_UPDATE: "નવીનતમ નીતિ ફેરફારોથી માહિતગાર રહો. તમારા ઇનબોક્સમાં સાપ્તાહિક એલર્ટ મેળવો.",
        SUBSCRIBE: "સબસ્ક્રાઇબ કરો",
        ENTER_YOUR_EMAIL: "તમારું ઇમેઇલ સરનામું લખો",
        PLEASE_ENTER_YOUR_EMAIL: "આગળ વધવા માટે કૃપા કરીને માન્ય ઇમેઇલ આપો.",
        PLEASE_ENTER_A_VALID_EMAIL: "ઇમેઇલ ફોર્મેટ ખોટું છે. કૃપા કરીને તપાસો.",
        SUCCESSFULLY_SUBSCRIBED: "તમે સાપ્ताહિક ન્યૂઝલેટર માટે સફળતાપૂર્વક સબસ્ક્રાઇબ થયા છો.",
        FAILED_TO_SUBSCRIBE: "સબસ્ક્રાઇબ કરવામાં સમસ્યા આવી. કૃપા કરીને કનેક્શન તપાસો.",
        SHARE_ANNOUNCEMENT: "આ મહત્વપૂર્ણ જાહેરાત શેર કરો",
        HELP_OTHERS_DISCOVER: "અન્ય લોકોને સત્તાવાર સરકારી સમાચારોથી માહિતગાર રહેવામાં મદદ કરો.",
        CHECK_OUT_THIS_AMAZING: "મને લાગ્યું કે તમને આ સરકારી જાહેરાત ઉપયોગી લાગશે:",
        SHARE_ON: "દ્વારા શેર કરો",
        CLICK_OPTION_TO_SHARE: "તમારા નેટવર્ક સાથે શેર કરવા માટે ઉપરનો વિકલ્પ પસંદ કરો."
    },
    ಕನ್ನಡ: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "ಎಲ್ಲಾ ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಘೋಷಣೆಗಳನ್ನು ಒಂದೇ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಪ್ರವೇಶಿಸಿ",
        INPUT_PLACEHOLDER: "ಕೀವರ್ಡ್, ಇಲಾಖೆ ಅಥವಾ ಶೀರ್ಷಿಕೆಯ ಮೂಲಕ ಹುಡುಕಿ...",
        SEARCH: "ಹುಡುಕಿ",
        PAGE: "ಪ್ರಸ್ತುತ ಪುಟ",
        OF: "ರಲ್ಲಿ",
        SOURCE: "ಮೂಲ ಅಧಿಕೃತ ದಾಖಲೆಯನ್ನು ನೋಡಿ",
        NO_ANNOUNCEMENTS_FOUND: "ನಿಮ್ಮ ಹುಡುಕಾಟಕ್ಕೆ ಪೂರಕವಾದ ಯಾವುದೇ ಘೋಷಣೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
        SEE_DETAILS: "ಪೂರ್ಣ ವಿವರಗಳನ್ನು ನೋಡಿ",
        DISCOVER_MORE: "ಹೆಚ್ಚಿನ ಮಾಹಿತಿ ಪಡೆಯಿರಿ",
        INDIAN_ANNOUNCEMENTS: "ಅಧಿಕೃತ ಭಾರತ ಸರ್ಕಾರಿ ಘೋಷಣೆಗಳು",
        SEE_MORE: "ಹೆಚ್ಚಿನ ಅಪ್‌ಡೇಟ್‌ಗಳನ್ನು ನೋಡಿ",
        VIEW_ALL: "ಎಲ್ಲಾ ಅಧಿಸೂਚನೆಗಳನ್ನು ನೋಡಿ",
        VIEW_DETAILS: "ವಿವರವಾದ ಮಾಹಿತಿ",
        DESCRIPTION: "ನಮ್ಮ ವೇದಿಕೆಯು ಭಾರತದಾದ್ಯಂತದ ಎಲ್ಲಾ ರಾಜ್ಯಗಳು ಮತ್ತು ಕೇಂದ್ರ ಇಲಾಖೆಗಳಿಂದ ಸರ್ಕಾರಿ ಅಧಿಸೂಚನೆಗಳನ್ನು ಸಂಗ್ರಹಿಸಿ, ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭାಷೆಯಲ್ಲಿ ಅನುವಾದಿಸಿ ಒದಗಿಸುತ್ತದೆ.",
        SEE_ANNOUNCEMENTS: "ಎಲ್ಲಾ ಘೋಷಣೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
        LOAD_MORE: "ಹೆಚ್ಚಿನ ಅಪ್‌ಡೇಟ್‌ಗಳನ್ನು ಲೋಡ್ ಮಾಡಿ",
        SOMETHING_WENT_WRONG: "ಡೇಟಾವನ್ನು ಪಡೆಯುವಲ್ಲಿ ದೋಷ ಸಂಭವಿಸಿದೆ. ದಯವಿಟ್ಟು ನಂತರ ಪ್ರಯತ್ನಿಸಿ.",
        SUBSCRIBE_TO_ALERTS: "ಅಲರ್ಟ್‌ಗಳಿಗಾಗಿ ಚಂದಾದಾರರಾಗಿ",
        NEVER_MISS_AN_UPDATE: "ಇತ್ತೀಚಿನ ನೀತಿ ಬದಲಾವಣೆಗಳ ಬಗ್ಗೆ ತಿಳಿದಿರಲಿ. ನಿಮ್ಮ ಇಮೇಲ್‌ನಲ್ಲಿ ಸಾಪ್ತಾಹಿಕ ಅಲರ್ಟ್‌ಗಳನ್ನು ಪಡೆಯಿರಿ.",
        SUBSCRIBE: "ಈಗಲೇ ಚಂದಾದಾರರಾಗಿ",
        ENTER_YOUR_EMAIL: "ನಿಮ್ಮ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ",
        PLEASE_ENTER_YOUR_EMAIL: "ಮುಂದುವರಿಯಲು ದಯವಿಟ್ಟು ಮಾನ್ಯ ಇಮೇಲ್ ಒದಗಿಸಿ.",
        PLEASE_ENTER_A_VALID_EMAIL: "ಇಮೇಲ್ ವಿಳಾಸ ಸರಿಯಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು ಪರಿಶೀಲಿಸಿ.",
        SUCCESSFULLY_SUBSCRIBED: "ನೀವು ಯಶಸ್ವಿಯಾಗಿ ಚಂದಾದਾਰರಾಗಿದ್ದೀರಿ.",
        FAILED_TO_SUBSCRIBE: "ಚಂದಾದಾರರಾಗುವಲ್ಲಿ ತೊಂದರೆಯಾಗಿದೆ. ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ.",
        SHARE_ANNOUNCEMENT: "ಈ ಪ್ರಮುಖ ಘೋಷಣೆಯನ್ನು ಹಂಚಿಕೊಳ್ಳಿ",
        HELP_OTHERS_DISCOVER: "ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಸುದ್ದಿಗಳೊಂದಿಗೆ ಅಪ್‌ಡೇಟ್ ಆಗಿರಲು ಇತರರಿಗೆ ಸಹಾಯ ಮಾಡಿ.",
        CHECK_OUT_THIS_AMAZING: "ಈ ಸರ್ಕಾರಿ ಘೋಷಣೆ ನಿಮಗೆ ಉಪಯುಕ್ತವಾಗಬಹುದು ಎಂದು ನಾನು ಭಾವಿಸುತ್ತೇನೆ:",
        SHARE_ON: "ಮೂલಕ ಹಂಚಿಕೊಳ್ಳಿ",
        CLICK_OPTION_TO_SHARE: "ನಿಮ್ಮ ನೆಟ್‌ವರ್ಕ್‌ನೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಲು ಮೇಲಿನ ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ."
    },
    اردو: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "تمام سرکاری اعلانات اب ایک ہی پورٹل پر دستیاب ہیں",
        INPUT_PLACEHOLDER: "کی ورڈ، محکمہ یا عنوان کے ذریعے تلاش کریں...",
        SEARCH: "ابھی تلاش کریں",
        PAGE: "موجودہ صفحہ",
        OF: "میں سے",
        SOURCE: "اصل سرکاری دستاویز دیکھیں",
        NO_ANNOUNCEMENTS_FOUND: "آپ کی تلاش کے مطابق کوئی اعلان نہیں ملا۔",
        SEE_DETAILS: "مکمل تفصیلات دیکھیں",
        DISCOVER_MORE: "مزید معلومات حاصل کریں",
        INDIAN_ANNOUNCEMENTS: "آفیشل ہندوستانی سرکاری اعلانات",
        SEE_MORE: "مزید اپ ڈیٹس دیکھیں",
        VIEW_ALL: "تمام نوٹیفیکیشن دیکھیں",
        VIEW_DETAILS: "تفصیلی معلومات",
        DESCRIPTION: "ہمارا پلیٹ فارم تمام ہندوستانی ریاستوں اور مرکزی محکموں سے سرکاری نوٹیفیکیشنز کو ذہانت سے اکٹھا کرتا ہے اور آپ کی ترجیحی زبان میں ترجمہ فراہم کرتا ہے۔",
        SEE_ANNOUNCEMENTS: "تمام اعلانات براؤز کریں",
        LOAD_MORE: "مزید اپ ڈیٹس لوڈ کریں",
        SOMETHING_WENT_WRONG: "ڈیٹا حاصل کرنے میں غلطی ہوئی۔ براہ کرم بعد میں کوشش کریں۔",
        SUBSCRIBE_TO_ALERTS: "فوری الرٹس کے لیے سبسکرائب کریں",
        NEVER_MISS_AN_UPDATE: "پالیسی کی تبدیلیوں سے باخبر رہیں۔ ہفتہ وار الرٹس براہ راست اپنے ان باکس میں حاصل کریں۔",
        SUBSCRIBE: "ابھی سبسکرائب کریں",
        ENTER_YOUR_EMAIL: "اپنا ای میل پتہ درج کریں",
        PLEASE_ENTER_YOUR_EMAIL: "جاری رکھنے کے لیے درست ای میل فراہم کریں۔",
        PLEASE_ENTER_A_VALID_EMAIL: "ای میل کا فارمیٹ درست نہیں ہے۔",
        SUCCESSFULLY_SUBSCRIBED: "آپ نے ہمارے نیوز لیٹر کو کامیابی سے سبسکرائب کر لیا ہے۔",
        FAILED_TO_SUBSCRIBE: "سبسکرائب کرنے میں دشواری پیش آئی۔ کنکشن چیک کریں۔",
        SHARE_ANNOUNCEMENT: "یہ اہم اعلان شیئر کریں",
        HELP_OTHERS_DISCOVER: "سرکاری خبروں کے ذریعے دوسروں کی مدد کریں تاکہ وہ باخبر رہ سکیں۔",
        CHECK_OUT_THIS_AMAZING: "مجھے لگا کہ یہ سرکاری اعلان آپ کے لیے مفید ہو سکتا ہے:",
        SHARE_ON: "کے ذریعے شیئر کریں",
        CLICK_OPTION_TO_SHARE: "اپنے نیٹ ورک کے ساتھ شیئر کرنے کے لیے اوپر والا آپشن منتخب کریں۔"
    },
    অসমীয়া: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "সকলো চৰকাৰী ঘোষণা এতিয়া এটা সমন্বিত পৰ্টেলত",
        INPUT_PLACEHOLDER: "বিভাগ বা শিৰোনাম অনুসৰি সন্ধান কৰক...",
        SEARCH: "সন্ধান কৰক",
        PAGE: "বৰ্তমানৰ পৃষ্ঠা",
        OF: "ৰ ভিতৰত",
        SOURCE: "মূল চৰকাৰী নথিপত্ৰ চাওক",
        NO_ANNOUNCEMENTS_FOUND: "আপোনাৰ সন্ধানৰ সৈতে মিল থকা কোনো ঘোষণা পোৱা নগ'ল।",
        SEE_DETAILS: "সম্পূৰ্ণ বিৱৰণ চাওক",
        DISCOVER_MORE: "অধিক তথ্য লাভ কৰক",
        INDIAN_ANNOUNCEMENTS: "চৰকাৰী ভাৰতীয় ঘোষণা",
        SEE_MORE: "অধিক আপডেট চাওক",
        VIEW_ALL: "সকলো জাননী চাওক",
        VIEW_DETAILS: "বিতং তথ্য",
        DESCRIPTION: "আমাৰ প্লেটফৰ্মে সমগ্ৰ ভাৰতৰ সকলো ৰাজ্য আৰু কেন্দ্ৰীয় বিভাগৰ পৰা চৰকাৰী জাননীসমূহ সংগ্ৰহ কৰি আপোনাৰ স্থানীয় ভাষাত সহজকৈ আগবঢ়ায়।",
        SEE_ANNOUNCEMENTS: "সকলো ঘোষণা ব্ৰাউজ কৰক",
        LOAD_MORE: "অধিক আপডেট চাওক",
        SOMETHING_WENT_WRONG: "তথ্য লাভ কৰোঁতে এটা সমস্যা হৈছে। অনুগ੍ਰহ কৰি পিছত চেষ্টা কৰক।",
        SUBSCRIBE_TO_ALERTS: "এলাৰ্টৰ বাবে চাবস্ক্ৰাইব কৰক",
        NEVER_MISS_AN_UPDATE: "নীতিৰ পৰিৱৰ্তনসমূহৰ বিষয়ে অৱগত থাকক। সাপ্তাহিক এলাৰ্ট লাভ কৰক।",
        SUBSCRIBE: "চাবস্ক্ৰাইব কৰক",
        ENTER_YOUR_EMAIL: "আপোনাৰ ইমেইল ঠিকনা লিখক",
        PLEASE_ENTER_YOUR_EMAIL: "আগবাঢ়িবলৈ এটা সঠিক ইমেইল দিয়ক।",
        PLEASE_ENTER_A_VALID_EMAIL: "ইমেইল ফৰ্মেটটো ভুল। অনুগ্ৰহ কৰি পৰীক্ষা কৰক।",
        SUCCESSFULLY_SUBSCRIBED: "আপুনি সফলভাৱে চাবস্ক্ৰাইব কৰিছে।",
        FAILED_TO_SUBSCRIBE: "চাবস্ক্ৰাইব কৰিবলৈ বিফল হৈছে। সংযোগ পৰীক্ষা কৰক।",
        SHARE_ANNOUNCEMENT: "এই গুৰুত্বপূৰ্ণ ঘোষণাটো শ্বেয়াৰ কৰক",
        HELP_OTHERS_DISCOVER: "আনকো চৰকাৰী খবৰৰ বিষয়ে অৱগত হ'বলৈ সহায় কৰক।",
        CHECK_OUT_THIS_AMAZING: "মই ভাবো এই ঘোষণাটো আপোনাৰ কামত আহিব পাৰে:",
        SHARE_ON: "দ্বাৰা শ্বেয়াৰ কৰক",
        CLICK_OPTION_TO_SHARE: "শ্বেয়াৰ কৰিবলৈ ওপৰৰ বিকল্পটো বাছনি কৰক।"
    },
    "बरʼ": {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "गासै सरकारी फोसावनायफोरखौ मोनसे पोर्टलआव मोननो हागोन",
        INPUT_PLACEHOLDER: "मुं एबा बिफानजों नायगिर...",
        SEARCH: "नायगिर",
        PAGE: "बिलाइ",
        OF: "नि",
        SOURCE: "गुबै बिलाइखौ नाय",
        NO_ANNOUNCEMENTS_FOUND: "जेबो फोसावनाय मोनाखै।",
        SEE_DETAILS: "गासैखौबो नाय",
        DISCOVER_MORE: "गोबां मिथिनो",
        INDIAN_ANNOUNCEMENTS: "भारत सरकारनि फोसावनाय",
        SEE_MORE: "गोबां अपडेट नाय",
        VIEW_ALL: "गासैखौबो नाय",
        VIEW_DETAILS: "गासै फोरमायथि",
        DESCRIPTION: "जोंनि मन्चआ भारतनि गासै राज्यो आरो मिरु बिफाननि फोसावनायफोरखौ बुथुमो आरो नोंथांनि रावआव सोलायो।",
        SEE_ANNOUNCEMENTS: "फोसावनायफोरखौ नाय",
        LOAD_MORE: "गोबां अपडेट लोद खालाम",
        SOMETHING_WENT_WRONG: "गोरोन्थि जादों। उन जाब नायफिन।",
        SUBSCRIBE_TO_ALERTS: "सबस्क्राइब खालाम",
        NEVER_MISS_AN_UPDATE: "गोदान फोसावनायफोरनि खौरां मोन। ईमेलआव फोसावनाय मोन।",
        SUBSCRIBE: "सबस्क्राइब",
        ENTER_YOUR_EMAIL: "नोंथांनि ईमेल लिर",
        PLEASE_ENTER_YOUR_EMAIL: "मोजां ईमेल लिर।",
        PLEASE_ENTER_A_VALID_EMAIL: "ईमेलआ गोरोन्थि जादों।",
        SUCCESSFULLY_SUBSCRIBED: "सबस्क्राइब जाबाय।",
        FAILED_TO_SUBSCRIBE: "सबस्क्राइब जायाखै।",
        SHARE_ANNOUNCEMENT: "शेयर खालाम",
        HELP_OTHERS_DISCOVER: "गुबुनफोरनोबो खौरां हो।",
        CHECK_OUT_THIS_AMAZING: "बे फोसावनायखौ नाय:",
        SHARE_ON: "जों शेयर खालाम",
        CLICK_OPTION_TO_SHARE: "शेयर खालामनो थाखाय क्लिक खालाम।"
    },
    डोगरी: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "सारे सरकारी ऐलान हुण इक्की पोर्टल पर उपलब्ध न",
        INPUT_PLACEHOLDER: "कीवर्ड या विभाग दे नां कन्ने तलाश करो...",
        SEARCH: "तलाश करो",
        PAGE: "मौजूदा सफा",
        OF: "शा",
        SOURCE: "असली सरकारी दस्तावेज दिक्खो",
        NO_ANNOUNCEMENTS_FOUND: "थुआडी तलाश दे मुताबिक कोई ऐलान नेईं मिलिया।",
        SEE_DETAILS: "पूरा ब्यौरा दिक्खो",
        DISCOVER_MORE: "होर जानकारी हासल करो",
        INDIAN_ANNOUNCEMENTS: "सराहनीय भारतीय सरकारी ऐलान",
        SEE_MORE: "होर अपडेट दिक्खो",
        VIEW_ALL: "सारे नोटिफिकेशन दिक्खो",
        VIEW_DETAILS: "विस्तृत जानकारी",
        DESCRIPTION: "साडा प्लेटफॉर्म भारत दे सारे राज्यें ते केंद्रीय विभागें शा सरकारी सूचनाएं इकट्ठा करदा है ते थुआडी मर्जी दी भाषा च अनुवाद करदा है।",
        SEE_ANNOUNCEMENTS: "सारे ऐलान ब्राउज करो",
        LOAD_MORE: "होर अपडेट लोड करो",
        SOMETHING_WENT_WRONG: "डेटा हासल करदे बेले कोई गलती होई गई।",
        SUBSCRIBE_TO_ALERTS: "अलर्ट लेई सबस्क्राइब करो",
        NEVER_MISS_AN_UPDATE: "नीति च बदलाव दी जानकारी लेई साप्ताहिक अलर्ट हासल करो।",
        SUBSCRIBE: "सबस्क्राइब करो",
        ENTER_YOUR_EMAIL: "अपना ईमेल पता लिखो",
        PLEASE_ENTER_YOUR_EMAIL: "जारी रखने लेई सही ईमेल देओ।",
        PLEASE_ENTER_A_VALID_EMAIL: "ईमेल दा फार्मेट सही नेईं ऐ।",
        SUCCESSFULLY_SUBSCRIBED: "थुआडा सबस्क्रिप्शन कामयाब रिया।",
        FAILED_TO_SUBSCRIBE: "सबस्क्राइब करदे बेले कोई मुश्कल आई गई।",
        SHARE_ANNOUNCEMENT: "इस जरूरी ऐलान की साझा करो",
        HELP_OTHERS_DISCOVER: "होर लोकें की सरकारी खबरें कन्नै अपडेट रहने च मदद करो।",
        CHECK_OUT_THIS_AMAZING: "में सोच्या ए ऐलान थुआडे लेई फायदेमंद होई सकदा ऐ:",
        SHARE_ON: "दे जरिए साझा करो",
        CLICK_OPTION_TO_SHARE: "साझा करने लेई ऊपर दित्ते गे विकल्प चुनिए।"
    },
    कॉशुर: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "سٲری سرکاری اعلان چھِ وِنہٕ اکہِ پورٹلس پیٹھ میسر",
        INPUT_PLACEHOLDER: "تلاش کٔریو محکمہٕ یا عنوان ذٔریعہٕ...",
        SEARCH: "وِنہٕ تلاش کٔریو",
        PAGE: "موجودہ صفحہ",
        OF: "منزہ",
        SOURCE: "اَصلی سرکاری دستاویز وُچھو",
        NO_ANNOUNCEMENTS_FOUND: "تُہندِ تلاشس مُطٲبق کانہہ اعلان نی میلو।",
        SEE_DETAILS: "پوٗرٕ تفصیل وُچھو",
        DISCOVER_MORE: "مزید معلومات حٲصل کٔریو",
        INDIAN_ANNOUNCEMENTS: "ہندوستانی سرکاری اعلان",
        SEE_MORE: "مزید اپ ڈیٹس وُچھو",
        VIEW_ALL: "سٲری اطلاع وُچھو",
        VIEW_DETAILS: "تَفصیلی معلومات",
        DESCRIPTION: "یہِ پلیٹ فارم چھُ ہندوستانچہِ سٲرنی ریاستن ہِندِ محکمہٕ منزہ سرکاری اطلاع جمع کَران تہٕ تُہندِ زبان منز ترجمہٕ کَران।",
        SEE_ANNOUNCEMENTS: "سٲری اعلان وُچھو",
        LOAD_MORE: "مزید اپ ڈیٹس وُچھو",
        SOMETHING_WENT_WRONG: "ڈیٹا حٲصل کَرنس منز گٔژھ کانہہ غَلطی।",
        SUBSCRIBE_TO_ALERTS: "سبسکرائب کٔریو الرٹس خٲطرٕ",
        NEVER_MISS_AN_UPDATE: "پالیسی منز تَبدیلی ہِندِ بابت باخبر روزیو। الرٹس حٲصل کٔریو।",
        SUBSCRIBE: "وِنہٕ سبسکرائب کٔریو",
        ENTER_YOUR_EMAIL: "پنُن ای میل درج کٔریو",
        PLEASE_ENTER_YOUR_EMAIL: "ای میل دِییو جاری تھونہٕ خٲطرٕ।",
        PLEASE_ENTER_A_VALID_EMAIL: "ای میل فارمیٹ چھُ غَلط।",
        SUCCESSFULLY_SUBSCRIBED: "تُہی کٔریو کامیابی سان سبسکرائب।",
        FAILED_TO_SUBSCRIBE: "سبسکرائب کَرنس منز گٔژھ رُکاوٹ।",
        SHARE_ANNOUNCEMENT: "یہِ اہم اعلان کٔریو شیئر",
        HELP_OTHERS_DISCOVER: "باقی لوکن تہِ کٔریو سرکاری خبرن سٟتؠ باخبر روزنس منز مَدَد।",
        CHECK_OUT_THIS_AMAZING: "مےٚ باسیو یہِ اعلان آسِہ تُہندِ خٲطرٕ کارآمد:",
        SHARE_ON: "ذٔریعہٕ کٔریو شیئر",
        CLICK_OPTION_TO_SHARE: "شیئر کَرنہٕ خٲطرٕ کٔریو آپشن منتخب।"
    },
    मैथिली: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "सब आधिकारिक सरकारी घोषणा आब एकहि पोर्टल पर उपलब्ध",
        INPUT_PLACEHOLDER: "कीवर्ड, विभाग वा घोषणाक शीर्षक सं खोजू...",
        SEARCH: "एखन खोजू",
        PAGE: "वर्तमान पृष्ठ",
        OF: "क",
        SOURCE: "आधिकारिक स्रोत दस्तावेज देखू",
        NO_ANNOUNCEMENTS_FOUND: "अहाँक खोजक अनुसार कोनो घोषणा नहि भेटल।",
        SEE_DETAILS: "पूर्ण विवरण देखू",
        DISCOVER_MORE: "आओर जानकारी प्राप्त करू",
        INDIAN_ANNOUNCEMENTS: "आधिकारिक भारतीय सरकारी घोषणा",
        SEE_MORE: "आओर अपडेट देखू",
        VIEW_ALL: "सब सूचना देखू",
        VIEW_DETAILS: "विस्तृत जानकारी",
        DESCRIPTION: "अहाँक लेल हमर प्लेटफ़ॉर्म सभटा भारतीय राज्य आ केंद्रीय विभागक सरकारी सूचना एकत्रित कऽ कऽ अहाँक भाषा मे अनुवाद करैत अछि।",
        SEE_ANNOUNCEMENTS: "सब घोषणा देखू",
        LOAD_MORE: "आओर अपडेट लोड करू",
        SOMETHING_WENT_WRONG: "डाटा प्राप्त करबा मे त्रुटि भेल। कृपया बाद मे प्रयास करू।",
        SUBSCRIBE_TO_ALERTS: "अलर्टक लेल सबस्क्राइब करू",
        NEVER_MISS_AN_UPDATE: "नीति मे बदलाव सं अवगत रहू। साप्ताहिक अलर्ट अपन इनबॉक्स मे पाबू।",
        SUBSCRIBE: "एखने सबस्क्राइब करू",
        ENTER_YOUR_EMAIL: "अपन ईमेल पता लिखू",
        PLEASE_ENTER_YOUR_EMAIL: "आगाँ बढ़बाक लेल एकटा वैध ईमेल पता दियौ।",
        PLEASE_ENTER_A_VALID_EMAIL: "ईमेलक प्रारूप गलत अछि।",
        SUCCESSFULLY_SUBSCRIBED: "अहाँ हमर साप्ताहिक न्यूजलेटरक लेल सफलतापूर्वक सबस्क्राइब भऽ गेलहुँ।",
        FAILED_TO_SUBSCRIBE: "सबस्क्रिप्शन मे समस्या भेल।",
        SHARE_ANNOUNCEMENT: "ई महत्वपूर्ण घोषणा साझा करू",
        HELP_OTHERS_DISCOVER: "दोसर लोक कें सेहो सरकारी खबड़ सं अपडेट रहय मे मदद करू।",
        CHECK_OUT_THIS_AMAZING: "हमरा लागल जे अहाँक लेल ई घोषणा उपयोगी भऽ सकैत अछि:",
        SHARE_ON: "क माध्यम सं साझा करू",
        CLICK_OPTION_TO_SHARE: "अपन नेटवर्कक संग साझा करबाक लेल विकल्प चुनू।"
    },
    মৈতৈলোন: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "সরকারগী থৌরম পুম্নমক অমত্তা ওইবা পোর্টালদা ফংবীয়ু",
        INPUT_PLACEHOLDER: "বিভাগ নত্রগা মমিং থিদুনা খঙবীয়ু...",
        SEARCH: "থিবা হৌগদবনি",
        PAGE: "হৌজিক লৈরিবা লমাই",
        OF: "গী",
        SOURCE: "অরিজিনেল সোর্স ডকুমেন্ট উবা",
        NO_ANNOUNCEMENTS_FOUND: "অদোম্না থিবা অদুগা চান্নবা পাউ ফংদ্রে।",
        SEE_DETAILS: "মপুং ফানা উবা",
        DISCOVER_MORE: "হেন্না খঙবীয়ু",
        INDIAN_ANNOUNCEMENTS: "ভারত সরকারগী ওফিসিএল পাউশিং",
        SEE_MORE: "হেন্না পাউ উবা",
        VIEW_ALL: "পুম্নমক উবা",
        VIEW_DETAILS: "অকুপ্পা মরোল",
        DESCRIPTION: "ঐখোয়গী পোর্টাল অসিনা ভারত সরকার অমসুং রাজ্য সরকারগী পাউ পুম্নমক খোমগৎতুনা অদোমগী লোলদা হন্দোকপীরি।",
        SEE_ANNOUNCEMENTS: "পাউ পুম্নমক উবা",
        LOAD_MORE: "মখা তানা উবা",
        SOMETHING_WENT_WRONG: "পাউ খোমগৎপদা অশোয়বা অমা লাক্লে।",
        SUBSCRIBE_TO_ALERTS: "পাউ ফংনবগীদমক সবস্ক্রাইব তৌবীয়ু",
        NEVER_MISS_AN_UPDATE: "অনৌবা পাউ পুম্নমক ইমেলদা ফংবীয়ু।",
        SUBSCRIBE: "সবস্ক্রাইব তৌবা",
        ENTER_YOUR_EMAIL: "ইমেল ইবীয়ু",
        PLEASE_ENTER_YOUR_EMAIL: "অচুম্বা ইমেল অমা ইবীয়ু।",
        PLEASE_ENTER_A_VALID_EMAIL: "ইমেল অসি অশোয়বা লৈ।",
        SUCCESSFULLY_SUBSCRIBED: "সবস্ক্রাইব তৌবা মায় পাক্লে।",
        FAILED_TO_SUBSCRIBE: "সবস্ক্রাইব তৌবদা অশোয়বা লাক্লে।",
        SHARE_ANNOUNCEMENT: "শেয়ার তৌবীয়ু",
        HELP_OTHERS_DISCOVER: "অতোপ্পদসু পাউ অসি খঙহনবীয়ু।",
        CHECK_OUT_THIS_AMAZING: "পাউ অসি অদোমগীদমক কান্নগনি খল্লি:",
        SHARE_ON: "না শেয়ার তৌবা",
        CLICK_OPTION_TO_SHARE: "শেয়ার তৌনবগীদমক মথক্কী অপসন অসি খনবীয়ু।"
    },
    नेपाली: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "सबै आधिकारिक सरकारी घोषणाहरू अब एउटै पोर्टलमा उपलब्ध",
        INPUT_PLACEHOLDER: "कीवर्ड, विभाग वा शीर्षक अनुसार खोज्नुहोस्...",
        SEARCH: "अहिले खोज्नुहोस्",
        PAGE: "वर्तमान पृष्ठ",
        OF: "को",
        SOURCE: "मूल आधिकारिक कागजात हेर्नुहोस्",
        NO_ANNOUNCEMENTS_FOUND: "तपाईंको खोज अनुसार कुनै घोषणा फेला परेन।",
        SEE_DETAILS: "पूर्ण विवरण हेर्नुहोस्",
        DISCOVER_MORE: "थप जानकारी प्राप्त गर्नुहोस्",
        INDIAN_ANNOUNCEMENTS: "आधिकारिक भारतीय सरकारी घोषणाहरू",
        SEE_MORE: "थप अपडेटहरू हेर्नुहोस्",
        VIEW_ALL: "सबै सूचनाहरू हेर्नुहोस्",
        VIEW_DETAILS: "विस्तृत जानकारी",
        DESCRIPTION: "हाम्रो प्लेटफर्मले भारतका सबै राज्य र केन्द्रीय विभागहरूबाट सरकारी सूचनाहरू संकलन गर्दछ र तपाईंको स्थानीय भाषामा अनुवाद प्रदान गर्दछ।",
        SEE_ANNOUNCEMENTS: "सबै घोषणाहरू ब्राउज गर्नुहोस्",
        LOAD_MORE: "थप अपडेटहरू लोड गर्नुहोस्",
        SOMETHING_WENT_WRONG: "डाटा प्राप्त गर्दा समस्या भयो। कृपया पछि प्रयास गर्नुहोस्।",
        SUBSCRIBE_TO_ALERTS: "सूचनाहरूको लागि सबस्क्राइब गर्नुहोस्",
        NEVER_MISS_AN_UPDATE: "नीति परिवर्तनहरू बारे सधैं अपडेट रहनुहोस्। साप्ताहिक अलर्टहरू प्राप्त गर्नुहोस्।",
        SUBSCRIBE: "अहिले सबस्क्राइब गर्नुहोस्",
        ENTER_YOUR_EMAIL: "आफ्नो ईमेल ठेगाना लेख्नुहोस्",
        PLEASE_ENTER_YOUR_EMAIL: "जारी राख्नको लागि सही ईमेल दिनुहोस्।",
        PLEASE_ENTER_A_VALID_EMAIL: "ईमेलको ढाँचा गलत छ।",
        SUCCESSFULLY_SUBSCRIBED: "तपाईं सफलतापूर्वक सबस्क्राइब हुनुभएको छ।",
        FAILED_TO_SUBSCRIBE: "सबस्क्राइब गर्दा समस्या भयो। कनेक्सन चेक गर्नुहोस्।",
        SHARE_ANNOUNCEMENT: "यो महत्त्वपूर्ण घोषणा साझा गर्नुहोस्",
        HELP_OTHERS_DISCOVER: "अरूलाई पनि सरकारी समाचारहरूसँग अपडेट रहन मद्दत गर्नुहोस्।",
        CHECK_OUT_THIS_AMAZING: "मलाई लाग्छ यो घोषणा तपाईंको लागि उपयोगी हुन सक्छ:",
        SHARE_ON: "मार्फत साझा गर्नुहोस्",
        CLICK_OPTION_TO_SHARE: "आफ्नो नेटवर्कसँग साझा गर्न माथिको विकल्प रोज्नुहोस्।"
    },
    ଓଡ଼ିଆ: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "ସମସ୍ତ ସରକାରୀ ଘୋଷଣା ଏବେ ଗୋଟିଏ ପୋର୍ଟାଲରେ ଉପଲବ୍ଧ",
        INPUT_PLACEHOLDER: "ବିଭାଗ କିମ୍ବା ଶୀର୍ଷକ ଅନୁଯାୟୀ ଖୋଜନ୍ତୁ...",
        SEARCH: "ଏବେ ଖୋଜନ୍ତୁ",
        PAGE: "ବର୍ତ୍ତମାନ ପୃଷ୍ଠା",
        OF: "ର",
        SOURCE: "ମୂଳ ସରକାରୀ ଦସ୍ତାବିଜ ଦେଖନ୍ତୁ",
        NO_ANNOUNCEMENTS_FOUND: "ଆପଣଙ୍କ ସନ୍ଧାନ ଅନୁଯାୟୀ କୌଣସି ସୂଚନା ମିଳିଲା ନାହିଁ।",
        SEE_DETAILS: "ସମ୍ପୂର୍ଣ୍ଣ ବିବରଣୀ ଦେଖନ୍ତୁ",
        DISCOVER_MORE: "ଅଧିକ ଜାଣନ୍ତୁ",
        INDIAN_ANNOUNCEMENTS: "ଅଧିକାରୀକ ଭାରତୀୟ ସରକାରୀ ଘୋଷଣା",
        SEE_MORE: "ଅଧିକ ଅପଡେଟ ଦେଖନ୍ତୁ",
        VIEW_ALL: "ସମସ୍ତ ସୂଚନା ଦେଖନ୍ତୁ",
        VIEW_DETAILS: "ବିସ୍ତୃତ ସୂଚନା",
        DESCRIPTION: "ଆମର ପ୍ଲାଟଫର୍ମ ଭାରତର ସମସ୍ତ ରାଜ୍ୟ ଓ କେନ୍ଦ୍ରୀୟ ବିଭାଗରୁ ସରକାରୀ ସୂଚନା ସଂଗ୍ରହ କରି ଓଡ଼ିଆ ଭାଷାରେ ଅନୁବାଦ ପ୍ରଦାନ କରିଥାଏ।",
        SEE_ANNOUNCEMENTS: "ସମସ୍ତ ଘୋଷଣା ଦେଖନ୍ତୁ",
        LOAD_MORE: "ଅଧିକ ଲୋଡ୍ କରନ୍ତୁ",
        SOMETHING_WENT_WRONG: "ତଥ୍ୟ ସଂଗ୍ରହରେ କିଛି ତ୍ରୁଟି ହୋଇଛି। ପରେ ଚେଷ୍ଟା କରନ୍ତୁ।",
        SUBSCRIBE_TO_ALERTS: "ସୂଚନା ପାଇବା ପାଇଁ ସବସ୍କ୍ରାଇବ କରନ୍ତୁ",
        NEVER_MISS_AN_UPDATE: "ସରକାରୀ ନିୟମ ପରିବର୍ତ୍ତନ ବିଷୟରେ ଜାણନ୍ତୁ। ସାପ୍ତାହିਕ ଅପଡੇଟ ପାଆନ୍ତୁ।",
        SUBSCRIBE: "ସବସ୍କ୍ରାଇବ କରନ୍ତୁ",
        ENTER_YOUR_EMAIL: "ଆପଣଙ୍କ ଇମେଲ ଦିଅନ୍ତୁ",
        PLEASE_ENTER_YOUR_EMAIL: "ଆଗକୁ ବଢିବା ପାଇଁ ସଠିକ ଇମେଲ ଦିଅନ୍ତୁ।",
        PLEASE_ENTER_A_VALID_EMAIL: "ଇମେଲ ଫର୍ମାଟ ଭୁଲ ଅଛି।",
        SUCCESSFULLY_SUBSCRIBED: "ସଫଳତାର ସହ ସବସ୍କ୍ରାଇବ ହୋଇଛି।",
        FAILED_TO_SUBSCRIBE: "ସବସ୍କ୍ରାଇବ କରିବାରେ ସମସ୍ୟା ହୋଇଛି।",
        SHARE_ANNOUNCEMENT: "ଏହି ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ସୂଚନାକୁ ଶେୟାର କରନ୍ତୁ",
        HELP_OTHERS_DISCOVER: "ଅନ୍ୟମାନଙ୍କୁ ସରକାରୀ ଖବର ସହ ଅପଡେଟ ରହିବାରे ସାହାଯ୍ୟ କରନ୍ତୁ।",
        CHECK_OUT_THIS_AMAZING: "ମୋତେ ଲାଗୁଛି ଏହି ସୂଚନା ଆପଣଙ୍କ ପାଇଁ ଉପଯୋଗୀ ହେବ:",
        SHARE_ON: "ମାଧ୍ୟମରେ ଶେୟାର କରନ୍ତୁ",
        CLICK_OPTION_TO_SHARE: "ଶେୟାର କରିବା ପାଇଁ ଉପର ବିକଳ୍ପ ବାଛନ୍ତୁ।"
    },
    ਪੰਜਾਬੀ: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "ਸਾਰੀਆਂ ਅਧਿਕਾਰਤ ਸਰਕਾਰੀ ਘੋਸ਼ਣਾਵਾਂ ਹੁਣ ਇੱਕੋ ਪੋਰਟਲ 'ਤੇ ਉਪਲਬਧ ਹਨ",
        INPUT_PLACEHOLDER: "ਵਿਭਾਗ ਜਾਂ ਸਿਰਲੇਖ ਅਨੁਸਾਰ ਖੋਜੋ...",
        SEARCH: "ਹੁਣੇ ਖੋਜੋ",
        PAGE: "ਮੌਜੂਦਾ ਪੰਨਾ",
        OF: "ਦਾ",
        SOURCE: "ਅਸਲੀ ਸਰਕਾਰੀ ਦਸਤਾਵੇਜ਼ ਦੇਖੋ",
        NO_ANNOUNCEMENTS_FOUND: "ਤੁਹਾਡੀ ਖੋਜ ਮੁਤਾਬਕ ਕੋਈ ਘੋਸ਼ਣਾ ਨਹੀਂ ਮਿਲੀ।",
        SEE_DETAILS: "ਪੂਰਾ ਵੇਰਵਾ ਦੇਖੋ",
        DISCOVER_MORE: "ਹੋਰ ਜਾਣਕਾਰੀ ਪ੍ਰਾਪਤ ਕਰੋ",
        INDIAN_ANNOUNCEMENTS: "ਅਧਿਕਾਰਤ ਭਾਰਤੀ ਸਰਕਾਰੀ ਘੋਸ਼ਣਾਵਾਂ",
        SEE_MORE: "ਹੋਰ ਅਪਡੇਟ ਦੇਖੋ",
        VIEW_ALL: "ਸਾਰੀਆਂ ਸੂਚਨਾਵਾਂ ਦੇਖੋ",
        VIEW_DETAILS: "ਵਿਸਤ੍ਰਿਤ ਜਾਣਕਾਰੀ",
        DESCRIPTION: "ਸਾਡਾ ਪਲੇਟਫਾਰਮ ਭਾਰਤ ਦੇ ਸਾਰੇ ਰਾਜਾਂ ਅਤੇ ਕੇਂਦਰੀ ਵਿਭਾਗਾਂ ਤੋਂ ਸਰਕਾਰੀ ਸੂਚਨਾਵਾਂ ਇਕੱਤਰ ਕਰਦਾ ਹੈ ਅਤੇ ਪੰਜਾਬੀ ਵਿੱਚ ਅਨੁਵਾਦ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ।",
        SEE_ANNOUNCEMENTS: "ਸਾਰੀਆਂ ਘੋਸ਼ਣਾਵਾਂ ਦੇਖੋ",
        LOAD_MORE: "ਹੋਰ ਅਪਡੇਟ ਲੋਡ ਕਰੋ",
        SOMETHING_WENT_WRONG: "ਡੇਟਾ ਲੋਡ ਕਰਨ ਵਿੱਚ ਕੋਈ ਗਲਤੀ ਹੋਈ ਹੈ।",
        SUBSCRIBE_TO_ALERTS: "ਅਲਰਟ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਸਬਸਕ੍ਰਾਈਬ ਕਰੋ",
        NEVER_MISS_AN_UPDATE: "ਸਰਕਾਰੀ ਨੀਤੀਆਂ ਵਿੱਚ ਬਦਲਾਅ ਬਾਰੇ ਜਾਣੂ ਰਹੋ। ਹਫਤਾਵਾਰੀ ਅਪਡੇਟ ਪ੍ਰਾਪਤ ਕਰੋ।",
        SUBSCRIBE: "ਹੁਣੇ ਸਬਸਕ੍ਰਾਈਬ ਕਰੋ",
        ENTER_YOUR_EMAIL: "ਆਪਣਾ ਈਮੇਲ ਪਤਾ ਲਿਖੋ",
        PLEASE_ENTER_YOUR_EMAIL: "ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਹੀ ਈਮੇਲ ਪ੍ਰਦਾਨ ਕਰੋ।",
        PLEASE_ENTER_A_VALID_EMAIL: "ਈਮੇਲ ਦਾ ਫਾਰਮੈਟ ਗਲਤ ਹੈ।",
        SUCCESSFULLY_SUBSCRIBED: "ਤੁਸੀਂ ਸਫਲਤਾਪੂਰਵਕ ਸਬਸਕ੍ਰਾਈਬ ਕਰ ਲਿਆ ਹੈ।",
        FAILED_TO_SUBSCRIBE: "ਸਬਸਕ੍ਰਾਈਬ ਕਰਨ ਵਿੱਚ ਕੋਈ ਸਮੱਸਿਆ ਆਈ ਹੈ।",
        SHARE_ANNOUNCEMENT: "ਇਸ ਜ਼ਰੂਰੀ ਘੋਸ਼ਣਾ ਨੂੰ ਸਾਂਝਾ ਕਰੋ",
        HELP_OTHERS_DISCOVER: "ਦੂਜਿਆਂ ਦੀ ਵੀ ਸਰਕਾਰੀ ਖਬਰਾਂ ਨਾਲ ਅਪਡੇਟ ਰਹਿਣ ਵਿੱਚ ਮਦਦ ਕਰੋ।",
        CHECK_OUT_THIS_AMAZING: "ਮੈਨੂੰ ਲੱਗਦਾ ਹੈ ਕਿ ਇਹ ਘੋਸ਼ਣਾ ਤੁਹਾਡੇ ਲਈ ਫਾਇਦੇਮੰਦ ਹੋ ਸਕਦੀ ਹੈ:",
        SHARE_ON: "ਦੇ ਰਾਹੀਂ ਸਾਂਝਾ ਕਰੋ",
        CLICK_OPTION_TO_SHARE: "ਸਾਂਝਾ ਕਰਨ ਲਈ ਉੱਪਰ ਦਿੱਤੇ ਵਿਕਲਪ ਚੁਣੋ।"
    },
    "संस्कृतम्": {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "सर्वे आधिकारिक-सर्वकारीय-उद्घोषाः अधुना एकस्मिन् एव स्थाले उपलभ्यन्ते",
        INPUT_PLACEHOLDER: "संकेतशब्दैः, विभागैः वा अन्वेषणं कुर्वन्तु...",
        SEARCH: "अधुना अन्वेषणम्",
        PAGE: "वर्तमान-पृष्ठम्",
        OF: "तः",
        SOURCE: "मूल-लेखपत्रं पश्यतु",
        NO_ANNOUNCEMENTS_FOUND: "भवतः अन्वेषणानुसारं किमपि न प्राप्तम्।",
        SEE_DETAILS: "पूर्णविवरणं पश्यतु",
        DISCOVER_MORE: "अधिकं ज्ञातुं",
        INDIAN_ANNOUNCEMENTS: "आधिकारिक-भारतीय-सर्वकारीय-उद्घोषाः",
        SEE_MORE: "अधिकम् अपडेट् पश्यतु",
        VIEW_ALL: "सर्वाः सूचनाः पश्यतु",
        VIEW_DETAILS: "विस्तृत-विवरणम्",
        DESCRIPTION: "अस्माकं मञ्चः भारतस्य सर्वेभ्यः राज्येभ्यः केन्द्रेभ्यः च सर्वकारीय-सूचनाः सङ्गृह्य भवतः भाषायाम् अनूद्य सरलीकरोति।",
        SEE_ANNOUNCEMENTS: "सर्वान् उद्घोषान् पश्यतु",
        LOAD_MORE: "अधिकम् अपडेट् लोड् कुर्वन्तु",
        SOMETHING_WENT_WRONG: "किमपि दोषं जातम्। पुनः प्रयासं कुर्वन्तु।",
        SUBSCRIBE_TO_ALERTS: "सूचनार्थं सदस्यतां गृह्णन्तु",
        NEVER_MISS_AN_UPDATE: "नूतनानां नियमानां ज्ञानं प्राप्नुवन्तु। ईमेल-माध्यमेन साप्ताहिक-सूचनाः प्राप्नुवन्तु।",
        SUBSCRIBE: "सदस्यतां गृह्णन्तु",
        ENTER_YOUR_EMAIL: "स्वस्य ईमेल-सङ्केतं लिखतु",
        PLEASE_ENTER_YOUR_EMAIL: "अग्रे गन्तुं समीचीनं ईमेल-सङ्केतं लिखतु।",
        PLEASE_ENTER_A_VALID_EMAIL: "ईमेल-प्रारूपं दोषपूर्णम् अस्ति।",
        SUCCESSFULLY_SUBSCRIBED: "भवन्तः सफलतया सदस्यतां गृहीतवन्तः।",
        FAILED_TO_SUBSCRIBE: "सदस्यताग्रहणे बाधा जाता।",
        SHARE_ANNOUNCEMENT: "इमां सूचनां साझां कुर्वन्तु",
        HELP_OTHERS_DISCOVER: "अन्येषां साहाय्यार्थं सर्वकारीय-वार्ताः प्रसारयन्तु।",
        CHECK_OUT_THIS_AMAZING: "अहं मन्ये इयं सर्वकारीय-सूचना भवतः उपयोगिनी भवेत्:",
        SHARE_ON: "माध्यमेन साझां कुर्वन्तु",
        CLICK_OPTION_TO_SHARE: "साझां कर्तुं उपरि विकल्पं चिनुत।"
    },
    "ᱥᱟᱱᱛᱟᱲᱤ": {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "ᱥᱟᱱᱟᱢ ᱥᱚᱨᱠᱟᱨᱤ ᱞᱟᱹᱭ ᱡᱟᱹᱦᱤᱨ ᱱᱤᱛᱚᱜ ᱢᱤᱫᱴᱟᱹᱝ ᱯᱳᱨᱴᱟᱞ ᱨᱮ",
        INPUT_PLACEHOLDER: "ᱛᱷᱚᱠ ᱟᱨᱵᱟᱝ ᱧᱩᱛᱩᱢ ᱛᱮ ᱥᱮᱸᱫᱽᱨᱟᱭ ᱢᱮ...",
        SEARCH: "ᱱᱤᱛᱚᱜ ᱥᱮᱸᱫᱽᱨᱟᱭ ᱢᱮ",
        PAGE: "ᱱᱤᱛᱚᱜᱟᱜ ᱥᱟᱦᱴᱟ",
        OF: "ᱨᱮᱭᱟᱜ",
        SOURCE: "ᱥᱚᱨᱠᱟᱨᱤ ᱥᱟᱠᱟᱢ ᱧᱮᱞ ᱢᱮ",
        NO_ANNOUNCEMENTS_FOUND: "ᱟᱢᱟᱜ ᱥᱮᱸᱫᱽᱨᱟ ᱞᱮᱠᱟᱛᱮ ᱡᱟᱦᱟᱸᱱ ᱠᱷᱚᱵᱚᱨ ᱵᱟᱝ ᱧᱟᱢ ᱞᱮᱱᱟ ᱾",
        SEE_DETAILS: "ᱯᱩᱨᱟᱹ ᱵᱤᱵᱽᱨᱚᱬ ᱧᱮᱞ ᱢᱮ",
        DISCOVER_MORE: "ᱵᱟᱹᱲᱛᱤ ᱡᱟᱱᱟᱢ ᱢᱮ",
        INDIAN_ANNOUNCEMENTS: "ᱵᱷᱟᱨᱚᱛ ᱥᱚᱨᱠᱟᱨᱟᱜ ᱞᱟᱹᱭ ᱡᱟᱹᱦᱤᱨ",
        SEE_MORE: "ᱵᱟᱹᱲᱛᱤ ᱧᱮᱞ ᱢᱮ",
        VIEW_ALL: "ᱡᱷᱚᱛᱚ ᱧᱮᱞ ᱢᱮ",
        VIEW_DETAILS: "ᱵᱤᱵᱽᱨᱚᱬ ᱛᱮᱭᱟᱨ",
        DESCRIPTION: "ᱟᱞᱮᱭᱟᱜ ᱯᱳᱨᱴᱟᱞ ᱫᱚ ᱵᱷᱟᱨᱚᱛ ᱨᱮᱱᱟᱜ ᱥᱟᱱᱟᱢ ᱯᱚᱱᱚᱛ ᱟᱨ ᱛᱟᱞᱢᱟ ᱵᱤᱵᱷᱟᱜᱽ ᱠᱷᱚᱱ ᱠᱷᱚᱵᱚᱨ ᱠᱚ ᱛᱩᱢᱟᱹᱞ ᱠᱟᱛᱮ ᱟᱢᱟᱜ ᱯᱟᱹᱨᱥᱤ ᱛᱮ ᱞᱟᱹᱭ ᱟᱢᱟ ᱾",
        SEE_ANNOUNCEMENTS: "ᱥᱟᱱᱟᱢ ᱞᱟᱹᱭ ᱡᱟᱹᱦᱤᱨ ᱧᱮᱞ ᱢᱮ",
        LOAD_MORE: "ᱵᱟᱹᱲᱛᱤ ᱞᱳᱰ ᱢᱮ",
        SOMETHING_WENT_WRONG: "ᱡᱟᱦᱟᱸᱱᱟᱜ ᱵᱟᱹᱲᱤᱡ ᱟᱠᱟᱱᱟ ᱾",
        SUBSCRIBE_TO_ALERTS: "ᱥᱟᱵᱽᱥᱠᱨᱟᱭᱤᱵᱽ ᱢᱮ",
        NEVER_MISS_AN_UPDATE: "ᱱᱟᱣᱟ ᱠᱷᱚᱵᱚᱨ ᱠᱚ ᱤᱢᱮᱞ ᱨᱮ ᱧᱟਮ ᱢᱮ ᱾",
        SUBSCRIBE: "ᱥᱟᱵᱽᱥᱠᱨᱟᱭᱤᱵᱽ",
        ENTER_YOUR_EMAIL: "ᱟᱢᱟᱜ ᱤᱢᱮᱞ ᱚᱞ ᱢᱮ",
        PLEASE_ENTER_YOUR_EMAIL: "ᱞᱟᱦᱟᱜ ᱞᱟᱹᱜᱤᱫ ᱥᱟᱹᱨᱤ ᱤᱢᱮᱞ ᱮᱢ ᱢᱮ ᱾",
        PLEASE_ENTER_A_VALID_EMAIL: "ᱤᱢᱮᱞ ᱵᱟᱹᱲᱤᱡ ᱜᱮᱭᱟ ᱾",
        SUCCESSFULLY_SUBSCRIBED: "ᱥᱟᱵᱽᱥᱠᱨᱟᱭᱤᱵᱽ ᱦᱩᱭ ᱮᱱᱟ ᱾",
        FAILED_TO_SUBSCRIBE: "ᱥᱟᱵᱽᱥᱠᱨᱟᱭᱤᱵᱽ ᱵᱟᱝ ᱦᱩᱭ ᱞᱮᱱᱟ ᱾",
        SHARE_ANNOUNCEMENT: "ᱦᱟᱹᱴᱤᱧ ᱢᱮ",
        HELP_OTHERS_DISCOVER: "ᱮᱴᱟᱜ ᱠᱚᱦᱚᱸ ᱥᱚᱨᱠᱟᱨᱤ ᱠᱷᱚᱵᱚᱨ ᱞᱟᱹᱭ ᱟᱠᱚ ᱢᱮ ᱾",
        CHECK_OUT_THIS_AMAZING: "ᱤᱧ ᱢᱚᱱᱮᱭᱟ ᱱᱚᱣᱟ ᱠᱷᱚᱵᱚᱨ ᱟᱢ ᱞᱟᱹᱜᱤᱫ ᱠᱟᱹᱢᱤ ᱨᱮ ᱞᱟᱜᱟᱜ-ᱟ:",
        SHARE_ON: "ᱛᱮ ᱦᱟᱹᱴᱤᱧ ᱢᱮ",
        CLICK_OPTION_TO_SHARE: "ᱦᱟᱹᱴᱤᱧ ᱞᱟᱹᱜᱤᱫ ᱪᱮᱛᱟᱱ ᱨᱮ ᱠᱞᱤਕ ᱢᱮ ᱾"
    },
    سنڌي: {
        ALL_GOVERNMENT_ANNOUNCEMENTS_IN_ONE_PLACE: "سڀ سرڪاري اعلان هاڻي هڪ پورٽل تي موجود آهن",
        INPUT_PLACEHOLDER: "عنوان يا شعبي جي نالي سان ڳوليو...",
        SEARCH: "هاڻي ڳوليو",
        PAGE: "موجوده صفحو",
        OF: "جو",
        SOURCE: "اصل سرڪاري دستاويز ڏسو",
        NO_ANNOUNCEMENTS_FOUND: "توهان جي ڳولا موجب ڪو اعلان نه مليو.",
        SEE_DETAILS: "مڪمل تفصيل ڏسو",
        DISCOVER_MORE: "وڌيڪ ڄاڻ حاصل ڪريو",
        INDIAN_ANNOUNCEMENTS: "سرڪاري هندستاني اعلان",
        SEE_MORE: "وڌيڪ اپڊيٽ ڏسو",
        VIEW_ALL: "سڀ نوٽيفڪيشن ڏسو",
        VIEW_DETAILS: "تفصيلي ڄاڻ",
        DESCRIPTION: "اسان جو پليٽ فارم هندستان جي سڀني رياستن ۽ مرڪزي شعبن مان سرڪاري اطلاع گڏ ڪري توهان جي ٻولي ۾ ترجمو ڪري ٿو.",
        SEE_ANNOUNCEMENTS: "سڀ اعلان ڏسو",
        LOAD_MORE: "وڌيڪ لوڊ ڪريو",
        SOMETHING_WENT_WRONG: "ڊيٽا حاصل ڪرڻ ۾ ڪا غلطي ٿي آهي.",
        SUBSCRIBE_TO_ALERTS: "الرٽس لاءِ سبسڪرائب ڪريو",
        NEVER_MISS_AN_UPDATE: "پاليسي تبديلين بابت باخبر رهو. هفتيوار الرٽس حاصل ڪريو.",
        SUBSCRIBE: "هاڻي سبسڪرائب ڪريو",
        ENTER_YOUR_EMAIL: "پنهنجو اي ميل پتو لکو",
        PLEASE_ENTER_YOUR_EMAIL: "جاري رکڻ لاءِ صحيح اي ميل لکو.",
        PLEASE_ENTER_A_VALID_EMAIL: "اي ميل فارميٽ غلط آهي.",
        SUCCESSFULLY_SUBSCRIBED: "توهان ڪاميابي سان سبسڪرائب ٿي ويا آهيو.",
        FAILED_TO_SUBSCRIBE: "سبسڪرائب ڪرڻ ۾ ڪا مشڪل پيش آئي آهي.",
        SHARE_ANNOUNCEMENT: "هي اهم اعلان شيئر ڪريو",
        HELP_OTHERS_DISCOVER: "ٻين جي مدد ڪريو ته جيئن اهي به باخبر رهن.",
        CHECK_OUT_THIS_AMAZING: "مون کي لڳي ٿو هي اعلان توهان لاءِ مفيد هوندو:",
        SHARE_ON: "ذريعي شيئر ڪريو",
        CLICK_OPTION_TO_SHARE: "شيئر ڪرڻ لاءِ مٿي ڏنل اختيار چونڊيو."
    }
};