export type TranslationKeys = {
    TITLE: string,
    DESCRIPTION: string,
    EXPLORE_ANNOUNCEMENTS: string,
    LATEST_ANNOUNCEMENTS: string,
    INPUT_PLACEHOLDER: string,
    SEARCH: string,
    SEE_DETAILS: string,
    LOAD_MORE: string,
    BACK: string,
    VIEW_MORE_ANNOUNCEMENTS: string,
    SHARE_ANNOUNCEMENT: string,
    HELP_OTHERS_DISCOVER: string,
    CHECK_OUT_THIS_AMAZING: string,
    SHARE_ON: string,
    SUBSCRIBE_TO_ALERTS: string,
    NEVER_MISS_AN_UPDATE: string,
    PLEASE_ENTER_YOUR_EMAIL: string,
    SUBSCRIBE: string,
    SOMETHING_WENT_WRONG: string,
    PLEASE_ENTER_A_VALID_EMAIL: string,
    SUCCESSFULLY_SUBSCRIBED: string,
    FAILED_TO_SUBSCRIBE: string,
    N0_ANNOUNCEMENTS_FOUND: string,
    VIEW_OFFICIAL_SOURCE: string,
    MORE_LIKE_THIS: string
};
//More Like this

export const TranslateText: Record<string, TranslationKeys> = {
    English: {
        TITLE: "Access All Official Government Announcements in One Unified Portal.",
        DESCRIPTION: "Breaks down complex government circulars into simple language. Access announcements from all ministries in your preferred language—text or audio. No bureaucratic jargon, just clarity.",
        EXPLORE_ANNOUNCEMENTS: "EXPLORE ANNOUNCEMENTS",
        LATEST_ANNOUNCEMENTS: "Latest Announcements",
        INPUT_PLACEHOLDER: "Search by keyword, department, or announcement title...",
        SEARCH: "SEARCH",
        SEE_DETAILS: "See Details",
        LOAD_MORE: "LOAD MORE ",
        BACK: "BACK",
        VIEW_MORE_ANNOUNCEMENTS: "View More Announcements",
        SHARE_ANNOUNCEMENT: "Share this Important Announcement",
        HELP_OTHERS_DISCOVER: "Spread the word and help your community stay updated with official government Annoucements.",
        CHECK_OUT_THIS_AMAZING: "Checkout this official government announcement useful:",
        SHARE_ON: "Share via",
        SUBSCRIBE_TO_ALERTS: "Subscribe to Notifications",
        NEVER_MISS_AN_UPDATE: "Stay informed with the latest policy changes and annoucements. Get Weekly announcements directly in your Mail.",
        PLEASE_ENTER_YOUR_EMAIL: "Please Enter Your email.",
        SUBSCRIBE: "SUBSCRIBE",
        SOMETHING_WENT_WRONG: "Something Went Wrong.",
        PLEASE_ENTER_A_VALID_EMAIL: "The email format is incorrect.",
        SUCCESSFULLY_SUBSCRIBED: "You have successfully subscribed .",
        FAILED_TO_SUBSCRIBE: "Failed to subscribe.",
        N0_ANNOUNCEMENTS_FOUND: "No Announcements Found",
        VIEW_OFFICIAL_SOURCE: "View Official Source",
        MORE_LIKE_THIS: "More Like This"
    },
    हिन्दी: {
        TITLE: "एक एकीकृत पोर्टल में सभी आधिकारिक सरकारी घोषणाओं तक पहुंचें।",
        DESCRIPTION: "जटिल सरकारी परिपत्रों को सरल भाषा में समझाता है। अपनी पसंदीदा भाषा में सभी मंत्रालयों की घोषणाएं प्राप्त करें—पाठ या ऑडियो। कोई नौकरशाही शब्दजाल नहीं, बस स्पष्टता।",
        EXPLORE_ANNOUNCEMENTS: "घोषणाएं देखें",
        LATEST_ANNOUNCEMENTS: "नवीनतम घोषणाएं",
        INPUT_PLACEHOLDER: "कीवर्ड, विभाग या घोषणा शीर्षक से खोजें...",
        SEARCH: "खोजें",
        SEE_DETAILS: "विवरण देखें",
        LOAD_MORE: "और देखें",
        BACK: "वापस",
        VIEW_MORE_ANNOUNCEMENTS: "अधिक घोषणाएं देखें",
        SHARE_ANNOUNCEMENT: "इस महत्वपूर्ण घोषणा को साझा करें",
        HELP_OTHERS_DISCOVER: "जानकारी फैलाएं और अपने समुदाय को आधिकारिक सरकारी घोषणाओं से अपडेट रहने में मदद करें।",
        CHECK_OUT_THIS_AMAZING: "इस उपयोगी आधिकारिक सरकारी घोषणा को देखें:",
        SHARE_ON: "इसके माध्यम से साझा करें",
        SUBSCRIBE_TO_ALERTS: "सूचनाओं की सदस्यता लें",
        NEVER_MISS_AN_UPDATE: "नवीनतम नीति परिवर्तनों और घोषणाओं से अपडेट रहें। साप्ताहिक घोषणाएं सीधे अपने मेल में प्राप्त करें।",
        PLEASE_ENTER_YOUR_EMAIL: "कृपया अपना ईमेल दर्ज करें।",
        SUBSCRIBE: "सदस्यता लें",
        SOMETHING_WENT_WRONG: "कुछ गलत हो गया।",
        PLEASE_ENTER_A_VALID_EMAIL: "ईमेल का प्रारूप गलत है।",
        SUCCESSFULLY_SUBSCRIBED: "आपने सफलतापूर्वक सदस्यता ले ली है।",
        FAILED_TO_SUBSCRIBE: "सदस्यता लेने में विफल।",
        N0_ANNOUNCEMENTS_FOUND: "कोई घोषणा नहीं मिली",
        VIEW_OFFICIAL_SOURCE: "आधिकारिक स्रोत देखें",
        MORE_LIKE_THIS: "इसी तरह के अन्य"
    },
    বাংলা: {
        TITLE: "একটি একীভূত পোর্টালে সমস্ত সরকারি ঘোষণা অ্যাক্সেস করুন।",
        DESCRIPTION: "জটিল সরকারি সার্কুলারগুলিকে সহজ ভাষায় ভেঙে দেয়। আপনার পছন্দের ভাষায় সমস্ত মন্ত্রণালয়ের ঘোষণা অ্যাক্সেস করুন—টেক্সট বা অডিও। কোনো আমলাতান্ত্রিক শব্দজাল নেই, শুধুমাত্র স্পষ্টতা।",
        EXPLORE_ANNOUNCEMENTS: "ঘোষণা দেখুন",
        LATEST_ANNOUNCEMENTS: "সর্বশেষ ঘোষণা",
        INPUT_PLACEHOLDER: "কীওয়ার্ড, বিভাগ বা ঘোষণার শিরোনাম দিয়ে অনুসন্ধান করুন...",
        SEARCH: "অনুসন্ধান করুন",
        SEE_DETAILS: "বিস্তারিত দেখুন",
        LOAD_MORE: "আরও দেখুন",
        BACK: "ফিরে যান",
        VIEW_MORE_ANNOUNCEMENTS: "আরও ঘোষণা দেখুন",
        SHARE_ANNOUNCEMENT: "এই গুরুত্বপূর্ণ ঘোষণা শেয়ার করুন",
        HELP_OTHERS_DISCOVER: "তথ্য ছড়িয়ে দিন এবং আপনার সম্প্রদায়কে সরকারি ঘোষণা সম্পর্কে আপডেট থাকতে সাহায্য করুন।",
        CHECK_OUT_THIS_AMAZING: "এই দরকারী সরকারি ঘোষণাটি দেখুন:",
        SHARE_ON: "এর মাধ্যমে শেয়ার করুন",
        SUBSCRIBE_TO_ALERTS: "বিজ্ঞপ্তির সদস্যতা নিন",
        NEVER_MISS_AN_UPDATE: "সর্বশেষ নীতি পরিবর্তন এবং ঘোষণা সম্পর্কে অবগত থাকুন। সাপ্তাহিক ঘোষণা সরাসরি আপনার মেইলে পান।",
        PLEASE_ENTER_YOUR_EMAIL: "অনুগ্রহ করে আপনার ইমেইল লিখুন।",
        SUBSCRIBE: "সদস্যতা নিন",
        SOMETHING_WENT_WRONG: "কিছু ভুল হয়েছে।",
        PLEASE_ENTER_A_VALID_EMAIL: "ইমেইলের বিন্যাস ভুল।",
        SUCCESSFULLY_SUBSCRIBED: "আপনি সফলভাবে সদস্যতা নিয়েছেন।",
        FAILED_TO_SUBSCRIBE: "সদস্যতা নিতে ব্যর্থ।",
        N0_ANNOUNCEMENTS_FOUND: "কোনো ঘোষণা পাওয়া যায়নি",
        VIEW_OFFICIAL_SOURCE: "অফিসিয়াল সোর্স দেখুন",
        MORE_LIKE_THIS: "এরকম আরও"
    },
    தமிழ்: {
        TITLE: "ஒரே ஒருங்கிணைந்த போர்ட்டலில் அனைத்து அதிகாரபூர்வ அரசு அறிவிப்புகளையும் அணுகவும்.",
        DESCRIPTION: "சிக்கலான அரசு சுற்றறிக்கைகளை எளிய மொழியில் விளக்குகிறது. உங்கள் விருப்பமான மொழியில் அனைத்து அமைச்சகங்களின் அறிவிப்புகளை அணுகவும்—உரை அல்லது ஆடியோ. அதிகாரத்துவ வாசகங்கள் இல்லை, தெளிவு மட்டுமே.",
        EXPLORE_ANNOUNCEMENTS: "அறிவிப்புகளைக் காண்க",
        LATEST_ANNOUNCEMENTS: "சமீபத்திய அறிவிப்புகள்",
        INPUT_PLACEHOLDER: "முக்கிய சொல், துறை அல்லது அறிவிப்பு தலைப்பு மூலம் தேடவும்...",
        SEARCH: "தேடவும்",
        SEE_DETAILS: "விவரங்களைக் காண்க",
        LOAD_MORE: "மேலும் காண்க",
        BACK: "திரும்பவும்",
        VIEW_MORE_ANNOUNCEMENTS: "மேலும் அறிவிப்புகளைக் காண்க",
        SHARE_ANNOUNCEMENT: "இந்த முக்கியமான அறிவிப்பைப் பகிரவும்",
        HELP_OTHERS_DISCOVER: "தகவலைப் பரப்பி, உங்கள் சமூகம் அதிகாரபூர்வ அரசு அறிவிப்புகளுடன் புதுப்பிக்கப்படுவதற்கு உதவவும்.",
        CHECK_OUT_THIS_AMAZING: "இந்த பயனுள்ள அதிகாரபூர்வ அரசு அறிவிப்பைப் பார்க்கவும்:",
        SHARE_ON: "இதன் மூலம் பகிரவும்",
        SUBSCRIBE_TO_ALERTS: "அறிவிப்புகளுக்கு குழுசேரவும்",
        NEVER_MISS_AN_UPDATE: "சமீபத்திய கொள்கை மாற்றங்கள் மற்றும் அறிவிப்புகளுடன் புதுப்பித்த நிலையில் இருங்கள். வாராந்திர அறிவிப்புகளை நேரடியாக உங்கள் மின்னஞ்சலில் பெறுங்கள்.",
        PLEASE_ENTER_YOUR_EMAIL: "தயவுசெய்து உங்கள் மின்னஞ்சலை உள்ளிடவும்.",
        SUBSCRIBE: "குழுசேரவும்",
        SOMETHING_WENT_WRONG: "ஏதோ தவறு நடந்தது.",
        PLEASE_ENTER_A_VALID_EMAIL: "மின்னஞ்சல் வடிவம் தவறானது.",
        SUCCESSFULLY_SUBSCRIBED: "நீங்கள் வெற்றிகரமாக குழுசேர்ந்துள்ளீர்கள்.",
        FAILED_TO_SUBSCRIBE: "குழுசேர தோல்வியடைந்தது.",
        N0_ANNOUNCEMENTS_FOUND: "அறிவிப்புகள் எதுவும் கிடைக்கவில்லை",
        VIEW_OFFICIAL_SOURCE: "அதிகாரப்பூர்வ ஆதாரத்தைக் காண்க",
        MORE_LIKE_THIS: "இது போன்ற மேலும்"
    },
    తెలుగు: {
        TITLE: "ఒకే ఏకీకృత పోర్టల్‌లో అన్ని అధికారిక ప్రభుత్వ ప్రకటనలను యాక్సెస్ చేయండి.",
        DESCRIPTION: "సంక్లిష్టమైన ప్రభుత్వ సర్కులర్‌లను సరళమైన భాషలో విభజిస్తుంది. మీకు ఇష్టమైన భాషలో అన్ని మంత్రిత్వ శాఖల ప్రకటనలను యాక్సెస్ చేయండి—టెక్స్ట్ లేదా ఆడియో. బ్యూరోక్రాటిక్ పరిభాష లేదు, కేవలం స్పష్టత మాత్రమే.",
        EXPLORE_ANNOUNCEMENTS: "ప్రకటనలను అన్వేషించండి",
        LATEST_ANNOUNCEMENTS: "తాజా ప్రకటనలు",
        INPUT_PLACEHOLDER: "కీవర్డ్, విభాగం లేదా ప్రకటన శీర్షిక ద్వారా శోధించండి...",
        SEARCH: "శోధించండి",
        SEE_DETAILS: "వివరాలు చూడండి",
        LOAD_MORE: "మరిన్ని చూడండి",
        BACK: "వెనక్కి",
        VIEW_MORE_ANNOUNCEMENTS: "మరిన్ని ప్రకటనలను చూడండి",
        SHARE_ANNOUNCEMENT: "ఈ ముఖ్యమైన ప్రకటనను షేర్ చేయండి",
        HELP_OTHERS_DISCOVER: "సమాచారాన్ని వ్యాప్తి చేయండి మరియు మీ సమాజం అధికారిక ప్రభుత్వ ప్రకటనలతో అప్‌డేట్‌గా ఉండటానికి సహాయం చేయండి.",
        CHECK_OUT_THIS_AMAZING: "ఈ ఉపయోగకరమైన అధికారిక ప్రభుత్వ ప్రకటనను చూడండి:",
        SHARE_ON: "దీని ద్వారా షేర్ చేయండి",
        SUBSCRIBE_TO_ALERTS: "నోటిఫికేషన్‌లకు సబ్‌స్క్రైబ్ చేయండి",
        NEVER_MISS_AN_UPDATE: "తాజా విధాన మార్పులు మరియు ప్రకటనలతో సమాచారంగా ఉండండి. వారానికొకసారి ప్రకటనలను నేరుగా మీ మెయిల్‌లో పొందండి.",
        PLEASE_ENTER_YOUR_EMAIL: "దయచేసి మీ ఇమెయిల్ నమోదు చేయండి.",
        SUBSCRIBE: "సబ్‌స్క్రైబ్ చేయండి",
        SOMETHING_WENT_WRONG: "ఏదో తప్పు జరిగింది.",
        PLEASE_ENTER_A_VALID_EMAIL: "ఇమెయిల్ ఫార్మాట్ తప్పు.",
        SUCCESSFULLY_SUBSCRIBED: "మీరు విజయవంతంగా సబ్‌స్క్రైబ్ చేశారు.",
        FAILED_TO_SUBSCRIBE: "సబ్‌స్క్రైబ్ చేయడంలో విफल అయ్యారు.",
        N0_ANNOUNCEMENTS_FOUND: "ప్రకటనలు కనుగొనబడలేదు",
        VIEW_OFFICIAL_SOURCE: "అధికారిక మూలాన్ని చూడండి",
        MORE_LIKE_THIS: "ఇలాంటివి మరిన్ని"
    },
    മലയാളം: {
        TITLE: "ഒരൊറ്റ ഏകീകൃത പോർട്ടലിൽ എല്ലാ ഔദ്യോഗിക സർക്കാർ അറിയിപ്പുകളും ആക്സസ് ചെയ്യുക.",
        DESCRIPTION: "സങ്കീർണ്ണമായ സർക്കാർ സർക്കുലറുകളെ ലളിതമായ ഭാഷയിലേക്ക് വിഭജിക്കുന്നു. നിങ്ങളുടെ ഇഷ്ട ഭാഷയിൽ എല്ലാ മന്ത്രാലയങ്ങളിൽ നിന്നുമുള്ള അറിയിപ്പുകൾ ആക്സസ് ചെയ്യുക—ടെക്സ്റ്റ് അല്ലെങ്കിൽ ഓഡിയോ. ബ്യൂറോക്രാറ്റിക് പദപ്രയോഗങ്ങളില്ല, വ്യക്തത മാത്രം.",
        EXPLORE_ANNOUNCEMENTS: "അറിയിപ്പുകൾ പര്യവേക്ഷണം ചെയ്യുക",
        LATEST_ANNOUNCEMENTS: "ഏറ്റവും പുതിയ അറിയിപ്പുകൾ",
        INPUT_PLACEHOLDER: "കീവേഡ്, വകുപ്പ് അല്ലെങ്കിൽ അറിയിപ്പ് ശീർഷകം ഉപയോഗിച്ച് തിരയുക...",
        SEARCH: "തിരയുക",
        SEE_DETAILS: "വിശദാംശങ്ങൾ കാണുക",
        LOAD_MORE: "കൂടുതൽ കാണുക",
        BACK: "തിരികെ",
        VIEW_MORE_ANNOUNCEMENTS: "കൂടുതൽ അറിയിപ്പുകൾ കാണുക",
        SHARE_ANNOUNCEMENT: "ഈ പ്രധാനപ്പെട്ട അറിയിപ്പ് പങ്കിടുക",
        HELP_OTHERS_DISCOVER: "വിവരങ്ങൾ പ്രചരിപ്പിക്കുകയും നിങ്ങളുടെ സമൂഹം ഔദ്യോഗിക സർക്കാർ അറിയിപ്പുകളുമായി അപ്ഡേറ്റായി തുടരാൻ സഹായിക്കുകയും ചെയ്യുക.",
        CHECK_OUT_THIS_AMAZING: "ഈ ഉപയോഗപ്രദമായ ഔദ്യോഗിക സർക്കാർ അറിയിപ്പ് കാണുക:",
        SHARE_ON: "ഇതിലൂടെ പങ്കിടുക",
        SUBSCRIBE_TO_ALERTS: "അറിയിപ്പുകൾക്കായി സബ്സ്ക്രൈബ് ചെയ്യുക",
        NEVER_MISS_AN_UPDATE: "ഏറ്റവും പുതിയ നയ മാറ്റങ്ങളും അറിയിപ്പുകളും അറിഞ്ഞിരിക്കുക. പ്രതിവാര അറിയിപ്പുകൾ നേരിട്ട് നിങ്ങളുടെ മെയിലിൽ നേടുക.",
        PLEASE_ENTER_YOUR_EMAIL: "ദയവായി നിങ്ങളുടെ ഇമെയിൽ നൽകുക.",
        SUBSCRIBE: "സബ്സ്ക്രൈബ് ചെയ്യുക",
        SOMETHING_WENT_WRONG: "എന്തോ തെറ്റ് സംഭവിച്ചു.",
        PLEASE_ENTER_A_VALID_EMAIL: "ഇമെയിൽ ഫോർമാറ്റ് തെറ്റാണ്.",
        SUCCESSFULLY_SUBSCRIBED: "നിങ്ങൾ വിജയകരമായി സബ്സ്ക്രൈബ് ചെയ്തു.",
        FAILED_TO_SUBSCRIBE: "സബ്സ്ക്രൈബ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു.",
        N0_ANNOUNCEMENTS_FOUND: "അറിയിപ്പുകളൊന്നും കണ്ടെത്തിയില്ല",
        VIEW_OFFICIAL_SOURCE: "ഔദ്യോഗിക ഉറവിടം കാണുക",
        MORE_LIKE_THIS: "ഇതുപോലെ കൂടുതൽ"
    },
    मराठी: {
        TITLE: "एका एकीकृत पोर्टलमध्ये सर्व अधिकृत सरकारी घोषणांमध्ये प्रवेश मिळवा.",
        DESCRIPTION: "जटिल सरकारी परिपत्रकांना सोप्या भाषेत मोडते. आपल्या पसंतीच्या भाषेत सर्व मंत्रालयांच्या घोषणांमध्ये प्रवेश मिळवा—मजकूर किंवा ऑडिओ. नोकरशाही शब्दजाल नाही, फक्त स्पष्टता.",
        EXPLORE_ANNOUNCEMENTS: "घोषणा पहा",
        LATEST_ANNOUNCEMENTS: "नवीनतम घोषणा",
        INPUT_PLACEHOLDER: "कीवर्ड, विभाग किंवा घोषणा शीर्षकानुसार शोधा...",
        SEARCH: "शोधा",
        SEE_DETAILS: "तपशील पहा",
        LOAD_MORE: "अधिक पहा",
        BACK: "मागे",
        VIEW_MORE_ANNOUNCEMENTS: "अधिक घोषणा पहा",
        SHARE_ANNOUNCEMENT: "ही महत्त्वाची घोषणा शेअर करा",
        HELP_OTHERS_DISCOVER: "माहिती पसरवा आणि आपल्या समुदायाला अधिकृत सरकारी घोषणांसह अद्ययावत राहण्यास मदत करा.",
        CHECK_OUT_THIS_AMAZING: "ही उपयुक्त अधिकृत सरकारी घोषणा पहा:",
        SHARE_ON: "याद्वारे शेअर करा",
        SUBSCRIBE_TO_ALERTS: "सूचनांसाठी सदस्यता घ्या",
        NEVER_MISS_AN_UPDATE: "नवीनतम धोरण बदल आणि घोषणांसह माहिती ठेवा. साप्ताहिक घोषणा थेट आपल्या मेलमध्ये मिळवा.",
        PLEASE_ENTER_YOUR_EMAIL: "कृपया आपला ईमेल प्रविष्ट करा.",
        SUBSCRIBE: "सदस्यता घ्या",
        SOMETHING_WENT_WRONG: "काहीतरी चूक झाली.",
        PLEASE_ENTER_A_VALID_EMAIL: "ईमेल स्वरूप चुकीचे आहे.",
        SUCCESSFULLY_SUBSCRIBED: "आपण यशस्वीरित्या सदस्यता घेतली आहे.",
        FAILED_TO_SUBSCRIBE: "सदस्यता घेण्यात अयशस्वी.",
        N0_ANNOUNCEMENTS_FOUND: "कोणतीही घोषणा सापडली नाही",
        VIEW_OFFICIAL_SOURCE: "अधिकृत स्रोत पहा",
        MORE_LIKE_THIS: "यासारखे अधिक"
    },
    ગુજરાતી: {
        TITLE: "એક એકીકૃત પોર્ટલમાં તમામ અધિકૃત સરકારી જાહેરાતોને ઍક્સેસ કરો.",
        DESCRIPTION: "જટિલ સરકારી પરિપત્રોને સરળ ભાષામાં વિભાજિત કરે છે. તમારી પસંદગીની ભાષામાં તમામ મંત્રાલયોની જાહેરાતો ઍક્સેસ કરો—ટેક્સ્ટ અથવા ઑડિયો. કોઈ અમલદારશાહી શબ્દજાળ નહીં, માત્ર સ્પષ્ટતા.",
        EXPLORE_ANNOUNCEMENTS: "જાહેરાતો જુઓ",
        LATEST_ANNOUNCEMENTS: "તાજેતરની જાહેરાતો",
        INPUT_PLACEHOLDER: "કીવર્ડ, વિભાગ અથવા જાહેરાત શીર્ષક દ્વારા શોધો...",
        SEARCH: "શોધો",
        SEE_DETAILS: "વિગતો જુઓ",
        LOAD_MORE: "વધુ જુઓ",
        BACK: "પાછળ",
        VIEW_MORE_ANNOUNCEMENTS: "વધુ જાહેરાતો જુઓ",
        SHARE_ANNOUNCEMENT: "આ મહત્વપૂર્ણ જાહેરાત શેર કરો",
        HELP_OTHERS_DISCOVER: "માહિતી ફેલાવો અને તમારા સમુદાયને અધિકૃત સરકારી જાહેરાતો સાથે અપડેટ રહેવામાં મદદ કરો.",
        CHECK_OUT_THIS_AMAZING: "આ ઉપયોગી અધિકૃત સરકારી જાહેરાત જુઓ:",
        SHARE_ON: "આના દ્વારા શેર કરો",
        SUBSCRIBE_TO_ALERTS: "સૂચનાઓ માટે સબ્સ્ક્રાઇબ કરો",
        NEVER_MISS_AN_UPDATE: "તાજેતરના નીતિ ફેરફારો અને જાહેરાતો સાથે માહિતગાર રહો. સાપ્તાહિક જાહેરાતો સીધી તમારા મેલમાં મેળવો.",
        PLEASE_ENTER_YOUR_EMAIL: "કૃપા કરીને તમારું ઇમેઇલ દાખલ કરો.",
        SUBSCRIBE: "સબ્સ્ક્રાઇબ કરો",
        SOMETHING_WENT_WRONG: "કંઈક ખોટું થયું.",
        PLEASE_ENTER_A_VALID_EMAIL: "ઇમેઇલ ફોર્મેટ ખોટું છે.",
        SUCCESSFULLY_SUBSCRIBED: "તમે સફળતાપૂર્વક સબ્સ્ક્રાઇબ કર્યું છે.",
        FAILED_TO_SUBSCRIBE: "સબ્સ્ક્રાઇબ કરવામાં નિષ્ફળ.",
        N0_ANNOUNCEMENTS_FOUND: "કોઈ જાહેરાત મળી નથી",
        VIEW_OFFICIAL_SOURCE: "અધિકૃત સ્રોત જુઓ",
        MORE_LIKE_THIS: "આવા વધુ"
    },
    ಕನ್ನಡ: {
        TITLE: "ಒಂದೇ ಏಕೀಕೃತ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಎಲ್ಲಾ ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಪ್ರಕಟಣೆಗಳನ್ನು ಪ್ರವೇಶಿಸಿ.",
        DESCRIPTION: "ಸಂಕೀರ್ಣ ಸರ್ಕಾರಿ ಸರ್ಕ್ಯುಲರ್‌ಗಳನ್ನು ಸರಳ ಭಾಷೆಯಲ್ಲಿ ವಿಭಜಿಸುತ್ತದೆ. ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯಲ್ಲಿ ಎಲ್ಲಾ ಸಚಿವಾಲಯಗಳ ಪ್ರಕಟಣೆಗಳನ್ನು ಪ್ರವೇಶಿಸಿ—ಪಠ್ಯ ಅಥವಾ ಆಡಿಯೋ. ಯಾವುದೇ ಅಧಿಕಾರಶಾಹಿ ಪರಿಭಾಷೆ ಇಲ್ಲ, ಕೇವಲ ಸ್ಪಷ್ಟತೆ.",
        EXPLORE_ANNOUNCEMENTS: "ಪ್ರಕಟಣೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
        LATEST_ANNOUNCEMENTS: "ಇತ್ತೀಚಿನ ಪ್ರಕಟಣೆಗಳು",
        INPUT_PLACEHOLDER: "ಕೀವರ್ಡ್, ಇಲಾಖೆ ಅಥವಾ ಪ್ರಕಟಣೆ ಶೀರ್ಷಿಕೆಯಿಂದ ಹುಡುಕಿ...",
        SEARCH: "ಹುಡುಕಿ",
        SEE_DETAILS: "ವಿವರಗಳನ್ನು ನೋಡಿ",
        LOAD_MORE: "ಇನ್ನಷ್ಟು ನೋಡಿ",
        BACK: "ಹಿಂದೆ",
        VIEW_MORE_ANNOUNCEMENTS: "ಹೆಚ್ಚಿನ ಪ್ರಕಟಣೆಗಳನ್ನು ನೋಡಿ",
        SHARE_ANNOUNCEMENT: "ಈ ಪ್ರಮುಖ ಪ್ರಕಟಣೆಯನ್ನು ಹಂಚಿಕೊಳ್ಳಿ",
        HELP_OTHERS_DISCOVER: "ಮಾಹಿತಿಯನ್ನು ಹರಡಿ ಮತ್ತು ನಿಮ್ಮ ಸಮುದಾಯವು ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಪ್ರಕಟಣೆಗಳೊಂದಿಗೆ ನವೀಕೃತವಾಗಿರಲು ಸಹಾಯ ಮಾಡಿ.",
        CHECK_OUT_THIS_AMAZING: "ಈ ಉಪಯುಕ್ತ ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಪ್ರಕಟಣೆಯನ್ನು ನೋಡಿ:",
        SHARE_ON: "ಇದರ ಮೂಲಕ ಹಂಚಿಕೊಳ್ಳಿ",
        SUBSCRIBE_TO_ALERTS: "ಅಧಿಸೂಚನೆಗಳಿಗೆ ಚಂದಾದಾರರಾಗಿ",
        NEVER_MISS_AN_UPDATE: "ಇತ್ತೀಚಿನ ನೀತಿ ಬದಲಾವಣೆಗಳು ಮತ್ತು ಪ್ರಕಟಣೆಗಳೊಂದಿಗೆ ತಿಳುವಳಿಕೆಯುಳ್ಳವರಾಗಿರಿ. ಸಾಪ್ತಾಹಿಕ ಪ್ರಕಟಣೆಗಳನ್ನು ನೇರವಾಗಿ ನಿಮ್ಮ ಮೇಲ್‌ನಲ್ಲಿ ಪಡೆಯಿರಿ.",
        PLEASE_ENTER_YOUR_EMAIL: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ.",
        SUBSCRIBE: "ಚಂದಾದಾರರಾಗಿ",
        SOMETHING_WENT_WRONG: "ಏನೋ ತಪ್ಪಾಗಿದೆ.",
        PLEASE_ENTER_A_VALID_EMAIL: "ಇಮೇಲ್ ಸ್ವರೂಪ ತಪ್ಪಾಗಿದೆ.",
        SUCCESSFULLY_SUBSCRIBED: "ನೀವು ಯಶಸ್ವಿಯಾಗಿ ಚಂದಾದಾರರಾಗಿದ್ದೀರಿ.",
        FAILED_TO_SUBSCRIBE: "ಚಂದಾದಾರರಾಗಲು ವಿಫಲವಾಗಿದೆ.",
        N0_ANNOUNCEMENTS_FOUND: "ಯಾವುದೇ ಪ್ರಕಟಣೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
        VIEW_OFFICIAL_SOURCE: "ಅಧಿಕೃತ ಮೂಲವನ್ನು ನೋಡಿ",
        MORE_LIKE_THIS: "ಈ ರೀತಿಯ ಇನ್ನಷ್ಟು"
    },
    اردو: {
        TITLE: "ایک متحدہ پورٹل میں تمام سرکاری اعلانات تک رسائی حاصل کریں۔",
        DESCRIPTION: "پیچیدہ سرکاری سرکلرز کو آسان زبان میں تقسیم کرتا ہے۔ اپنی پسندیدہ زبان میں تمام وزارتوں کے اعلانات تک رسائی حاصل کریں—متن یا آڈیو۔ کوئی بیوروکریٹک اصطلاحات نہیں، صرف وضاحت۔",
        EXPLORE_ANNOUNCEMENTS: "اعلانات دیکھیں",
        LATEST_ANNOUNCEMENTS: "تازہ ترین اعلانات",
        INPUT_PLACEHOLDER: "مطلوبہ الفاظ، محکمہ یا اعلان کے عنوان سے تلاش کریں...",
        SEARCH: "تلاش کریں",
        SEE_DETAILS: "تفصیلات دیکھیں",
        LOAD_MORE: "مزید دیکھیں",
        BACK: "واپس",
        VIEW_MORE_ANNOUNCEMENTS: "مزید اعلانات دیکھیں",
        SHARE_ANNOUNCEMENT: "اس اہم اعلان کو شیئر کریں",
        HELP_OTHERS_DISCOVER: "معلومات کو پھیلائیں اور اپنی کمیونٹی کو سرکاری اعلانات سے باخبر رہنے میں مدد کریں۔",
        CHECK_OUT_THIS_AMAZING: "یہ مفید سرکاری اعلان دیکھیں:",
        SHARE_ON: "اس کے ذریعے شیئر کریں",
        SUBSCRIBE_TO_ALERTS: "اطلاعات کی رکنیت لیں",
        NEVER_MISS_AN_UPDATE: "تازہ ترین پالیسی تبدیلیوں اور اعلانات سے باخبر رہیں۔ ہفتہ وار اعلانات براہ راست اپنے میل میں حاصل کریں۔",
        PLEASE_ENTER_YOUR_EMAIL: "براہ کرم اپنا ای میل درج کریں۔",
        SUBSCRIBE: "رکنیت لیں",
        SOMETHING_WENT_WRONG: "کچھ غلط ہو گیا۔",
        PLEASE_ENTER_A_VALID_EMAIL: "ای میل کی شکل غلط ہے۔",
        SUCCESSFULLY_SUBSCRIBED: "آپ نے کامیابی سے رکنیت لے لی ہے۔",
        FAILED_TO_SUBSCRIBE: "رکنیت لینے میں ناکام۔",
        N0_ANNOUNCEMENTS_FOUND: "کوئی اعلان نہیں ملا",
        VIEW_OFFICIAL_SOURCE: "سرکاری ذریعہ دیکھیں",
        MORE_LIKE_THIS: "اس طرح کے مزید"
    },
    অসমীয়া: {
        TITLE: "এটা একীভূত পৰ্টেলত সকলো চৰকাৰী ঘোষণা প্ৰৱেশ কৰক।",
        DESCRIPTION: "জটিল চৰকাৰী পৰিপত্ৰসমূহক সৰল ভাষালৈ বিভক্ত কৰে। আপোনাৰ পছন্দৰ ভাষাত সকলো মন্ত্ৰালয়ৰ ঘোষণা প্ৰৱেশ কৰক—পাঠ বা অডিঅ'। কোনো আমোলাতান্ত্ৰিক শব্দজাল নাই, কেৱল স্পষ্টতা।",
        EXPLORE_ANNOUNCEMENTS: "ঘোষণাসমূহ অন্বেষণ কৰক",
        LATEST_ANNOUNCEMENTS: "শেহতীয়া ঘোষণাসমূহ",
        INPUT_PLACEHOLDER: "কীৱৰ্ড, বিভাগ বা ঘোষণাৰ শীৰ্ষকৰ দ্বাৰা সন্ধান কৰক...",
        SEARCH: "সন্ধান কৰক",
        SEE_DETAILS: "বিৱৰণ চাওক",
        LOAD_MORE: "অধিক চাওক",
        BACK: "উভতি যাওক",
        VIEW_MORE_ANNOUNCEMENTS: "অধিক ঘোষণা চাওক",
        SHARE_ANNOUNCEMENT: "এই গুৰুত্বপূৰ্ণ ঘোষণা শ্বেয়াৰ কৰক",
        HELP_OTHERS_DISCOVER: "তথ্য বিস্তাৰ কৰক আৰু আপোনাৰ সমাজক চৰকাৰী ঘোষণাৰ সৈতে আপডেট থকাত সহায় কৰক।",
        CHECK_OUT_THIS_AMAZING: "এই উপযোগী চৰকাৰী ঘোষণা চাওক:",
        SHARE_ON: "ইয়াৰ জৰিয়তে শ্বেয়াৰ কৰক",
        SUBSCRIBE_TO_ALERTS: "জাননীৰ বাবে চাবস্ক্ৰাইব কৰক",
        NEVER_MISS_AN_UPDATE: "শেহতীয়া নীতি পৰিৱৰ্তন আৰু ঘোষণাৰ সৈতে তথ্য লাভ কৰক। সাপ্তাহিক ঘোষণা পোনপটীয়াকৈ আপোনাৰ মেইলত লাভ কৰক।",
        PLEASE_ENTER_YOUR_EMAIL: "অনুগ্ৰহ কৰি আপোনাৰ ইমেইল প্ৰৱিষ্ট কৰক।",
        SUBSCRIBE: "চাবস্ক্ৰাইব কৰক",
        SOMETHING_WENT_WRONG: "কিবা ভুল হৈছে।",
        PLEASE_ENTER_A_VALID_EMAIL: "ইমেইলৰ বিন্যাস ভুল।",
        SUCCESSFULLY_SUBSCRIBED: "আপুনি সফলতাৰে চাবস্ক্ৰাইব কৰিছে।",
        FAILED_TO_SUBSCRIBE: "চাবস্ক্ৰাইব কৰাত ব্যৰ্থ।",
        N0_ANNOUNCEMENTS_FOUND: "কোনো ঘোষণা পোৱা নগ'ল",
        VIEW_OFFICIAL_SOURCE: "চৰকাৰী উৎস চাওক",
        MORE_LIKE_THIS: "এনেকুৱা অধিক"
    },
    बर: {
        TITLE: "मोनसे एकीकृत पोर्टलआव गासै सरकारी फोसावनायफोरखौ मोननो हागोन।",
        DESCRIPTION: "जटिल सरकारी परिपत्रफोरखौ सोजों रावआव बिभाजन खालामनाय जादों। नोंथांनि मननाय रावआव गासै मन्त्रालयनि फोसावनायफोरखौ मोननो हागोन—लिरनाय एबा आवाजआव। जेबो नौकरशाही रावआ हाया, खालि सोजों जानाय।",
        EXPLORE_ANNOUNCEMENTS: "फोसावनायफोरखौ नाय",
        LATEST_ANNOUNCEMENTS: "गोदान फोसावनायफोर",
        INPUT_PLACEHOLDER: "मुं, बिफान एबा फोसावनायनि मुंजों नायगिर...",
        SEARCH: "नायगिर",
        SEE_DETAILS: "गासै फोरमायथि नाय",
        LOAD_MORE: "गोबां अपडेट नाय",
        BACK: "उनाव",
        VIEW_MORE_ANNOUNCEMENTS: "गोबां फोसावनायफोर नाय",
        SHARE_ANNOUNCEMENT: "बे गोजौनि फोसावनायखौ शेयर खालाम",
        HELP_OTHERS_DISCOVER: "फोरमाय बिस्तार खालाम आरो नोंथांनि समाजखौ सरकारी फोसावनायफोरजों अपडेट दंनो साहाय्य खालाम।",
        CHECK_OUT_THIS_AMAZING: "बे उपयोगि सरकारी फोसावनायखौ नाय:",
        SHARE_ON: "जोंआव शेयर खालाम",
        SUBSCRIBE_TO_ALERTS: "सूचनाफोरनि सबस्क्राइब खालाम",
        NEVER_MISS_AN_UPDATE: "गोदान नीतिनि सोलाय आरो फोसावनायफोरजों फोरमाय मोन। हाप्थायाव फोसावनायफोर सोजों नोंथांनि ईमेलआव मोन।",
        PLEASE_ENTER_YOUR_EMAIL: "मोजां नोंथांनि ईमेल लिर।",
        SUBSCRIBE: "सबस्क्राइब खालाम",
        SOMETHING_WENT_WRONG: "गोरोन्थि जादों।",
        PLEASE_ENTER_A_VALID_EMAIL: "ईमेलनि फरमेट गोरोन्थि जादों।",
        SUCCESSFULLY_SUBSCRIBED: "नों सफलताजों सबस्क्राइब खालामबाय।",
        FAILED_TO_SUBSCRIBE: "सबस्क्राइब खालामनाय जायाखै।",
        N0_ANNOUNCEMENTS_FOUND: "जेबो फोसावनाय मोनखायेनाय",
        VIEW_OFFICIAL_SOURCE: "सरकारी जायगा नाय",
        MORE_LIKE_THIS: "बेनि जाथाव गोबां"
    },
    डोगरी: {
        TITLE: "इक्क एकीकृत पोर्टल च सारे सरकारी घोषणाएं गी एक्सेस करो।",
        DESCRIPTION: "जटिल सरकारी सर्कुलरें गी सादी भाशा च तोड़दा ऐ। अपनी पसंद दी भाशा च सारे मंत्रालयें दी घोषणाएं गी एक्सेस करो—टेक्स्ट जां ऑडियो। कोई नौकरशाही शब्दजाल नेईं, सिर्फ स्पश्टता।",
        EXPLORE_ANNOUNCEMENTS: "घोषणाएं गी देखो",
        LATEST_ANNOUNCEMENTS: "ताजा घोषणाएं",
        INPUT_PLACEHOLDER: "कीवर्ड, विभाग जां घोषणा दे शीर्षक कन्नै तलाश करो...",
        SEARCH: "तलाश करो",
        SEE_DETAILS: "ब्यौरा देखो",
        LOAD_MORE: "होर देखो",
        BACK: "वापस",
        VIEW_MORE_ANNOUNCEMENTS: "होर घोषणाएं देखो",
        SHARE_ANNOUNCEMENT: "इस जरूरी घोषणा गी शेयर करो",
        HELP_OTHERS_DISCOVER: "जानकारी फैलाओ ते अपने समुदाय गी सरकारी घोषणाएं कन्नै अपडेट रौह्ने च मदद करो।",
        CHECK_OUT_THIS_AMAZING: "इस उपयोगी सरकारी घोषणा गी देखो:",
        SHARE_ON: "इसदे राएं शेयर करो",
        SUBSCRIBE_TO_ALERTS: "सूचनाएं दी सदस्यता लैओ",
        NEVER_MISS_AN_UPDATE: "ताजा नीति बदलावें ते घोषणाएं कन्नै जानकारी च रौह्ओ। हफ्तावार घोषणाएं सिद्धा अपने मेल च हासल करो।",
        PLEASE_ENTER_YOUR_EMAIL: "कृपया अपना ईमेल दर्ज करो।",
        SUBSCRIBE: "सदस्यता लैओ",
        SOMETHING_WENT_WRONG: "किश गलत होई गेआ।",
        PLEASE_ENTER_A_VALID_EMAIL: "ईमेल फॉर्मेट गलत ऐ।",
        SUCCESSFULLY_SUBSCRIBED: "तुसें सफलतापूर्वक सदस्यता लैई लई ऐ।",
        FAILED_TO_SUBSCRIBE: "सदस्यता लैने च असफल।",
        N0_ANNOUNCEMENTS_FOUND: "कोई घोषणा नेईं मिल्ली",
        VIEW_OFFICIAL_SOURCE: "सरकारी स्रोत देखो",
        MORE_LIKE_THIS: "इस चाल्ली दे होर"
    },
    कॉशुर: {
        TITLE: "أکھ اکیکرِت پورٹل منز تمام سرکأری اعلانن تک رسائی حأصل کرِو۔",
        DESCRIPTION: "پیچیدٕ سرکأری سرکلرن سادٕ زبانس منز توڑان چھُ۔ پنن پسندٕ کِس زبانس منز تمام وزارتن ہنٛد اعلانن تک رسائی حأصل کرِو—متن یا آڈیو۔ کانٛہہ نوکرشاہی اصطلاحات چھِ نہٕ، صرف وضاحت۔",
        EXPLORE_ANNOUNCEMENTS: "اعلانات وُچھِو",
        LATEST_ANNOUNCEMENTS: "تازٕ ترین اعلانات",
        INPUT_PLACEHOLDER: "کیورڈ، محکمہ یا اعلانک عنوان سٕتۍ تلاش کرِو...",
        SEARCH: "تلاش کرِو",
        SEE_DETAILS: "تفصیلات وُچھِو",
        LOAD_MORE: "مزید وُچھِو",
        BACK: "واپس",
        VIEW_MORE_ANNOUNCEMENTS: "مزید اعلانات وُچھِو",
        SHARE_ANNOUNCEMENT: "یہِ اہم اعلان شیئر کرِو",
        HELP_OTHERS_DISCOVER: "معلومات پھیلأیِو تہٕ پننہٕ برأدرس سرکأری اعلانن سٕتۍ اپڈیٹ روزنس منز مدد کرِو۔",
        CHECK_OUT_THIS_AMAZING: "یہِ فأیدہ مند سرکأری اعلان وُچھِو:",
        SHARE_ON: "أمیہ ذریعہ شیئر کرِو",
        SUBSCRIBE_TO_ALERTS: "اطلاعاتن ہنٛد رکنیت حأصل کرِو",
        NEVER_MISS_AN_UPDATE: "تازٕ ترین پالیسی تبدیلین تہٕ اعلانن سٕتۍ آگاہ روزِو۔ ہفتہ وار اعلانات براہ راست پننس میلس منز حأصل کرِو۔",
        PLEASE_ENTER_YOUR_EMAIL: "مہربأنی کٔرتھ پننۍ ای میل درج کرِو۔",
        SUBSCRIBE: "رکنیت حأصل کرِو",
        SOMETHING_WENT_WRONG: "کانٛہہ غلط گوٚ۔",
        PLEASE_ENTER_A_VALID_EMAIL: "ای میلُک فارمیٹ غلط چھُ۔",
        SUCCESSFULLY_SUBSCRIBED: "تۄہہ کأمیأبی سٕتۍ رکنیت حأصل کٔر۔",
        FAILED_TO_SUBSCRIBE: "رکنیت حأصل کرنس منز ناکام۔",
        N0_ANNOUNCEMENTS_FOUND: "کانٛہہ اعلان میلہٕ نہٕ",
        VIEW_OFFICIAL_SOURCE: "سرکأری ذٔریعہٕ وُچھِو",
        MORE_LIKE_THIS: "اتھ پٮٚٹھۍ مزید"
    },
    मैथिली: {
        TITLE: "एकटा एकीकृत पोर्टल मे सब सरकारी घोषणा सभ केँ एक्सेस करू।",
        DESCRIPTION: "जटिल सरकारी सर्कुलर सभ केँ सरल भाषा मे तोड़ैत अछि। अपन पसंद केर भाषा मे सब मंत्रालय सभक घोषणा सभ केँ एक्सेस करू—पाठ वा ऑडियो। कोनो नौकरशाही शब्दजाल नहि, मात्र स्पष्टता।",
        EXPLORE_ANNOUNCEMENTS: "घोषणा सभ देखू",
        LATEST_ANNOUNCEMENTS: "नवीनतम घोषणा सभ",
        INPUT_PLACEHOLDER: "कीवर्ड, विभाग वा घोषणाक शीर्षक सँ खोजू...",
        SEARCH: "खोजू",
        SEE_DETAILS: "विवरण देखू",
        LOAD_MORE: "आओर देखू",
        BACK: "पाछाँ",
        VIEW_MORE_ANNOUNCEMENTS: "आओर घोषणा सभ देखू",
        SHARE_ANNOUNCEMENT: "ई महत्वपूर्ण घोषणा केँ शेयर करू",
        HELP_OTHERS_DISCOVER: "जानकारी फैलाऊ आ अपन समुदाय केँ सरकारी घोषणा सभ सँ अपडेट रहबा मे मदद करू।",
        CHECK_OUT_THIS_AMAZING: "ई उपयोगी सरकारी घोषणा देखू:",
        SHARE_ON: "एहि द्वारा शेयर करू",
        SUBSCRIBE_TO_ALERTS: "सूचना सभक लेल सब्सक्राइब करू",
        NEVER_MISS_AN_UPDATE: "नवीनतम नीति परिवर्तन आ घोषणा सभ सँ सूचित रहू। साप्ताहिक घोषणा सभ सीधा अपन मेल मे प्राप्त करू।",
        PLEASE_ENTER_YOUR_EMAIL: "कृपया अपन ईमेल दर्ज करू।",
        SUBSCRIBE: "सब्सक्राइब करू",
        SOMETHING_WENT_WRONG: "किछु गलत भऽ गेल।",
        PLEASE_ENTER_A_VALID_EMAIL: "ईमेल फॉर्मेट गलत अछि।",
        SUCCESSFULLY_SUBSCRIBED: "अहाँ सफलतापूर्वक सब्सक्राइब कऽ लेलहुँ अछि।",
        FAILED_TO_SUBSCRIBE: "सब्सक्राइब करबा मे विफल।",
        N0_ANNOUNCEMENTS_FOUND: "कोनो घोषणा नहि भेटल",
        VIEW_OFFICIAL_SOURCE: "आधिकारिक स्रोत देखू",
        MORE_LIKE_THIS: "एहि जकाँ आओर"
    },
    মৈতৈলোন: {
        TITLE: "অমত্তা ইন্তেগ্রেতেদ পোর্তেলদা গবর্মেন্ত অনাউন্সমেন্ত পুম্নমক এক্সেস তৌবা।",
        DESCRIPTION: "কোম্প্লেক্স অসুম্বা গবর্মেন্তকী সর্কুলরশীং অদু অসেংবা লোনদা খাইদোক্লি। নখোয়গী পাম্বা লোনদা মিনিস্ত্রী পুম্নমকী অনাউন্সমেন্তশীং এক্সেস তৌ—তেক্সত নত্রগা অডিও। বিউরোক্রেতিক ওইবা ওয়াশীং লৈতে, ক্লেরিতি খক্তনি।",
        EXPLORE_ANNOUNCEMENTS: "অনাউন্সমেন্তশীং উবা",
        LATEST_ANNOUNCEMENTS: "অহান্বা অনাউন্সমেন্তশীং",
        INPUT_PLACEHOLDER: "কীওয়র্দ, দিপার্তমেন্ত নত্রগা অনাউন্সমেন্তকী হেদিংনা থীবিয়ু...",
        SEARCH: "থীবা",
        SEE_DETAILS: "দিতেইলশীং উবা",
        LOAD_MORE: "অমুক উবা",
        BACK: "হন্না",
        VIEW_MORE_ANNOUNCEMENTS: "অনাউন্সমেন্ত অমুক উবা",
        SHARE_ANNOUNCEMENT: "মরুওইবা অনাউন্সমেন্ত অসি শেয়র তৌবা",
        HELP_OTHERS_DISCOVER: "ইনফোর্মেসন খাইদোকপা অমসুং নখোয়গী কম্যুনিতিদা গবর্মেন্তকী অনাউন্সমেন্তশীংগা লোয়ননা অপদেত লৈবদা মতেং পাংবিয়ু।",
        CHECK_OUT_THIS_AMAZING: "মফম শীজিন্নরিবা গবর্মেন্তকী অনাউন্সমেন্ত অসি য়েংবিয়ু:",
        SHARE_ON: "মসিনা শেয়র তৌবা",
        SUBSCRIBE_TO_ALERTS: "নোতিফিকেসনশীংদা সবস্ক্রাইব তৌবা",
        NEVER_MISS_AN_UPDATE: "অহান্বা পোলিসী চেঞ্জশীং অমসুং অনাউন্সমেন্তশীংগা লোয়ননা ইনফোর্ম লৈয়ু। চাউখত্তা অনাউন্সমেন্তশীং নখোয়গী মেইলদা থৌগৎপা ফংবা।",
        PLEASE_ENTER_YOUR_EMAIL: "চানবিদুনা নখোয়গী ইমেইল হাল্লু।",
        SUBSCRIBE: "সবস্ক্রাইব তৌবা",
        SOMETHING_WENT_WRONG: "অমুক অরান্বা থোক্লক্লে।",
        PLEASE_ENTER_A_VALID_EMAIL: "ইমেইল ফোর্মেত অদু অরান্বনি।",
        SUCCESSFULLY_SUBSCRIBED: "নখোয়না মফম ফবা ওইনা সবস্ক্রাইব তৌখ্রে।",
        FAILED_TO_SUBSCRIBE: "সবস্ক্রাইব তৌবদা ফেইল তৌখ্রে।",
        N0_ANNOUNCEMENTS_FOUND: "অনাউন্সমেন্ত অমত্তা ফংখিদে",
        VIEW_OFFICIAL_SOURCE: "অফিসিয়েল সোর্স উবা",
        MORE_LIKE_THIS: "মসিগুম্বা অমুক"
    },
    नेपाली: {
        TITLE: "एउटै एकीकृत पोर्टलमा सबै आधिकारिक सरकारी घोषणाहरू पहुँच गर्नुहोस्।",
        DESCRIPTION: "जटिल सरकारी परिपत्रहरूलाई सरल भाषामा विभाजन गर्दछ। आफ्नो मनपर्ने भाषामा सबै मन्त्रालयका घोषणाहरू पहुँच गर्नुहोस्—पाठ वा अडियो। कुनै नोकरशाही शब्दजाल छैन, केवल स्पष्टता।",
        EXPLORE_ANNOUNCEMENTS: "घोषणाहरू अन्वेषण गर्नुहोस्",
        LATEST_ANNOUNCEMENTS: "नवीनतम घोषणाहरू",
        INPUT_PLACEHOLDER: "कीवर्ड, विभाग वा घोषणा शीर्षकद्वारा खोज्नुहोस्...",
        SEARCH: "खोज्नुहोस्",
        SEE_DETAILS: "विवरणहरू हेर्नुहोस्",
        LOAD_MORE: "थप हेर्नुहोस्",
        BACK: "फिर्ता",
        VIEW_MORE_ANNOUNCEMENTS: "थप घोषणाहरू हेर्नुहोस्",
        SHARE_ANNOUNCEMENT: "यो महत्त्वपूर्ण घोषणा साझा गर्नुहोस्",
        HELP_OTHERS_DISCOVER: "जानकारी फैलाउनुहोस् र आफ्नो समुदायलाई आधिकारिक सरकारी घोषणाहरूसँग अद्यावधिक रहन मद्दत गर्नुहोस्।",
        CHECK_OUT_THIS_AMAZING: "यो उपयोगी आधिकारिक सरकारी घोषणा हेर्नुहोस्:",
        SHARE_ON: "यसमार्फत साझा गर्नुहोस्",
        SUBSCRIBE_TO_ALERTS: "सूचनाहरूको सदस्यता लिनुहोस्",
        NEVER_MISS_AN_UPDATE: "नवीनतम नीति परिवर्तनहरू र घोषणाहरूसँग जानकारी राख्नुहोस्। साप्ताहिक घोषणाहरू सीधा आफ्नो मेलमा प्राप्त गर्नुहोस्।",
        PLEASE_ENTER_YOUR_EMAIL: "कृपया आफ्नो इमेल प्रविष्ट गर्नुहोस्।",
        SUBSCRIBE: "सदस्यता लिनुहोस्",
        SOMETHING_WENT_WRONG: "केही गलत भयो।",
        PLEASE_ENTER_A_VALID_EMAIL: "इमेल ढाँचा गलत छ।",
        SUCCESSFULLY_SUBSCRIBED: "तपाईंले सफलतापूर्वक सदस्यता लिनुभयो।",
        FAILED_TO_SUBSCRIBE: "सदस्यता लिन असफल।",
        N0_ANNOUNCEMENTS_FOUND: "कुनै घोषणा भेटिएन",
        VIEW_OFFICIAL_SOURCE: "आधिकारिक स्रोत हेर्नुहोस्",
        MORE_LIKE_THIS: "यस्तै अरू"
    },
    ଓଡ଼ିଆ: {
        TITLE: "ଗୋଟିଏ ଏକୀକୃତ ପୋର୍ଟାଲରେ ସମସ୍ତ ସରକାରୀ ଘୋଷଣାକୁ ଆକ୍ସେସ କରନ୍ତୁ।",
        DESCRIPTION: "ଜଟିଳ ସରକାରୀ ସର୍କୁଲାରଗୁଡ଼ିକୁ ସରଳ ଭାଷାରେ ବିଭାଜନ କରେ। ଆପଣଙ୍କ ପସନ୍ଦର ଭାଷାରେ ସମସ୍ତ ମନ୍ତ୍ରଣାଳୟର ଘୋଷଣାକୁ ଆକ୍ସେସ କରନ୍ତୁ—ପାଠ୍ୟ କିମ୍ବା ଅଡିଓ। କୌଣସି ଅମଲାତାନ୍ତ୍ରିକ ଶବ୍ଦଜାଲ ନାହିଁ, କେବଳ ସ୍ପଷ୍ଟତା।",
        EXPLORE_ANNOUNCEMENTS: "ଘୋଷଣାଗୁଡ଼ିକ ଅନ୍ବେଷଣ କରନ୍ତୁ",
        LATEST_ANNOUNCEMENTS: "ସର୍ବଶେଷ ଘୋଷଣାଗୁଡ଼ିକ",
        INPUT_PLACEHOLDER: "କୀୱାର୍ଡ, ବିଭାଗ କିମ୍ବା ଘୋଷଣା ଶୀର୍ଷକ ଦ୍ୱାରା ଖୋଜନ୍ତୁ...",
        SEARCH: "ଖୋଜନ୍ତୁ",
        SEE_DETAILS: "ବିବରଣୀ ଦେଖନ୍ତୁ",
        LOAD_MORE: "ଅଧିକ ଦେଖନ୍ତୁ",
        BACK: "ପଛକୁ",
        VIEW_MORE_ANNOUNCEMENTS: "ଅଧିକ ଘୋଷଣା ଦେଖନ୍ତୁ",
        SHARE_ANNOUNCEMENT: "ଏହି ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ଘୋଷଣା ସେୟାର କରନ୍ତୁ",
        HELP_OTHERS_DISCOVER: "ସୂଚନା ପ୍ରସାର କରନ୍ତୁ ଏବଂ ଆପଣଙ୍କ ସମୁଦାୟକୁ ସରକାରୀ ଘୋଷଣା ସହ ଅପଡେଟ୍ ରହିବାରେ ସାହାଯ୍ୟ କରନ୍ତୁ।",
        CHECK_OUT_THIS_AMAZING: "ଏହି ଉପଯୋଗୀ ସରକାରୀ ଘୋଷଣା ଦେଖନ୍ତୁ:",
        SHARE_ON: "ଏହା ମାଧ୍ୟମରେ ସେୟାର କରନ୍ତୁ",
        SUBSCRIBE_TO_ALERTS: "ବିଜ୍ଞପ୍ତି ପାଇଁ ସବସ୍କ୍ରାଇବ କରନ୍ତୁ",
        NEVER_MISS_AN_UPDATE: "ସର୍ବଶେଷ ନୀତି ପରିବର୍ତ୍ତନ ଏବଂ ଘୋଷଣା ସହ ସୂଚିତ ରୁହନ୍ତୁ। ସାପ୍ତାହିକ ଘୋଷଣାଗୁଡ଼ିକ ସିଧାସଳଖ ଆପଣଙ୍କ ମେଲରେ ପାଆନ୍ତୁ।",
        PLEASE_ENTER_YOUR_EMAIL: "ଦୟାକରି ଆପଣଙ୍କ ଇମେଲ ପ୍ରବେଶ କରନ୍ତୁ।",
        SUBSCRIBE: "ସବସ୍କ୍ରାଇବ କରନ୍ତୁ",
        SOMETHING_WENT_WRONG: "କିଛି ଭୁଲ ହୋଇଗଲା।",
        PLEASE_ENTER_A_VALID_EMAIL: "ଇମେଲ ଫର୍ମାଟ ଭୁଲ ଅଛି।",
        SUCCESSFULLY_SUBSCRIBED: "ଆପଣ ସଫଳତାର ସହ ସବସ୍କ୍ରାଇବ କରିଛନ୍ତି।",
        FAILED_TO_SUBSCRIBE: "ସବସ୍କ୍ରାଇବ କରିବାରେ ବିଫଳ।",
        N0_ANNOUNCEMENTS_FOUND: "କୌଣସି ଘୋଷଣା ମିଳିଲା ନାହିଁ",
        VIEW_OFFICIAL_SOURCE: "ସରକାରୀ ଉତ୍ସ ଦେଖନ୍ତୁ",
        MORE_LIKE_THIS: "ଏହିଭଳି ଅଧିକ"
    },
    ਪੰਜਾਬੀ: {
        TITLE: "ਇੱਕ ਇਕੱਠੇ ਪੋਰਟਲ ਵਿੱਚ ਸਾਰੇ ਸਰਕਾਰੀ ਐਲਾਨਾਂ ਤੱਕ ਪਹੁੰਚ ਪ੍ਰਾਪਤ ਕਰੋ।",
        DESCRIPTION: "ਗੁੰਝਲਦਾਰ ਸਰਕਾਰੀ ਸਰਕੂਲਰਾਂ ਨੂੰ ਸਰਲ ਭਾਸ਼ਾ ਵਿੱਚ ਸਮਝਾਉਂਦਾ ਹੈ। ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਵਿੱਚ ਸਾਰੇ ਮੰਤਰਾਲਿਆਂ ਦੇ ਐਲਾਨਾਂ ਤੱਕ ਪਹੁੰਚ—ਲਿਖਤ ਜਾਂ ਆਡੀਓ। ਕੋਈ ਦਫ਼ਤਰੀ ਸ਼ਬਦਾਵਲੀ ਨਹੀਂ, ਸਿਰਫ਼ ਸਪੱਸ਼ਟਤਾ।",
        EXPLORE_ANNOUNCEMENTS: "ਐਲਾਨਾਂ ਦੀ ਪੜਚੋਲ ਕਰੋ",
        LATEST_ANNOUNCEMENTS: "ਤਾਜ਼ਾ ਐਲਾਨ",
        INPUT_PLACEHOLDER: "ਕੀਵਰਡ, ਵਿਭਾਗ, ਜਾਂ ਐਲਾਨ ਦੇ ਸਿਰਲੇਖ ਨਾਲ ਖੋਜੋ...",
        SEARCH: "ਖੋਜੋ",
        SEE_DETAILS: "ਵੇਰਵੇ ਦੇਖੋ",
        LOAD_MORE: "ਹੋਰ ਲੋਡ ਕਰੋ",
        BACK: "ਪਿੱਛੇ",
        VIEW_MORE_ANNOUNCEMENTS: "ਹੋਰ ਐਲਾਨ ਦੇਖੋ",
        SHARE_ANNOUNCEMENT: "ਇਹ ਮਹੱਤਵਪੂਰਨ ਐਲਾਨ ਸਾਂਝਾ ਕਰੋ",
        HELP_OTHERS_DISCOVER: "ਖ਼ਬਰ ਫੈਲਾਓ ਅਤੇ ਆਪਣੇ ਭਾਈਚਾਰੇ ਨੂੰ ਸਰਕਾਰੀ ਐਲਾਨਾਂ ਨਾਲ ਅੱਪਡੇਟ ਰਹਿਣ ਵਿੱਚ ਮਦਦ ਕਰੋ।",
        CHECK_OUT_THIS_AMAZING: "ਇਹ ਲਾਭਦਾਇਕ ਸਰਕਾਰੀ ਐਲਾਨ ਦੇਖੋ:",
        SHARE_ON: "ਰਾਹੀਂ ਸਾਂਝਾ ਕਰੋ",
        SUBSCRIBE_TO_ALERTS: "ਸੂਚਨਾਵਾਂ ਲਈ ਗਾਹਕੀ ਲਓ",
        NEVER_MISS_AN_UPDATE: "ਨਵੀਨਤਮ ਨੀਤੀਗਤ ਬਦਲਾਵਾਂ ਅਤੇ ਐਲਾਨਾਂ ਤੋਂ ਸੂਚਿਤ ਰਹੋ। ਹਫ਼ਤਾਵਾਰੀ ਐਲਾਨ ਸਿੱਧੇ ਆਪਣੀ ਈਮੇਲ ਵਿੱਚ ਪ੍ਰਾਪਤ ਕਰੋ।",
        PLEASE_ENTER_YOUR_EMAIL: "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ ਈਮੇਲ ਦਰਜ ਕਰੋ।",
        SUBSCRIBE: "ਗਾਹਕੀ ਲਓ",
        SOMETHING_WENT_WRONG: "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ।",
        PLEASE_ENTER_A_VALID_EMAIL: "ਈਮੇਲ ਫਾਰਮੈਟ ਗਲਤ ਹੈ।",
        SUCCESSFULLY_SUBSCRIBED: "ਤੁਸੀਂ ਸਫਲਤਾਪੂਰਵਕ ਗਾਹਕੀ ਲੈ ਲਈ ਹੈ।",
        FAILED_TO_SUBSCRIBE: "ਗਾਹਕੀ ਲੈਣ ਵਿੱਚ ਅਸਫਲ।",
        N0_ANNOUNCEMENTS_FOUND: "ਕੋਈ ਐਲਾਨ ਨਹੀਂ ਮਿਲਿਆ",
        VIEW_OFFICIAL_SOURCE: "ਅਧਿਕਾਰਕ ਸਰੋਤ ਦੇਖੋ",
        MORE_LIKE_THIS: "ਇਸ ਤਰ੍ਹਾਂ ਦੇ ਹੋਰ"
    },
    संस्कृतम्: {
        TITLE: "एकस्मिन् एकीकृते द्वारे सर्वाणि शासकीयघोषणानि प्राप्नुवन्तु।",
        DESCRIPTION: "जटिलानि शासकीयपरिपत्राणि सरलभाषायां विभजति। सर्वेषु मन्त्रालयेषु घोषणानाम् भवतः रोचितभाषायाम् प्राप्तिः—पाठरूपेण श्रव्यरूपेण वा। न कापि कार्यालयीना शब्दावली, केवलं स्पष्टता।",
        EXPLORE_ANNOUNCEMENTS: "घोषणानाम् अन्वेषणं कुर्वन्तु",
        LATEST_ANNOUNCEMENTS: "नवीनतमघोषणाः",
        INPUT_PLACEHOLDER: "मुख्यशब्देन, विभागेन, घोषणाशीर्षकेण वा अन्विष्यन्तु...",
        SEARCH: "अन्वेषणम्",
        SEE_DETAILS: "विवरणानि पश्यन्तु",
        LOAD_MORE: "अधिकं लोडयन्तु",
        BACK: "पश्चात्",
        VIEW_MORE_ANNOUNCEMENTS: "अधिकघोषणानि पश्यन्तु",
        SHARE_ANNOUNCEMENT: "एतद् महत्त्वपूर्णघोषणां साझां कुर्वन्तु",
        HELP_OTHERS_DISCOVER: "वार्तां प्रसारयन्तु तथा च स्वसमुदायं शासकीयघोषणाभिः अद्यतनं भवितुं साहाय्यं कुर्वन्तु।",
        CHECK_OUT_THIS_AMAZING: "एतद् उपयोगि शासकीयघोषणां पश्यन्तु:",
        SHARE_ON: "द्वारा साझां कुर्वन्तु",
        SUBSCRIBE_TO_ALERTS: "सूचनानाम् अभिदानं स्वीकुर्वन्तु",
        NEVER_MISS_AN_UPDATE: "नवीनतमनीतिपरिवर्तनैः घोषणाभिश्च सूचितास्तिष्ठन्तु। साप्ताहिकघोषणानि साक्षात् स्वविद्युत्पत्रे प्राप्नुवन्तु।",
        PLEASE_ENTER_YOUR_EMAIL: "कृपया स्वविद्युत्पत्रसङ्केतं प्रविशन्तु।",
        SUBSCRIBE: "अभिदानं स्वीकुर्वन्तु",
        SOMETHING_WENT_WRONG: "किमपि दोषः अभवत्।",
        PLEASE_ENTER_A_VALID_EMAIL: "विद्युत्पत्रस्य प्रारूपं न्यूनम् अस्ति।",
        SUCCESSFULLY_SUBSCRIBED: "भवन्तः सफलतया अभिदानं स्वीकृतवन्तः।",
        FAILED_TO_SUBSCRIBE: "अभिदानस्वीकारे असफलता।",
        N0_ANNOUNCEMENTS_FOUND: "किमपि घोषणा न प्राप्तम्",
        VIEW_OFFICIAL_SOURCE: "आधिकारिकस्रोतं पश्यन्तु",
        MORE_LIKE_THIS: "एवमेव अधिकानि"
    },
    ᱥᱟᱱᱛᱟᱲᱤ: {
        TITLE: "ᱢᱤᱫ ᱮᱠᱟᱞ ᱯᱚᱨᱴᱟᱞ ᱨᱮ ᱡᱷᱚᱛᱚ ᱥᱚᱨᱠᱟᱨᱤ ᱠᱷᱚᱵᱚᱨ ᱠᱚ ᱧᱟᱢ ᱢᱮ᱾",
        DESCRIPTION: "ᱡᱷᱟᱹᱞ ᱥᱚᱨᱠᱟᱨᱤ ᱥᱚᱨᱠᱩᱞᱟᱨ ᱠᱚ ᱥᱚᱡᱷᱮ ᱯᱟᱹᱨᱥᱤ ᱛᱮ ᱵᱩᱡᱷᱟᱹᱣᱟ᱾ ᱡᱷᱚᱛᱚ ᱢᱚᱱᱛᱨᱤᱢᱚᱱᱰᱚᱲ ᱠᱷᱚᱱ ᱠᱷᱚᱵᱚᱨ ᱠᱚ ᱟᱢᱟᱜ ᱠᱩᱥᱤᱭᱟᱜ ᱯᱟᱹᱨᱥᱤ ᱛᱮ ᱧᱟᱢ ᱢᱮ—ᱚᱞ ᱟᱨᱵᱟᱝ ᱟᱲᱟᱝ᱾ ᱫᱚᱯᱷᱛᱚᱨᱤᱭᱟᱹ ᱟᱹᱲᱟᱹ ᱵᱟᱹᱱᱩᱜ, ᱠᱷᱟᱹᱞᱤ ᱥᱟᱹᱦᱤ ᱠᱟᱛᱷᱟ᱾",
        EXPLORE_ANNOUNCEMENTS: "ᱠᱷᱚᱵᱚᱨ ᱠᱚ ᱯᱟᱱᱛᱮ ᱢᱮ",
        LATEST_ANNOUNCEMENTS: "ᱱᱟᱶᱟ ᱠᱷᱚᱵᱚᱨ ᱠᱚ",
        INPUT_PLACEHOLDER: "ᱢᱩᱲᱩᱛ ᱟᱹᱲᱟᱹ, ᱵᱤᱵᱷᱟᱜᱽ, ᱟᱨᱵᱟᱝ ᱠᱷᱚᱵᱚᱨ ᱧᱩᱛᱩᱢ ᱛᱮ ᱯᱟᱱᱛᱮ ᱢᱮ...",
        SEARCH: "ᱯᱟᱱᱛᱮ",
        SEE_DETAILS: "ᱵᱤᱵᱨᱚᱱ ᱧᱮᱞ ᱢᱮ",
        LOAD_MORE: "ᱰᱷᱮᱨ ᱞᱳᱰ ᱢᱮ",
        BACK: "ᱛᱟᱭᱚᱢ",
        VIEW_MORE_ANNOUNCEMENTS: "ᱰᱷᱮᱨ ᱠᱷᱚᱵᱚᱨ ᱠᱚ ᱧᱮᱞ ᱢᱮ",
        SHARE_ANNOUNCEMENT: "ᱱᱚᱶᱟ ᱞᱟᱹᱠᱛᱤᱭᱟᱱ ᱠᱷᱚᱵᱚᱨ ᱦᱟᱹᱴᱤᱧ ᱢᱮ",
        HELP_OTHERS_DISCOVER: "ᱠᱷᱚᱵᱚᱨ ᱯᱟᱥᱱᱟᱣ ᱠᱟᱛᱮ ᱟᱢᱟᱜ ᱥᱚᱢᱟᱡᱽ ᱥᱚᱨᱠᱟᱨᱤ ᱠᱷᱚᱵᱚᱨ ᱠᱚ ᱛᱮ ᱦᱟᱹᱞᱤ ᱨᱮ ᱫᱚᱦᱚ ᱢᱮ᱾",
        CHECK_OUT_THIS_AMAZING: "ᱱᱚᱶᱟ ᱜᱚᱲᱚᱣᱟᱱ ᱥᱚᱨᱠᱟᱨᱤ ᱠᱷᱚᱵᱚᱨ ᱧᱮᱞ ᱢᱮ:",
        SHARE_ON: "ᱰᱟᱦᱟᱨ ᱛᱮ ᱦᱟᱹᱴᱤᱧ ᱢᱮ",
        SUBSCRIBE_TO_ALERTS: "ᱠᱷᱚᱵᱚᱨ ᱞᱟᱹᱜᱤᱫ ᱚᱝᱜᱚ ᱫᱚᱦᱚ ᱢᱮ",
        NEVER_MISS_AN_UPDATE: "ᱱᱟᱶᱟ ᱱᱤᱛᱤ ᱵᱚᱫᱚᱞ ᱟᱨ ᱠᱷᱚᱵᱚᱨ ᱠᱚ ᱛᱮ ᱵᱟᱰᱟᱭ ᱠᱟᱛᱮ ᱛᱟᱸᱦᱮᱸᱱ ᱢᱮ᱾ ᱦᱟᱯᱛᱟ ᱦᱤᱥᱟᱹᱵᱽ ᱛᱮ ᱠᱷᱚᱵᱚᱨ ᱠᱚ ᱥᱤᱫᱷᱟᱹ ᱟᱢᱟᱜ ᱤᱢᱮᱞ ᱨᱮ ᱧᱟᱢ ᱢᱮ᱾",
        PLEASE_ENTER_YOUR_EMAIL: "ᱫᱚᱭᱟ ᱠᱟᱛᱮ ᱟᱢᱟᱜ ᱤᱢᱮᱞ ᱚᱞ ᱢᱮ᱾",
        SUBSCRIBE: "ᱚᱝᱜᱚ ᱫᱚᱦᱚ ᱢᱮ",
        SOMETHING_WENT_WRONG: "ᱪᱮᱫ ᱵᱷᱩᱞ ᱦᱩᱭ ᱮᱱᱟ᱾",
        PLEASE_ENTER_A_VALID_EMAIL: "ᱤᱢᱮᱞ ᱯᱷᱚᱨᱢᱮᱴ ᱵᱷᱩᱞ ᱜᱮᱭᱟ᱾",
        SUCCESSFULLY_SUBSCRIBED: "ᱟᱢ ᱵᱮᱥ ᱛᱮ ᱚᱝᱜᱚ ᱫᱚᱦᱚ ᱠᱮᱫᱟᱢ᱾",
        FAILED_TO_SUBSCRIBE: "ᱚᱝᱜᱚ ᱫᱚᱦᱚ ᱨᱮ ᱵᱟᱹᱲᱤᱡ᱾",
        N0_ANNOUNCEMENTS_FOUND: "ᱡᱟᱦᱟᱸ ᱠᱷᱚᱵᱚᱨ ᱵᱟᱹᱱᱩᱜ-ᱟ",
        VIEW_OFFICIAL_SOURCE: "ᱥᱚᱨᱠᱟᱨᱤ ᱡᱟᱜᱟ ᱧᱮᱞ ᱢᱮ",
        MORE_LIKE_THIS: "ᱱᱚᱝᱠᱟ ᱜᱮ ᱰᱷᱮᱨ"
    },
    سنڌي: {
        TITLE: "هڪ متحد پورٽل ۾ سڀني سرڪاري اعلانن تائين رسائي حاصل ڪريو.",
        DESCRIPTION: "پيچيده سرڪاري سرڪيولرز کي سادي ٻولي ۾ ٽوڙي ٿو. توهان جي پسنديده ٻولي ۾ سڀني وزارتن جي اعلانن تائين رسائي- متن يا آڊيو. ڪابه دفتري اصطلاح نه، رڳو وضاحت.",
        EXPLORE_ANNOUNCEMENTS: "اعلانن جي ڳولا ڪريو",
        LATEST_ANNOUNCEMENTS: "تازيون اعلان",
        INPUT_PLACEHOLDER: "لفظ، شعبي، يا اعلان جي عنوان سان ڳوليو...",
        SEARCH: "ڳوليو",
        SEE_DETAILS: "تفصيل ڏسو",
        LOAD_MORE: "وڌيڪ لوڊ ڪريو",
        BACK: "واپس",
        VIEW_MORE_ANNOUNCEMENTS: "وڌيڪ اعلان ڏسو",
        SHARE_ANNOUNCEMENT: "هي اهم اعلان شيئر ڪريو",
        HELP_OTHERS_DISCOVER: "لفظ پکيڙيو ۽ پنهنجي ڪميونٽي کي سرڪاري اعلانن سان اپڊيٽ رهڻ ۾ مدد ڪريو.",
        CHECK_OUT_THIS_AMAZING: "هي مفيد سرڪاري اعلان ڏسو:",
        SHARE_ON: "ذريعي شيئر ڪريو",
        SUBSCRIBE_TO_ALERTS: "اطلاعن جي رڪنيت حاصل ڪريو",
        NEVER_MISS_AN_UPDATE: "تازين پاليسي تبديلين ۽ اعلانن کان باخبر رهو. هفتيوار اعلان سڌو پنهنجي ميل ۾ حاصل ڪريو.",
        PLEASE_ENTER_YOUR_EMAIL: "مهرباني ڪري پنهنجو اي ميل داخل ڪريو.",
        SUBSCRIBE: "رڪنيت حاصل ڪريو",
        SOMETHING_WENT_WRONG: "ڪجهه غلط ٿي ويو.",
        PLEASE_ENTER_A_VALID_EMAIL: "اي ميل جو فارميٽ غلط آهي.",
        SUCCESSFULLY_SUBSCRIBED: "توهان ڪاميابي سان رڪنيت حاصل ڪري ورتي آهي.",
        FAILED_TO_SUBSCRIBE: "رڪنيت حاصل ڪرڻ ۾ ناڪام.",
        N0_ANNOUNCEMENTS_FOUND: "ڪا به اعلان نه مليو",
        VIEW_OFFICIAL_SOURCE: "سرڪاري ذريعو ڏسو",
        MORE_LIKE_THIS: "اهڙا وڌيڪ"
    }
};