name: Scheduled Scraper

on:
  schedule:
    - cron: "0 */2 * * *"   
  workflow_dispatch:        

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger update announcements endpoint
        run: |
          curl -X POST https://indiangovtoday.app/updateannouncements \
          -H "Content-Type: application/json"
